import { q } from '../helpers.mjs';
const R = (id, additions, extra = {}) => ({ id: `b1-adab-${id}`, level: 'B1', scriptDecision: 'reviewed; strengthened for evidence, proportionality, safety, privacy, rights, and respectful correction', tags: { 0:'thoughtful',2:'carefully',4:'reflective',6:'honestly',8:'seriously',10:'gently',12:'encouraging',14:'sincere',16:'thoughtful',18:'carefully' }, additions, ...extra });
export const reviews = [
  R('01', [
    q('When may a public correction be needed?', 'When delay risks material harm or the audience needs an accurate record', 'Only when someone is embarrassed', 'Never in a meeting', 'After the figures are forgotten', 'Privacy is not an absolute rule.'),
    q('What should the narrator verify first?', 'The data source, scope, and seriousness of the possible error', 'Whether the manager likes feedback', 'Who is watching', 'The next meeting date', 'Confidence is not proof.'),
    q('What should happen after a private check?', 'The responsible authority corrects the record through the right channel', 'The narrator deletes the figures', 'The team is left uninformed', 'The manager hides the error', 'Repair includes audience accuracy.'),
    q('Why can public correction still be respectful?', 'It can be factual, proportionate, and focused on the record rather than humiliation', 'It always proves disloyalty', 'It requires blaming a person', 'It prevents future questions', 'Tone and purpose matter.'),
    q('What must not guide the choice?', 'Fear of embarrassment when safety, fairness, or material decisions are affected', 'A reliable source', 'A clear correction route', 'The effect on listeners', 'Adab does not conceal damaging error.'),
  ], { replaceText: [
    ['Even though I was fairly certain I was right, I decided the timing mattered just as much as the accuracy of the information itself.', 'I first checked the source and scope. Privacy mattered, but urgent safety, fairness, legal, financial, or material decisions could require immediate factual correction.'],
    ['Unless silence would cause real damage, I will always choose privacy over an audience when pointing out an error.', 'I will choose the least harmful effective channel, but will not use privacy to delay necessary correction or leave others acting on false information.'],
  ] }),
  R('02', [
    q('What makes advice more respectful?', 'Permission or a specific safety reason with proportionate evidence', 'Comparing generations', 'Public instructions', 'Assuming a parent has not thought', 'Method affects reception.'),
    q('Who holds parenting authority?', 'Dinda as the parent, subject to genuine safety and legal duties', 'Yusuf', 'The aunt', 'Every neighbor', 'Advice does not replace guardianship.'),
    q('What should a serious concern include?', 'Specific observation, urgency, evidence, and an appropriate support route', 'A vague fear', 'A public accusation', 'A demand for obedience', 'Concern must be actionable.'),
    q('Why is screen time not settled by one opinion?', 'Age, content, sleep, accessibility, family context, and evidence differ', 'Television is always harmful', 'Relatives choose all rules', 'Children need no routine', 'Parenting claims require context.'),
    q('What boundary can Dinda set?', 'Please ask before advice and avoid judgmental comparison', 'Never speak to me again', 'Tell everyone my child is unsafe', 'Accept every comment', 'A boundary can be courteous.'),
  ]),
  R('03', [
    q('Why can private messaging be insufficient?', 'A false public claim may require a visible correction for readers', 'Private messages are rude', 'All disagreement is public', 'Comments cannot be edited', 'Audience impact matters.'),
    q('What should Fikri do before replying?', 'Verify facts, policy, authority, risk, and account authenticity', 'Assume the critic is malicious', 'Delete every comment', 'Ask followers to attack', 'Moderation begins with assessment.'),
    q('What requires formal escalation?', 'Threats, doxxing, harassment, safeguarding, fraud, or unlawful content', 'A calm factual question', 'A spelling error', 'A different opinion', 'Some conduct exceeds dialogue.'),
    q('How can a public reply show adab?', 'State verified facts and boundaries without shaming or exposing private data', 'Win with insults', 'Reveal private messages', 'Promise unchecked facts', 'Respect does not mean silence.'),
    q('What is the goal of private discussion?', 'Resolve suitable issues, not hide accountability or public correction', 'Avoid evidence', 'Protect false claims', 'End criticism', 'Channel follows purpose.'),
  ], { replaceText: [
    ['whenever possible, move disagreements into private conversation.', 'use the channel that fits the risk: private dialogue for suitable matters; visible correction for public misinformation; and formal reporting for threats, harassment, safeguarding, fraud, or unlawful content.'],
  ] }),
  R('04', [
    q('What makes feedback usable?', 'Specific examples, expected standard, evidence, and a chance to clarify', 'A vague personal judgment', 'Public embarrassment', 'A demand for gratitude', 'Actionable feedback is bounded.'),
    q('Why might repeating a point be unsafe?', 'Power imbalance or hostile feedback may require documentation and another channel', 'Listening is always harmful', 'Colleagues dislike summaries', 'Feedback must be accepted', 'Safety changes the response.'),
    q('What can the narrator do after understanding?', 'Ask questions, provide evidence, disagree, or use review routes', 'Agree automatically', 'Ignore the concern', 'Share private records', 'Understanding precedes judgment.'),
    q('What must a mentor avoid?', 'Humiliation, discrimination, harassment, retaliation, or false certainty', 'Clear standards', 'Private feedback', 'A review process', 'Adab includes power use.'),
    q('What distinguishes hearing from defending?', 'Understanding a concern before choosing how to respond', 'Silence always', 'Accepting everything', 'Repeating words without meaning', 'Listening supports a reasoned reply.'),
  ]),
  R('05', [
    q('Who determines driving restrictions?', 'The relevant clinician, licensing authority, law, and formal assessment process', 'The siblings alone', 'The father’s friends', 'A daylight rule', 'Family concern is not authoritative.'),
    q('Why is daylight-only driving unsafe as a default?', 'It may ignore assessed impairment and legal restrictions', 'Daylight is always dangerous', 'Cars cannot travel by day', 'It removes independence', 'A compromise needs evidence.'),
    q('What support can preserve dignity?', 'Transport planning, accessible services, involvement, and alternatives', 'Hiding the keys', 'Public pressure', 'Ignoring assessment', 'Autonomy includes support.'),
    q('When is urgent action required?', 'When an authorized professional or law identifies immediate serious risk', 'Whenever siblings disagree', 'After a flight booking', 'Only after an accident', 'Risk response follows authority.'),
    q('What do siblings owe their father?', 'Respect, truthful communication, lawful safety action, and inclusion', 'Unlimited driving access', 'A secret decision', 'An impossible promise', 'Care combines dignity and protection.'),
  ], { replaceScript: [
    'Wulan: [carefully] Bagas, Dad’s clinician raised driving concerns. We need the written advice, his consent where possible, and the relevant licensing and legal rules.',
    'Bagas: [thoughtful] I want to protect his independence, but we cannot ignore a current serious safety restriction.',
    'Wulan: The clinician and authority must assess function, medicines, vision, cognition, and the legal process. We cannot invent a daylight-only compromise.',
    'Bagas: [reflective] If driving changes, we should involve Dad and arrange transport, appointments, deliveries, and accessible alternatives.',
    'Wulan: [carefully] We will share health information only with people who need it and with his agreement where possible.',
    'Bagas: What if he refuses an urgent restriction?',
    'Wulan: Then we follow the clinician’s and authority’s emergency guidance. Depending on local law and risk, action may go beyond a family conversation.',
    'Bagas: [thoughtful] This is a safety and rights process in which Dad should have a voice.',
    'Wulan: We can ask about reassessment, rehabilitation, support, and documented next steps.',
    'Bagas: [gently] Let us meet him with information, not a secret decision already made behind his back.',
    'Wulan: We can say we love him, are worried about safety, and want to plan alternatives with him.',
    'Bagas: [sincere] I will ask the clinic what consent and support they need from us.',
    'Wulan: We should ask about costs, accessible transport, appointments, delivery services, and whether he wants a trusted person at each discussion.',
    'Bagas: I will also listen if he feels grief, anger, or fear. Those feelings do not prove he lacks capacity, and they should not be used to silence him.',
    'Wulan: [encouraging] Patience means listening and following qualified guidance, not delaying serious risk because the conversation is painful.',
    'Bagas: Our role is respectful support, honest communication, and lawful action—not diagnosing driving fitness.',
  ] }),
  R('06', [
    q('What should a guest do about a food need?', 'Tell the host early and discuss a suitable option', 'Criticize at the table', 'Assume every dish is safe', 'Hide an allergy', 'Advance communication protects both people.'),
    q('Why are repeated jokes harmful?', 'They can turn a host’s effort or culture into public criticism', 'Humor is forbidden', 'Spice has no meaning', 'Hosts never notice tone', 'Impact can differ from intent.'),
    q('What makes the apology specific?', 'It names comments, acknowledges impact, and changes behavior', 'It asks whether the host is angry', 'It lists stress', 'It demands forgiveness', 'Repair centers the affected person.'),
    q('What should the narrator not infer?', 'A kind reply proves no harm occurred', 'All hosts are offended', 'The meal was unsafe', 'Apology is useless', 'Grace does not erase impact.'),
    q('What can the narrator do next time?', 'Ask about food, bring an agreed alternative, and praise effort honestly', 'Compare recipes publicly', 'Eat allergens', 'Invent medical advice', 'Adab includes preparation.'),
  ]),
  R('07', [
    q('What does declining not cancel?', 'A valid duty, emergency response, care arrangement, or contractual commitment', 'Personal privacy', 'A polite thank-you', 'The right to rest', 'Limits require assessment.'),
    q('Why keep a decline brief?', 'It can protect privacy without a false excuse', 'No explanation is ever allowed', 'Hosts need no answer', 'All relatives are unsafe', 'Briefness is a choice.'),
    q('What if refusal may trigger coercion or harm?', 'Use a safety plan, trusted support, or appropriate formal help', 'Keep declining alone', 'Provide more personal data', 'Attend every event', 'Boundaries can be risky.'),
    q('When should an invitation be rearranged?', 'When responsibility requires an honest alternative or timely help', 'Whenever the host is older', 'Only when guilt appears', 'Never after exhaustion', 'Duty and capacity matter.'),
    q('What makes a yes genuine?', 'Free informed agreement within real capacity and responsibilities', 'Fear of displeasing', 'An invented excuse', 'A promise to exhaust oneself', 'Consent needs a meaningful no.'),
  ]),
  R('08', [
    q('Why were repeated poster results insufficient?', 'Repetition online did not establish a reliable source or grading', 'Posters cannot use Arabic', 'The group banned quotes', 'Relatives are scholars', 'Popularity is not authentication.'),
    q('What did the narrator ask the sender?', 'Where the wording came from', 'Why she wanted attention', 'Whether she lied', 'To leave the group', 'Private inquiry preserved dignity.'),
    q('Why was the general message not accepted as hadith?', 'Similar moral meaning does not prove prophetic attribution', 'Advice cannot be good', 'Teachers reject reminders', 'Translation is forbidden', 'Attribution needs evidence.'),
    q('What did the correction provide?', 'Uncertainty, a non-forwarding instruction, and verified references', 'Public punishment', 'A new unsupported quote', 'A vote', 'Repair offered a safe next step.'),
    q('What does the rule prevent?', 'Treating votes, algorithms, or emotion as source verification', 'All religious discussion', 'Respectful questions', 'Teacher guidance', 'The group adopts restraint.'),
  ]),
  R('09', [
    q('Why did the narrator call?', 'The delay needed direct ownership and repair options', 'Texting is always rude', 'The colleague had no phone', 'Calls erase impact', 'Channel served the situation.'),
    q('What did the ten-minute limit show?', 'The colleague’s time and childcare constraints remained valid', 'She forgave everything', 'The meeting had no value', 'Traffic was irrelevant', 'Repair follows capacity.'),
    q('Why were files not sent through personal chat?', 'Urgency did not remove information-security rules', 'Chats cannot send files', 'The colleague requested secrecy', 'Documents were public', 'Repair needs safe channels.'),
    q('What made trust uncertain?', 'One apology did not automatically restore confidence', 'The narrator arrived early later', 'The colleague rescheduled', 'Traffic reports existed', 'Trust belongs to the other person.'),
    q('What does the lesson reject?', 'Performing shame or demanding forgiveness', 'Practical repair', 'Truthful ownership', 'Changed behavior', 'Adab focuses outward.'),
  ]),
  R('10', [
    q('Why are verified figures needed?', 'Taste and loud voices should not decide resources', 'Budgets need no records', 'Flowers have no price', 'Access is only emotional', 'Evidence supports stewardship.'),
    q('What should be checked about orders?', 'Authorization and cancellation terms before blame', 'Volunteer personality', 'Flower color', 'Whether decoration is illegal', 'Facts precede judgment.'),
    q('What is a conflict of interest?', 'A relevant personal or financial interest needing disclosure and management', 'Any disagreement', 'A design preference', 'A safety need', 'Transparency protects decisions.'),
    q('Why may postponement be ethical?', 'The event should not promise services it cannot safely provide', 'Delay always saves money', 'Guests dislike access', 'Committees cannot revise plans', 'Honesty can change scope.'),
    q('What does respectful disagreement avoid?', 'Attacking motives while raising evidence and rights concerns', 'Asking questions', 'Recording decisions', 'Inviting participants', 'Adab permits accountable challenge.'),
  ]),
];
