import { q } from '../helpers.mjs';

const R = (id, decision, additions, extra = {}) => ({
  id: `b1-nature-${id}`,
  level: 'B1',
  scriptDecision: decision,
  tags: { 0: 'thoughtful', 2: 'carefully', 4: 'reflective', 6: 'honestly', 8: 'seriously', 10: 'gently', 12: 'encouraging', 14: 'sincere', 16: 'thoughtful', 18: 'carefully' },
  additions,
  ...extra,
});

export const reviews = [
  R('01', 'revise; anchor the retreat figure to displayed local monitoring, avoid a vague irreversible threshold, and distinguish personal reflection from climate evidence', [
    q('Why did the retreat figure affect the narrator more than a dramatic collapse?', 'It revealed a large cumulative change that was difficult to notice moment by moment', 'It proved the guide could predict every future year', 'It made the journey cheaper', 'It showed the glacier was moving toward the sea', 'Long records made slow change visible.'),
    q('What evidence supported the guide’s statement?', 'Dated surveys, mapped former edges, and local monitoring records', 'A single tourist photograph', 'The narrator’s memory from childhood', 'A sound heard inside the ice', 'The revision identifies the basis of the local claim.'),
    q('Why should the local number not be used for every glacier?', 'Glaciers differ by location and must be assessed with relevant records', 'All glaciers have identical measurements', 'Distance cannot be measured', 'Only tourists study ice', 'A site-specific observation is not a universal rate.'),
    q('What does the narrator separate in the conclusion?', 'Scientific evidence about ice from a personal analogy about noticing gradual change', 'Weather from clothing', 'Travel from cost', 'Patience from observation', 'The analogy is meaningful but not presented as proof.'),
    q('Which action is more precise than simply “caring”?', 'Supporting evidence-based emission reduction, adaptation, and local protection', 'Waiting for a visible collapse', 'Moving the stone markers', 'Ignoring changes too slow to film', 'Response is described through concrete categories.'),
  ], { replaceText: [
    ['I asked her how fast this particular glacier was retreating, and she said it had lost nearly two kilometers in the last thirty years alone.', 'I asked about this glacier. She pointed to dated local monitoring records showing that its mapped edge had retreated nearly two kilometers over the previous thirty years.'],
    ["She told us that scientists mark the ice's former edges with small stone posts, so that even though nothing seems to move day to day, the long retreat becomes undeniable over years.", 'She showed us dated surveys and marked former edges. Day-to-day change remained difficult to see, but repeated measurements created a clear local record over years.'],
    ['The guide, however, did not seem hopeless. She said that even slow damage can be slowed further, provided enough people actually care before it becomes irreversible.', 'The guide was serious but not hopeless. She discussed evidence-based emission reduction, adaptation, and local protection without promising that one visitor’s action could reverse every loss.'],
    ['Since that trip, whenever something in my own life changes gradually, a friendship cooling, a habit slipping, I try to notice it early, the way that guide notices her ice.', 'Since the trip, I use the glacier as a personal reminder to notice gradual change. That analogy is my reflection; the claim about the ice comes from measurements, not from my feelings.'],
  ] }),

  R('02', 'revise; remove the unsafe twenty-minute compromise under possible lightning and replace it with pre-agreed turnaround rules, immediate descent, and route-specific safety judgment', [
    q('Why is “we are nearly there” poor safety reasoning?', 'Past effort cannot reduce the hazard ahead', 'Summits always move farther away', 'Training makes clouds darker', 'Morning hikes are never completed', 'Sunk effort should not override current risk.'),
    q('What should partners agree before a hike?', 'Weather thresholds, turnaround time, route, communication, and emergency plan', 'Who gets the summit photograph', 'Which person complains first', 'A promise never to return', 'Pre-agreed limits reduce pressure during a difficult decision.'),
    q('Why do they descend without another twenty minutes?', 'Lightning and exposed terrain can worsen before certainty is available', 'They have forgotten their shoes', 'The outcrop is private property', 'The summit has closed permanently', 'Waiting for proof can remove the safety margin.'),
    q('How does Intan reinterpret success?', 'A safe return and sound decision can matter more than reaching the summit', 'Training was completely wasted', 'Made must choose every future route', 'Bad weather proves weak ability', 'The dialogue changes the definition of completion.'),
    q('What does partnership contribute?', 'A companion can challenge risky thinking and support a safe plan', 'A partner guarantees good weather', 'Two hikers need no forecast', 'Disagreement should be hidden', 'Constructive challenge is a safety resource.'),
  ], { baseQuiz: [
    q('Why does Made want to turn back?', 'Storm clouds and possible lightning threaten the exposed route', 'He has reached the summit', 'His food is missing', 'The trail is too quiet', 'The decision responds to a developing hazard.'),
    q('Why does Intan initially resist?', 'She connects the summit with months of training and personal success', 'She cannot see the clouds', 'Made has the map', 'She wants to shelter above the treeline', 'Emotional investment affects her judgment.'),
    q('What replaces the proposed compromise?', 'They follow the safer turnaround decision and descend promptly', 'They wait on exposed rock', 'They race the storm upward', 'They split into separate routes', 'The revision removes unnecessary additional exposure.'),
    q('What confirms the decision rather than causing it?', 'The clouds continue darkening after they have begun the safe response', 'The summit becomes visible', 'Another group passes them', 'The rain stops completely', 'They do not wait for certainty before acting.'),
    q('How does Intan feel about Made’s challenge?', 'Disappointed but grateful that he did not follow her blindly', 'Angry that he hid the forecast', 'Certain the training was useless', 'Unwilling to hike again', 'She recognizes the value of disagreement.'),
  ], replaceText: [
    ['What if we compromise? We climb another twenty minutes toward that flat outcrop, and if the clouds get darker, we descend immediately, no arguing.', 'Our plan says to leave exposed terrain when storm indicators reach this threshold. Let us descend now, stay together, and follow the safer route without waiting for certainty.'],
    ['Fine, twenty minutes. Although honestly, I already suspect how this ends.', 'I am disappointed, but you are right: the four hours already spent cannot make the next twenty minutes safer. I am ready to descend.'],
    ['Maybe. But at least we\'ll have decided together, instead of me simply forcing you to turn around against your judgment.', 'Thank you. Before our next attempt, we will review the forecast, route advice, turnaround time, communication, and emergency equipment again.'],
    ['Look, the clouds just darkened noticeably in the last few minutes. I think you were right after all.', 'The clouds have darkened while we are already moving down. I am glad we did not stay above the treeline to demand more proof.'],
    ['As a result, I suppose we\'re descending now, before this decision gets made for us by the weather instead.', 'I used to think turning back meant failure. Now I think a safe return and a sound decision are part of completing a mountain journey.'],
  ] }),

  R('03', 'revise; present rewilding as active, evidence-based stewardship with legal, ecological, neighbor, and monitoring responsibilities rather than simple neglect', [
    q('Why is rewilding not simply abandonment?', 'It may require research, invasive-species control, monitoring, and active risk management', 'Every plant must be removed', 'Farms automatically become forests', 'Neighbors lose all rights', 'The project reduces some control while retaining stewardship.'),
    q('Whose knowledge should shape a project?', 'Ecologists, land authorities, neighbors, and affected land users', 'Only online visitors', 'Only the landowner’s memories', 'Anyone selling seeds', 'Ecological action also has legal and social context.'),
    q('Why is the stream observation reported cautiously?', 'Its return was observed, but one project alone did not prove the cause', 'Streams cannot return', 'Owls created the water', 'The host did not see it', 'Observation and causal explanation are separated.'),
    q('What emotional change does Rani describe?', 'She learns that honoring her father need not mean freezing the land in one condition', 'She forgets that the farm existed', 'She decides agriculture is always wrong', 'She gives the land to the host', 'Memory and stewardship are reconciled.'),
    q('What advice replaces “try it on any unused land”?', 'Assess obligations and establish a suitable monitored plan before changing management', 'Stop all maintenance immediately', 'Introduce animals from another region', 'Promise visible results in three years', 'Responsible replication begins with assessment.'),
  ], { replaceText: [
    ['Essentially, it means stepping back and letting natural processes take over again, rather than continuing to control every inch the way farming requires.', 'It means restoring more space for natural processes, but not simply abandoning responsibility. We used ecological assessment, permissions, monitoring, and targeted management.'],
    ['Genuinely noticeable. We now have owls nesting in the old barn, deer passing through regularly, and a small stream that had dried up decades ago started flowing again.', 'We documented owls, deer, and water flowing again in part of an old stream. Those observations matter, but monitoring has not proved that our project alone caused every change.'],
    ['Be patient, because nature moves on its own schedule, and results that seem invisible in year one often become undeniable by year three.', 'First consult relevant ecologists, authorities, neighbors, and land users. Check legal duties, fire and invasive-species risks, water, animal welfare, and long-term monitoring before changing management.'],
    ["Thank you for having me. I hope it encourages someone listening to try something similar with their own quiet corner of land.", 'Thank you. I hope listeners value restoration while recognizing that each site needs its own evidence, permissions, community discussion, and plan.'],
  ] }),

  R('04', 'revise; qualify navigation and light claims, add safe authorized rooftop access, and avoid suggesting one household action has a known population effect', [
    q('What first helped the narrator notice birds at night?', 'Learning to recognize calls before seeing the birds clearly', 'Buying a brighter roof light', 'Following the birds south', 'Closing every window', 'Listening changed what the city environment revealed.'),
    q('Why is the rooftop detail qualified?', 'Observation requires permission, barriers, safe access, and suitable conditions', 'All roofs are public', 'Birds avoid lower floors', 'Headlamps prevent falls', 'A poetic setting should not become unsafe advice.'),
    q('How is artificial light described responsibly?', 'Research links unnecessary night light with migration risks, but effects vary by species and conditions', 'One lamp always causes a bird to fail', 'Stars are the only navigation cue', 'City light has no ecological effect', 'The revision avoids an absolute causal statement.'),
    q('What does the neighbor’s action represent?', 'A practical contribution within a wider evidence-based effort', 'Proof that his apartment saved the migration', 'A replacement for city policy', 'A reason to make streets unsafe', 'The action is useful without inflated impact.'),
    q('Which lights should not simply be switched off?', 'Lighting needed for safety, accessibility, or legal requirements', 'Decorative empty-room lights', 'Unused advertising after closing', 'An apartment light with no occupant', 'Risk reduction must preserve human safety.'),
  ], { replaceText: [
    ['He explained that certain species travel thousands of kilometers each year, navigating partly by stars, even though scientists still don\'t fully understand every method they use.', 'He explained that some species travel thousands of kilometers and may use several cues, including celestial, magnetic, visual, and learned information; the mix varies and remains an active research area.'],
    ['He told me that if the city lights grew brighter every year, fewer birds would successfully complete their journey, since artificial light disorients their navigation badly.', 'He said research links unnecessary artificial light at night with risks such as attraction, disorientation, and collision during migration, although effects vary by species and conditions.'],
    ['As a result, he now turns off unnecessary lights during peak migration weeks, and he has convinced several neighbors to do the same small thing.', 'He now reduces unnecessary light during locally identified migration periods while keeping lighting needed for safety, accessibility, and legal requirements.'],
    ['Now, every autumn evening, I climb up to that same rooftop, watch quietly, and switch off my apartment lights before the birds pass overhead.', 'Now I observe from an authorized rooftop with safe access and barriers, follow local guidance, and reduce unnecessary indoor light without claiming that my action alone determines a bird’s journey.'],
  ] }),

  R('05', 'revise; remove unsupported flood-cause speculation and add evacuation, contaminated-water, electrical, structural, cleanup, mold, and vulnerable-person safeguards', [
    q('Why does Tomo avoid assigning the flood to the drainage project?', 'Causation requires rainfall, river, land-use, drainage, and engineering evidence', 'Construction can never affect water', 'Nabila dislikes reports', 'The river has no upstream area', 'A resident’s impression is not a completed investigation.'),
    q('What should happen before entering a flooded building?', 'Authorities or qualified professionals should confirm relevant electrical, structural, and contamination safety', 'Furniture should be moved immediately', 'Windows must stay closed for a month', 'Volunteers should enter alone', 'Cleanup begins after immediate hazards are assessed.'),
    q('Why is carrying the neighbor upstairs not celebrated as the universal plan?', 'Evacuation should follow safe assistance appropriate to the person and conditions', 'Older people cannot use stairs', 'Neighbors should evacuate last', 'Family members need no training', 'A dramatic rescue detail should not become unsafe guidance.'),
    q('What does Nabila need before volunteering?', 'Coordination, protective equipment, and clear safe tasks', 'Only old towels', 'A live electrical connection', 'Permission to inspect mold herself', 'Extra hands help only within a safe response plan.'),
    q('What evidence question remains open?', 'How much each environmental and infrastructure factor contributed', 'Whether water entered the home', 'Whether the warning lasted two hours', 'Whether the family moved upstairs', 'The event is known while causal shares remain uncertain.'),
  ], { replaceText: [
    ['Do you think the new drainage construction upstream contributed to this, or was it simply an unusually heavy storm season?', 'Some neighbors blame the upstream construction. Has an official investigation established what contributed?'],
    ['Probably both, if I\'m being fair. The storm was severe, but the drainage changes likely made the water rise faster than it would have otherwise.', 'Not yet. Rainfall, river conditions, land use, and drainage all need qualified analysis, so I should not assign a cause from what I saw on one street.'],
    ['Me too. My elderly neighbor couldn\'t manage the stairs alone, so my brother carried her up, which honestly felt heroic in the moment.', 'Me too. We followed the evacuation instructions and helped our older neighbor through the safest available assistance for her needs and the conditions.'],
    ['Cleaning mud out of everything, throwing away ruined furniture, and trying to dry the walls before mold becomes an even bigger problem.', 'First we are waiting for electrical, structural, and contamination safety guidance. Cleanup and drying need suitable protective equipment and qualified mold advice when the damage is extensive.'],
    ['Then I\'ll bring gloves and old towels. Despite the damage, at least you and your family are safe, and that matters most.', 'Then I will contact the volunteer coordinator, bring the specified protective equipment, and accept only tasks the response team says are safe.'],
  ] }),

  R('06', 'revise; turn an improvised predawn hike into a prepared outing and keep nature-based comfort separate from medical or psychological treatment claims', [
    q('What safety preparation is added?', 'Route, forecast, fitness, equipment, contacts, turnaround limits, and local guidance', 'Only a brighter camera', 'A promise to reach the ridge', 'Following unknown footprints', 'Predawn hiking requires more than emotional motivation.'),
    q('Why does the narrator avoid calling sunrise a cure?', 'Relief after one experience does not diagnose or treat ongoing exhaustion', 'Sunrise has no emotional value', 'Mountains prevent reflection', 'Friends cannot offer support', 'Comfort and treatment are different claims.'),
    q('What role does the friend play?', 'A prepared companion who offers quiet support without forcing an explanation', 'A medical specialist who diagnoses tiredness', 'A guide who ignores the weather', 'A person who hides the route', 'Support remains helpful without exceeding its role.'),
    q('What does “lighter” mean in context?', 'The narrator gains perspective while the underlying problems still exist', 'Every practical problem disappears', 'The descent requires no effort', 'The job is immediately restored', 'The text explicitly rejects instant resolution.'),
    q('What follow-up would be appropriate for persistent unexplained tiredness?', 'Qualified assessment and continuing support rather than relying only on hikes', 'A more difficult climb alone', 'Ignoring it after sunrise', 'Giving the same advice to everyone', 'A lasting health concern needs appropriate evaluation.'),
  ], { replaceText: [
    ['I hadn\'t planned this hike carefully. I simply needed to leave the city after a year that had drained nearly everything out of me.', 'After a draining year, I wanted to leave the city briefly. Because the hike began before dawn, my experienced friend and I planned the route rather than leaving impulsively.'],
    ['My friend suggested watching the sunrise from a nearby peak, and even though I was exhausted, something in me agreed almost immediately.', 'We checked the forecast and local guidance, considered my fitness and tiredness, packed suitable clothing, lights, water, navigation, and emergency items, and shared our route and return time.'],
    ['We started climbing at three in the morning, using headlamps, stumbling occasionally over roots we couldn\'t see clearly in the dark.', 'We started at three with reliable lights, stayed on the approved route, moved at a safe pace, and kept the agreed turnaround limit.'],
    ['Sometimes healing doesn\'t arrive through answers. Sometimes it simply arrives through light, patiently spreading across a sky you almost didn\'t bother climbing to see.', 'The sunrise gave me comfort and perspective, not a diagnosis or cure. Persistent unexplained tiredness or distress still deserves qualified assessment and continuing support.'],
  ] }),

  R('07', 'revise; replace a questionable owl-feeding claim and ensure wildlife rescue, rehabilitation, release, possession, disease control, and welfare remain with authorized specialists', [
    q('Why can private rescue create harm despite affection?', 'Wild species have specialized welfare, social, diet, disease, and legal needs', 'Wild animals cannot recognize people', 'All homes are too small', 'Kind intentions are illegal', 'Intent does not guarantee suitable care.'),
    q('What should someone do after finding injured wildlife?', 'Keep a safe distance and contact an authorized wildlife service for instructions', 'Feed it household food', 'Post its location and invite visitors', 'Take it home permanently', 'Early specialist guidance protects people and animals.'),
    q('Why is release not always the immediate result?', 'Qualified assessment must consider health, behavior, habitat, law, and survival prospects', 'Sanctuaries never release animals', 'Owners choose by affection', 'Every animal prefers captivity', 'Release is a welfare decision, not merely a slogan.'),
    q('What does the owl example demonstrate?', 'Love did not provide the species-specific development and care the bird needed', 'Owls must be trained as pets', 'Live prey is required in every household', 'Veterinarians oppose rescue', 'The revised example avoids prescribing a feeding method.'),
    q('What is the key distinction at the end?', 'Authorized rehabilitation serves the animal’s welfare, not a person’s wish to possess it', 'Temporary care creates ownership', 'Payment permits wildlife possession', 'Release is always possible within a week', 'Purpose and professional authority separate rehabilitation from pet keeping.'),
  ], { replaceText: [
    ['Certainly. I once treated an owl someone had raised since it was a chick, and despite loving it deeply, the owner hadn\'t realized it needed to hunt live prey to develop properly.', 'I once assessed an owl raised privately from a chick. Despite genuine affection, it had missed species-specific nutrition, social learning, space, and behavior needed for healthy development.'],
    ['In rare situations, perhaps, though even then, most animals experience chronic stress from an environment that isn\'t truly theirs.', 'Private possession may be illegal. Money alone cannot provide authorization or expertise. Licensed specialists assess welfare, disease risk, facilities, and the law.'],
    ['Private possession may be restricted or illegal, and money alone cannot provide authorization or expertise. Licensed specialists must assess welfare, disease risk, facilities, and the law.', 'Private possession may be illegal. Money alone cannot provide authorization or expertise. Licensed specialists assess welfare, disease risk, facilities, and law.'],
    ['As a result, I always encourage people to support proper sanctuaries instead, where trained staff can meet those complex needs appropriately.', 'If someone finds wildlife, keep a safe distance and contact the authorized local wildlife service. Do not feed, handle, transport, or publish a sensitive location unless instructed.'],
    ['Temporary rehabilitation, yes, provided the eventual goal remains release back into the wild, not permanent ownership disguised as rescue.', 'Authorized rehabilitation may be appropriate after qualified assessment. Release is preferred when safe and lawful, but some animals need other welfare decisions based on health, behavior, habitat, and regulation.'],
  ] }),

  R('08', 'retain; strong restoration account that prioritizes diagnosis, community interests, natural regeneration, species fit, maintenance, and honest monitoring', [
    q('What made the original target attractive?', 'A large number looked impressive in campaign publicity', 'It came from tidal measurements', 'Every seedling was already growing', 'Fishers had selected one species', 'The opening contrasts visible scale with appropriate action.'),
    q('Why were fishers and residents included?', 'Restoration could affect access, livelihoods, and local knowledge', 'They owned the nursery catalogue', 'Only residents could measure salt', 'Scientists were unavailable', 'Ecological decisions also affect people.'),
    q('What did natural regeneration require?', 'Protection from unnecessary planting and disturbance', 'Replacement with identical nursery trees', 'Removal as weeds', 'A concrete wall', 'Sometimes recovery needs space rather than more inputs.'),
    q('Why was the final plan smaller?', 'Evidence supported different actions in different sections', 'The team no longer valued mangroves', 'The campaign had no volunteers', 'Every site was privately owned', 'Site variation changed the intervention.'),
    q('What indicates a durable project?', 'Maintenance, community arrangements, survival records, and adaptive decisions', 'A launch photograph alone', 'The number ordered', 'One year without losses', 'Long-term capacity matters more than a planting event.'),
  ]),

  R('09', 'retain; strong field-survey monologue with biosecurity, authorization, non-disturbance, uncertainty, contextual data, and limits of non-detection', [
    q('Why did the team record weather and time?', 'Detection and interpretation depend on survey conditions', 'Frogs require a calendar', 'The road company requested a diary', 'Temperature proves a species identity', 'Context affects what observers can hear and infer.'),
    q('Why was repeated call playback avoided?', 'It could disturb animals and alter the behavior under study', 'Speakers cannot work at night', 'Volunteers preferred silence', 'Recordings are always illegal', 'A survey method can change its subject.'),
    q('What broader evidence did the road assessment need?', 'Habitat, noise, water, movement barriers, and repeated seasonal observations', 'Only the longest species list', 'One volunteer’s memory', 'A photograph from another wetland', 'Impact assessment extends beyond detection.'),
    q('Why did the team stop at the planned time?', 'Fatigue can reduce safety and observation quality', 'Every frog had been counted', 'The road opened at midnight', 'The equipment belonged elsewhere', 'Field discipline includes safe limits.'),
    q('What is the narrator’s changed view of conservation?', 'Restraint and honest uncertainty can be more responsible than dramatic contact', 'Rare photographs are the main evidence', 'Animals should be moved for study', 'Uncertain calls should be ignored', 'The closing reframes careful practice as meaningful action.'),
  ]),

  R('10', 'retain; strong ecotourism dialogue centered on authorization, non-disturbance, honest uncertainty, location sensitivity, accessibility, and no unauthorized handling', [
    q('What does payment not provide?', 'Control over whether a wild turtle appears', 'Access to an authorized guide', 'A scheduled meeting place', 'Safety information', 'Wildlife remains unpredictable.'),
    q('Why can the beach still be educational without a sighting?', 'Tracks, habitat, tides, and threats can be interpreted responsibly', 'Visitors may open nests themselves', 'Photographs can be staged', 'The tour becomes a swimming lesson', 'Learning does not require forcing an encounter.'),
    q('What information should be checked before booking?', 'Authorization, group practice, distance, training, fees, and response rules', 'Only the cheapest ticket', 'Only the camera brand', 'The number of live posts', 'Operator practice matters more than promotional images.'),
    q('Why are accessibility arrangements mentioned?', 'Responsible conservation visits should also plan for visitor safety and access', 'Accessibility allows closer wildlife contact', 'Rules apply only to some guests', 'The beach has no hazards', 'Environmental care and inclusive planning can coexist.'),
    q('What ethical aim guides Laila’s final choice?', 'Learn without transferring the cost of excitement to the animals', 'Guarantee a close photograph', 'Find a nest without a guide', 'Handle a hatchling briefly', 'The conclusion centers animal welfare.'),
  ]),
];
