import { ShadowingTheme } from './shadowingData';

export const DAILY_ISLAMIC_THEMES: ShadowingTheme[] = [
  {
    id: "di_worship_routine",
    title: "Daily Worship & Routine",
    category: "Daily Conversations",
    mainCategory: "Daily Conversations",
    subCategory: "Islamic",
    icon: "fa-pray",
    description: "Everyday conversations related to prayers, wudhu, reciting Quran, and maintaining spiritual habits.",
    tasks: [
      // Easy (5)
      { id: "di_worship_routine_e1", title: "Waking Up for Fajr", category: 'Daily Conversations', difficulty: "Easy", text: "Assalamu'alaikum. It's time for Fajr. Let's wake up and pray.", translation: "Assalamu'alaikum. Sudah waktu Subuh. Ayo bangun dan shalat.", scenario: "Sapaan dan ajakan santai untuk bangun shalat Subuh di rumah." },
      { id: "di_worship_routine_e2", title: "Making Wudhu", category: 'Daily Conversations', difficulty: "Easy", text: "Wait a minute, I need to make Wudhu before we leave the house.", translation: "Tunggu sebentar, saya harus wudhu dulu sebelum kita berangkat.", scenario: "Menyampaikan rutinitas menjaga wudhu sebelum beraktivitas." },
      { id: "di_worship_routine_e3", title: "Reminding the Adhan", category: 'Daily Conversations', difficulty: "Easy", text: "Quiet down for a moment, the Adhan is playing. Let's listen to it.", translation: "Tolong diam sebentar, azan sedang berkumandang. Mari kita dengarkan.", scenario: "Mengingatkan adab untuk mendengarkan dan menjawab azan." },
      { id: "di_worship_routine_e4", title: "Daily Dhikr", category: 'Daily Conversations', difficulty: "Easy", text: "I like to do my morning Dhikr while driving to work. It brings me peace.", translation: "Saya suka berzikir pagi sambil menyetir ke tempat kerja. Itu memberiku ketenangan.", scenario: "Menceritakan kebiasaan zikir pagi dalam perjalanan." },
      { id: "di_worship_routine_e5", title: "Quran Portion", category: 'Daily Conversations', difficulty: "Easy", text: "Have you finished your daily Quran portion today? I'm currently on Surah Al-Kahf.", translation: "Apakah kamu sudah menyelesaikan tilawah harianmu hari ini? Saya sedang di Surah Al-Kahf.", scenario: "Saling mengingatkan tentang target tilawah Al-Quran." },
      // Medium (5)
      { id: "di_worship_routine_m1", title: "Catching the Jamaah", category: 'Daily Conversations', difficulty: "Medium", text: "Hurry up! We don't want to miss the first Rak'ah in congregation.", translation: "Cepatlah! Kita tidak mau ketinggalan rakaat pertama berjamaah.", scenario: "Ajakan bersegera menuju masjid untuk mendapat keutamaan shalat berjamaah." },
      { id: "di_worship_routine_m2", title: "Renewing Intention", category: 'Daily Conversations', difficulty: "Medium", text: "Before we start this project, let's renew our intentions purely for the sake of Allah.", translation: "Sebelum kita memulai proyek ini, mari kita perbarui niat murni karena Allah.", scenario: "Mengingatkan kolega untuk meluruskan niat (Tajdidun Niyah)." },
      { id: "di_worship_routine_m3", title: "Night Prayers", category: 'Daily Conversations', difficulty: "Medium", text: "I've been trying to wake up for Tahajjud recently, but my sleep schedule is a mess.", translation: "Belakangan ini saya mencoba bangun untuk Tahajjud, tapi jadwal tidur saya berantakan.", scenario: "Berbagi kendala dalam menjalankan ibadah sunnah malam." },
      { id: "di_worship_routine_m4", title: "Fasting Monday Thursday", category: 'Daily Conversations', difficulty: "Medium", text: "I'd love to join you for lunch, but I'm actually fasting today. It's Monday.", translation: "Saya ingin sekali ikut makan siang, tapi saya sedang puasa hari ini. Ini hari Senin.", scenario: "Menolak ajakan makan dengan halus karena sedang puasa sunnah." },
      { id: "di_worship_routine_m5", title: "Memorization Review", category: 'Daily Conversations', difficulty: "Medium", text: "Could you listen to me recite? I need to review the Surah I memorized last week.", translation: "Bisa tolong dengarkan bacaanku? Saya perlu muraja'ah surah yang saya hafal minggu lalu.", scenario: "Meminta bantuan teman untuk menyimak hafalan (Muraja'ah)." },
      // Hard (5)
      { id: "di_worship_routine_h1", title: "Combining Prayers", category: 'Daily Conversations', difficulty: "Hard", text: "Since we are traveling a long distance today, we can combine and shorten our prayers.", translation: "Karena kita menempuh jarak jauh hari ini, kita bisa menjamak dan mengqashar shalat kita.", scenario: "Menjelaskan rukhsah (keringanan) dalam safar/perjalanan." },
      { id: "di_worship_routine_h2", title: "Overcoming Futur", category: 'Daily Conversations', difficulty: "Hard", text: "I've been experiencing a dip in my faith lately. Do you have any advice on overcoming it?", translation: "Belakangan ini iman saya sedang turun. Apakah kamu punya nasihat untuk mengatasinya?", scenario: "Meminta nasihat spiritual saat mengalami futur (lemah iman)." },
      { id: "di_worship_routine_h3", title: "Consistency over Quantity", category: 'Daily Conversations', difficulty: "Hard", text: "The Prophet said the most beloved deeds to Allah are those done consistently, even if they are small.", translation: "Nabi bersabda amal yang paling dicintai Allah adalah yang berkesinambungan, meski kecil.", scenario: "Menyampaikan hadis tentang pentingnya istiqamah dalam amal ibadah." },
      { id: "di_worship_routine_h4", title: "Seeking Forgiveness", category: 'Daily Conversations', difficulty: "Hard", text: "No matter how many mistakes you make, never despair of Allah's mercy. Keep repenting.", translation: "Sebanyak apa pun kesalahanmu, jangan pernah putus asa dari rahmat Allah. Teruslah bertaubat.", scenario: "Memberikan motivasi untuk senantiasa melakukan Taubat Nasuha." },
      { id: "di_worship_routine_h5", title: "Guarding the Gaze", category: 'Daily Conversations', difficulty: "Hard", text: "In this era of social media, guarding our gaze and protecting our hearts has become a constant struggle.", translation: "Di era media sosial ini, menjaga pandangan dan melindungi hati telah menjadi perjuangan terus-menerus.", scenario: "Mendiskusikan tantangan menjaga iffah (kesucian diri) di zaman modern." }
    ]
  },
  {
    id: "di_social_manners",
    title: "Social Etiquette & Manners",
    category: "Daily Conversations",
    mainCategory: "Daily Conversations",
    subCategory: "Islamic",
    icon: "fa-users",
    description: "Practical expressions for daily interactions, maintaining Islamic manners (Adab) in society.",
    tasks: [
      // Easy (5)
      { id: "di_social_manners_e1", title: "Greeting Etiquette", category: 'Daily Conversations', difficulty: "Easy", text: "Assalamu'alaikum warahmatullah. How are your parents doing?", translation: "Assalamu'alaikum warahmatullah. Bagaimana kabar orang tuamu?", scenario: "Sapaan standar dengan mendoakan kesehatan keluarga." },
      { id: "di_social_manners_e2", title: "Saying InshaAllah", category: 'Daily Conversations', difficulty: "Easy", text: "I'll send you the document by tomorrow morning, InshaAllah.", translation: "Saya akan mengirim dokumennya besok pagi, InsyaAllah.", scenario: "Mengaitkan janji manusia dengan kehendak Allah." },
      { id: "di_social_manners_e3", title: "Expressing Gratitude", category: 'Daily Conversations', difficulty: "Easy", text: "Jazakallahu khairan for helping me carry these heavy boxes.", translation: "Jazakallahu khairan (Semoga Allah membalasmu dengan kebaikan) karena telah membantuku membawa kotak berat ini.", scenario: "Ucapan terima kasih Islami kepada sesama." },
      { id: "di_social_manners_e4", title: "Sneezing Adab", category: 'Daily Conversations', difficulty: "Easy", text: "Alhamdulillah. Oh, excuse me.", translation: "Alhamdulillah. Oh, permisi.", scenario: "Adab ketika bersin di tempat umum dengan mengucapkan tahmid." },
      { id: "di_social_manners_e5", title: "Replying to Sneeze", category: 'Daily Conversations', difficulty: "Easy", text: "Yarhamukallah. May Allah have mercy on you.", translation: "Yarhamukallah. Semoga Allah merahmatimu.", scenario: "Merespons teman yang mengucapkan Alhamdulillah setelah bersin (Tasymit)." },
      // Medium (5)
      { id: "di_social_manners_m1", title: "Visiting the Sick", category: 'Daily Conversations', difficulty: "Medium", text: "I heard you weren't feeling well. May Allah grant you a speedy recovery, Syafakallah.", translation: "Saya dengar kamu sedang sakit. Semoga Allah memberimu kesembuhan yang cepat, Syafakallah.", scenario: "Mendoakan teman yang sedang sakit (Adab menjenguk)." },
      { id: "di_social_manners_m2", title: "Avoiding Backbiting", category: 'Daily Conversations', difficulty: "Medium", text: "Let's change the topic. We shouldn't be talking about him when he's not here.", translation: "Mari ganti topik. Kita tidak seharusnya membicarakannya saat dia tidak ada.", scenario: "Mencegah perbuatan ghibah di tengah obrolan santai." },
      { id: "di_social_manners_m3", title: "Admitting Fault", category: 'Daily Conversations', difficulty: "Medium", text: "Astaghfirullah, that was completely my fault. Please forgive my negligence.", translation: "Astaghfirullah, itu sepenuhnya kesalahanku. Tolong maafkan kelalaianku.", scenario: "Adab meminta maaf dengan lapang dada tanpa mencari alasan." },
      { id: "di_social_manners_m4", title: "Respecting Elders", category: 'Daily Conversations', difficulty: "Medium", text: "Please, go ahead first. You are older and deserve more respect.", translation: "Silakan, maju duluan. Anda lebih tua dan pantas mendapat penghormatan lebih.", scenario: "Mendahulukan orang yang lebih tua saat mengantre atau masuk ruangan." },
      { id: "di_social_manners_m5", title: "Returning Items", category: 'Daily Conversations', difficulty: "Medium", text: "Thank you for lending me this book. I made sure to return it in good condition.", translation: "Terima kasih sudah meminjamkan buku ini. Saya pastikan mengembalikannya dalam kondisi baik.", scenario: "Adab meminjam dan menjaga amanah barang milik orang lain." },
      // Hard (5)
      { id: "di_social_manners_h1", title: "Comforting the Bereaved", category: 'Daily Conversations', difficulty: "Hard", text: "Inna lillahi wa inna ilayhi raji'un. I am so deeply sorry for your loss; may Allah grant you patience.", translation: "Inna lillahi wa inna ilayhi raji'un. Saya sangat berduka atas kehilanganmu; semoga Allah memberimu kesabaran.", scenario: "Memberikan ucapan takziah/belasungkawa Islami yang mendalam." },
      { id: "di_social_manners_h2", title: "Respectful Disagreement", category: 'Daily Conversations', difficulty: "Hard", text: "I respect your perspective, but from an Islamic standpoint, we are taught to approach this with compassion.", translation: "Saya menghargai sudut pandangmu, tapi dari sisi Islam, kita diajarkan mendekati hal ini dengan kasih sayang.", scenario: "Berbeda pendapat (Ikhtilaf) dengan tetap menjaga ukhuwah dan kesopanan." },
      { id: "di_social_manners_h3", title: "Guarding Secrets", category: 'Daily Conversations', difficulty: "Hard", text: "Whatever you share with me in confidence remains between us. I won't disclose your private matters.", translation: "Apa pun yang kamu ceritakan padaku secara rahasia akan tetap di antara kita. Aku tidak akan membuka urusan pribadimu.", scenario: "Menegaskan komitmen untuk menjaga aib dan rahasia sesama Muslim." },
      { id: "di_social_manners_h4", title: "Giving Honest Advice", category: 'Daily Conversations', difficulty: "Hard", text: "As your brother in Islam, I have to tell you the truth even if it's hard to hear.", translation: "Sebagai saudaramu seiman, aku harus mengatakan yang sebenarnya walau sulit didengar.", scenario: "Memberikan nasihat dengan hikmah meskipun pahit (Amar Ma'ruf)." },
      { id: "di_social_manners_h5", title: "Handling Provocation", category: 'Daily Conversations', difficulty: "Hard", text: "I choose not to respond to insults. The Quran teaches us to reply to ignorance with peace.", translation: "Saya memilih untuk tidak menanggapi hinaan. Al-Quran mengajarkan kita membalas kebodohan dengan salam perdamaian.", scenario: "Adab menghadapi provokasi (Ibadurrahman) tanpa tersulut emosi." }
    ]
  },
  {
    id: "di_halal_lifestyle",
    title: "Halal Lifestyle & Ethics",
    category: "Daily Conversations",
    mainCategory: "Daily Conversations",
    subCategory: "Islamic",
    icon: "fa-leaf",
    description: "Conversations regarding halal food, ethical business, modesty, and Islamic lifestyle choices.",
    tasks: [
      // Easy (5)
      { id: "di_halal_lifestyle_e1", title: "Asking Halal Status", category: 'Daily Conversations', difficulty: "Easy", text: "Excuse me, is the meat served in this restaurant halal-certified?", translation: "Permisi, apakah daging yang disajikan di restoran ini bersertifikat halal?", scenario: "Pertanyaan wajib saat makan di luar untuk memastikan kehalalan." },
      { id: "di_halal_lifestyle_e2", title: "Checking Ingredients", category: 'Daily Conversations', difficulty: "Easy", text: "I need to check the ingredients list to make sure there's no alcohol or gelatin.", translation: "Saya harus mengecek daftar komposisi untuk memastikan tidak ada alkohol atau gelatin.", scenario: "Kebiasaan membaca label makanan di supermarket." },
      { id: "di_halal_lifestyle_e3", title: "Declining Alcohol", category: 'Daily Conversations', difficulty: "Easy", text: "I don't drink alcohol for religious reasons, but I'd love a glass of orange juice.", translation: "Saya tidak minum alkohol karena alasan agama, tapi saya mau segelas jus jeruk.", scenario: "Menolak tawaran minuman keras dengan sopan di acara sosial." },
      { id: "di_halal_lifestyle_e4", title: "Lowering the Gaze", category: 'Daily Conversations', difficulty: "Easy", text: "Let's sit somewhere else. The screen over there is showing inappropriate content.", translation: "Ayo duduk di tempat lain. Layar di sana menampilkan konten yang tidak pantas.", scenario: "Inisiatif menjaga pandangan (Ghadul Basar) di tempat umum." },
      { id: "di_halal_lifestyle_e5", title: "Modest Dressing", category: 'Daily Conversations', difficulty: "Easy", text: "I prefer wearing clothes that are loose-fitting and comfortable.", translation: "Saya lebih suka memakai pakaian yang longgar dan nyaman.", scenario: "Menjelaskan preferensi gaya berpakaian yang menutup aurat." },
      // Medium (5)
      { id: "di_halal_lifestyle_m1", title: "Explaining Hijab", category: 'Daily Conversations', difficulty: "Medium", text: "For me, the hijab is a personal commitment to modesty and a reflection of my faith.", translation: "Bagi saya, hijab adalah komitmen pribadi terhadap kesopanan dan cerminan iman saya.", scenario: "Menjelaskan makna hijab kepada non-Muslim yang bertanya dengan sopan." },
      { id: "di_halal_lifestyle_m2", title: "Business Honesty", category: 'Daily Conversations', difficulty: "Medium", text: "I have to inform you about a minor defect in this product before you buy it.", translation: "Saya harus memberitahu Anda tentang sedikit cacat pada produk ini sebelum Anda membelinya.", scenario: "Kejujuran dalam jual beli, meniru adab berdagang Rasulullah." },
      { id: "di_halal_lifestyle_m3", title: "Avoiding Interest", category: 'Daily Conversations', difficulty: "Medium", text: "I'm looking for an Islamic bank account because I want to avoid dealing with Riba (interest).", translation: "Saya mencari rekening bank syariah karena saya ingin menghindari berurusan dengan Riba (bunga).", scenario: "Diskusi mengenai prinsip keuangan yang bersih dari bunga." },
      { id: "di_halal_lifestyle_m4", title: "Fair Payment", category: 'Daily Conversations', difficulty: "Medium", text: "We must pay our workers their wages before their sweat dries, as the Prophet advised.", translation: "Kita harus membayar upah pekerja kita sebelum keringat mereka kering, seperti anjuran Nabi.", scenario: "Mengingatkan pentingnya etika kerja dan hak pekerja dalam Islam." },
      { id: "di_halal_lifestyle_m5", title: "Ethical Consumption", category: 'Daily Conversations', difficulty: "Medium", text: "I try to boycott brands that are known for unethical practices or supporting oppression.", translation: "Saya berusaha memboikot merek yang dikenal dengan praktik tidak etis atau mendukung penindasan.", scenario: "Mendiskusikan kesadaran konsumsi yang sejalan dengan nilai keadilan Islam." },
      // Hard (5)
      { id: "di_halal_lifestyle_h1", title: "Explaining Halal Slaughter", category: 'Daily Conversations', difficulty: "Hard", text: "Halal slaughter isn't just a ritual; it's designed to minimize the animal's suffering and ensure hygiene.", translation: "Penyembelihan halal bukan sekadar ritual; ia dirancang untuk meminimalkan penderitaan hewan dan memastikan kebersihan.", scenario: "Memberikan edukasi logis tentang hikmah penyembelihan secara Islam." },
      { id: "di_halal_lifestyle_h2", title: "Declining Shaking Hands", category: 'Daily Conversations', difficulty: "Hard", text: "I apologize, but I don't shake hands with the opposite gender due to my religious beliefs.", translation: "Saya minta maaf, tapi saya tidak bersalaman dengan lawan jenis karena keyakinan agama saya.", scenario: "Menolak jabat tangan dengan sopan tanpa menyinggung perasaan di lingkungan profesional." },
      { id: "di_halal_lifestyle_h3", title: "Navigating Mortgages", category: 'Daily Conversations', difficulty: "Hard", text: "Buying a house is challenging for Muslims here since finding a genuinely interest-free mortgage is difficult.", translation: "Membeli rumah adalah tantangan bagi Muslim di sini karena mencari KPR yang benar-benar tanpa bunga sangat sulit.", scenario: "Mengeluhkan tantangan ekonomi umat Islam di negara mayoritas non-Muslim." },
      { id: "di_halal_lifestyle_h4", title: "Workplace Prayer Accommodations", category: 'Daily Conversations', difficulty: "Hard", text: "Could we possibly schedule our afternoon meetings around my prayer times? It would only take ten minutes.", translation: "Bisakah kita menjadwalkan rapat sore kita menyesuaikan waktu shalat saya? Hanya butuh sepuluh menit.", scenario: "Melakukan negosiasi hak beribadah dengan atasan di tempat kerja." },
      { id: "di_halal_lifestyle_h5", title: "Opposing Corruption", category: 'Daily Conversations', difficulty: "Hard", text: "I cannot sign this document. My faith prohibits bribery and deceit under any circumstances.", translation: "Saya tidak bisa menandatangani dokumen ini. Keyakinan saya melarang suap dan penipuan dalam keadaan apa pun.", scenario: "Pendirian tegas menolak korupsi (Risywah) di lingkungan profesional." }
    ]
  },
  {
    id: "di_family_home",
    title: "Family & Home Life",
    category: "Daily Conversations",
    mainCategory: "Daily Conversations",
    subCategory: "Islamic",
    icon: "fa-home",
    description: "Expressions related to Tarbiyah, honoring parents (Birrul Walidain), and maintaining a peaceful Islamic household.",
    tasks: [
      // Easy (5)
      { id: "di_family_home_e1", title: "Greeting Parents", category: 'Daily Conversations', difficulty: "Easy", text: "Assalamu'alaikum, Mom and Dad. How was your day?", translation: "Assalamu'alaikum, Ibu dan Ayah. Bagaimana hari kalian?", scenario: "Sapaan wajib ketika pulang ke rumah kepada orang tua." },
      { id: "di_family_home_e2", title: "Eating Together", category: 'Daily Conversations', difficulty: "Easy", text: "Bismillah. Let's start eating. Remember to use your right hand.", translation: "Bismillah. Ayo mulai makan. Ingat untuk menggunakan tangan kananmu.", scenario: "Mengingatkan adab makan sederhana kepada adik atau anak." },
      { id: "di_family_home_e3", title: "Helping Around", category: 'Daily Conversations', difficulty: "Easy", text: "Mom, sit down and relax. I will wash the dishes for you tonight.", translation: "Ibu, duduk dan bersantailah. Aku yang akan mencuci piring malam ini.", scenario: "Tindakan sederhana Birrul Walidain di rumah." },
      { id: "di_family_home_e4", title: "Leaving Home", category: 'Daily Conversations', difficulty: "Easy", text: "Bismillahi tawakkaltu 'alallah. I'm leaving for school now, please pray for me.", translation: "Bismillahi tawakkaltu 'alallah. Saya berangkat ke sekolah sekarang, tolong doakan saya.", scenario: "Membaca doa keluar rumah dan meminta doa restu." },
      { id: "di_family_home_e5", title: "Sleeping Adab", category: 'Daily Conversations', difficulty: "Easy", text: "Don't forget to dust your bed and recite the 3 Quls before you sleep.", translation: "Jangan lupa mengibaskan tempat tidurmu dan membaca 3 Qul sebelum tidur.", scenario: "Mengingatkan sunnah sebelum tidur kepada anggota keluarga." },
      // Medium (5)
      { id: "di_family_home_m1", title: "Apologizing to Parents", category: 'Daily Conversations', difficulty: "Medium", text: "I'm sorry for raising my voice earlier. I shouldn't have spoken to you that way.", translation: "Maafkan saya karena meninggikan suara tadi. Saya tidak seharusnya berbicara seperti itu pada kalian.", scenario: "Berani meminta maaf saat melanggar adab kepada orang tua." },
      { id: "di_family_home_m2", title: "Teaching Patience", category: 'Daily Conversations', difficulty: "Medium", text: "I know it's frustrating, but we have to teach the kids patience through our own actions.", translation: "Saya tahu ini membuat frustrasi, tapi kita harus mengajarkan kesabaran pada anak-anak melalui tindakan kita sendiri.", scenario: "Diskusi suami istri tentang metode Tarbiyah anak." },
      { id: "di_family_home_m3", title: "Resolving Conflicts", category: 'Daily Conversations', difficulty: "Medium", text: "Let's not go to sleep angry. The Prophet encouraged spouses to make peace quickly.", translation: "Mari kita tidak tidur dalam keadaan marah. Nabi menganjurkan pasangan suami istri untuk cepat berdamai.", scenario: "Menyelesaikan pertengkaran rumah tangga sesuai tuntunan Sunnah." },
      { id: "di_family_home_m4", title: "Screen Time Rules", category: 'Daily Conversations', difficulty: "Medium", text: "We need to limit their screen time and spend more time reading stories of the Prophets together.", translation: "Kita perlu membatasi waktu layar mereka dan menghabiskan lebih banyak waktu membaca kisah para Nabi bersama.", scenario: "Mengatur aktivitas keluarga untuk lebih religius dan bermanfaat." },
      { id: "di_family_home_m5", title: "Family Consultation", category: 'Daily Conversations', difficulty: "Medium", text: "Let's have a family meeting to decide on our vacation plans. Islam teaches us Shura (consultation).", translation: "Mari kita adakan rapat keluarga untuk menentukan rencana liburan kita. Islam mengajarkan kita Musyawarah.", scenario: "Menerapkan sistem musyawarah dalam mengambil keputusan keluarga." },
      // Hard (5)
      { id: "di_family_home_h1", title: "Caring for Elderly", category: 'Daily Conversations', difficulty: "Hard", text: "Taking care of our elderly parents is a privilege and a direct path to Jannah, not a burden.", translation: "Merawat orang tua kita yang sudah lanjut usia adalah sebuah kehormatan dan jalan langsung menuju Surga, bukan beban.", scenario: "Nasihat mendalam tentang merawat orang tua yang sepuh." },
      { id: "di_family_home_h2", title: "Discussing Inheritance", category: 'Daily Conversations', difficulty: "Hard", text: "We must distribute the inheritance strictly according to the Shariah laws to maintain justice among the siblings.", translation: "Kita harus membagikan warisan ini ketat sesuai hukum Syariat untuk menjaga keadilan di antara saudara kandung.", scenario: "Pembicaraan sensitif mengenai keadilan hukum waris Islam (Faraid)." },
      { id: "di_family_home_h3", title: "Answering Tough Questions", category: 'Daily Conversations', difficulty: "Hard", text: "When children ask about Allah, we shouldn't dismiss them; we must answer with simple, age-appropriate logic.", translation: "Saat anak bertanya tentang Allah, kita jangan mengabaikan mereka; kita harus menjawab dengan logika sederhana yang sesuai umurnya.", scenario: "Tantangan Tarbiyah dalam menjawab pertanyaan kritis anak." },
      { id: "di_family_home_h4", title: "Supporting Relatives", category: 'Daily Conversations', difficulty: "Hard", text: "Silaturahim means maintaining ties even with relatives who have cut you off. We should invite them.", translation: "Silaturahim berarti menyambung ikatan bahkan dengan kerabat yang telah memutusnya denganmu. Kita harus mengundang mereka.", scenario: "Prinsip berat namun mulia tentang menyambung tali persaudaraan yang retak." },
      { id: "di_family_home_h5", title: "Spousal Support", category: 'Daily Conversations', difficulty: "Hard", text: "A righteous spouse acts as a garment for the other, covering their flaws and protecting their dignity.", translation: "Pasangan yang saleh bertindak sebagai pakaian bagi yang lain, menutupi kekurangannya dan melindungi martabatnya.", scenario: "Mendiskusikan fungsi perlindungan pernikahan sesuai metafora Al-Quran." }
    ]
  },
  {
    id: "di_community_dawah",
    title: "Community & Dawah",
    category: "Daily Conversations",
    mainCategory: "Daily Conversations",
    subCategory: "Islamic",
    icon: "fa-hands-helping",
    description: "Discussions on volunteering, advising others, attending Halaqah, and engaging with the community.",
    tasks: [
      // Easy (5)
      { id: "di_community_dawah_e1", title: "Inviting to Halaqah", category: 'Daily Conversations', difficulty: "Easy", text: "Are you free this weekend? There's a great lecture about the Seerah at our local mosque.", translation: "Apakah kamu luang akhir pekan ini? Ada kajian bagus tentang Sirah Nabawiyah di masjid kita.", scenario: "Mengajak teman untuk menghadiri majelis ilmu (Halaqah)." },
      { id: "di_community_dawah_e2", title: "Volunteering", category: 'Daily Conversations', difficulty: "Easy", text: "I signed up to volunteer for the community Iftar cleanup tomorrow.", translation: "Saya mendaftar jadi sukarelawan untuk bersih-bersih setelah buka puasa bersama besok.", scenario: "Berpartisipasi aktif dalam kegiatan masjid." },
      { id: "di_community_dawah_e3", title: "Giving Charity", category: 'Daily Conversations', difficulty: "Easy", text: "Let's chip in some money for the orphans' fund. Every little bit counts.", translation: "Ayo kita patungan sedikit uang untuk dana anak yatim. Sekecil apa pun sangat berarti.", scenario: "Mengajak teman untuk bersedekah bersama." },
      { id: "di_community_dawah_e4", title: "Greeting Neighbors", category: 'Daily Conversations', difficulty: "Easy", text: "Good morning! We just moved next door and brought some sweets for you.", translation: "Selamat pagi! Kami baru pindah ke sebelah dan membawakan sedikit manisan untuk Anda.", scenario: "Memuliakan tetangga, yang merupakan anjuran kuat dalam Islam." },
      { id: "di_community_dawah_e5", title: "Checking Up", category: 'Daily Conversations', difficulty: "Easy", text: "I haven't seen brother Ali at Fajr lately. Let's send him a message to see if he's okay.", translation: "Saya tidak melihat saudara Ali di shalat Subuh akhir-akhir ini. Ayo kirim pesan untuk melihat apakah dia baik-baik saja.", scenario: "Perhatian terhadap sesama anggota jamaah masjid." },
      // Medium (5)
      { id: "di_community_dawah_m1", title: "Advising Gently", category: 'Daily Conversations', difficulty: "Medium", text: "Brother, I noticed a small mistake in your Wudhu. Can I show you the correct way?", translation: "Saudaraku, saya melihat sedikit kesalahan dalam wudhumu. Bolehkah saya tunjukkan cara yang benar?", scenario: "Memberikan nasihat/koreksi ibadah dengan sangat lembut dan tidak menggurui." },
      { id: "di_community_dawah_m2", title: "Organizing Events", category: 'Daily Conversations', difficulty: "Medium", text: "We need a team to manage the crowd during Eid prayers to ensure everyone's safety.", translation: "Kita butuh tim untuk mengatur kerumunan selama shalat Ied untuk memastikan keselamatan semua orang.", scenario: "Diskusi kepanitiaan acara hari raya Islam." },
      { id: "di_community_dawah_m3", title: "Dawah to Non-Muslims", category: 'Daily Conversations', difficulty: "Medium", text: "Instead of arguing, we should show them the beauty of Islam through our excellent character.", translation: "Daripada berdebat, kita seharusnya menunjukkan pada mereka keindahan Islam melalui akhlak kita yang luar biasa.", scenario: "Pendekatan dakwah bil hal (dengan perbuatan) kepada non-Muslim." },
      { id: "di_community_dawah_m4", title: "Collecting Donations", category: 'Daily Conversations', difficulty: "Medium", text: "The mosque roof is leaking. We're running a campaign to collect funds for the repairs.", translation: "Atap masjid bocor. Kami sedang menjalankan kampanye untuk mengumpulkan dana perbaikan.", scenario: "Menggalang dana untuk fasilitas ibadah umum." },
      { id: "di_community_dawah_m5", title: "Supporting Reverts", category: 'Daily Conversations', difficulty: "Medium", text: "Being a new Muslim can be lonely. We should invite him to our family dinner.", translation: "Menjadi Mualaf baru bisa sangat sepi. Kita harus mengundangnya ke makan malam keluarga kita.", scenario: "Kepedulian komunitas terhadap saudara baru yang butuh dukungan sosial." },
      // Hard (5)
      { id: "di_community_dawah_h1", title: "Mediator Role", category: 'Daily Conversations', difficulty: "Hard", text: "We need to sit down with both parties and mediate this conflict strictly based on Islamic justice.", translation: "Kita perlu duduk bersama kedua belah pihak dan memediasi konflik ini ketat berdasarkan keadilan Islam.", scenario: "Berperan sebagai pendamai (Islah) dalam perselisihan warga/komunitas." },
      { id: "di_community_dawah_h2", title: "Correcting Innovations", category: 'Daily Conversations', difficulty: "Hard", text: "It's difficult to speak out against common cultural practices that contradict the Sunnah without offending people.", translation: "Sulit untuk angkat bicara menentang praktik budaya umum yang bertentangan dengan Sunnah tanpa menyinggung orang.", scenario: "Tantangan berdakwah meluruskan bid'ah dengan hikmah." },
      { id: "di_community_dawah_h3", title: "Interfaith Dialogue", category: 'Daily Conversations', difficulty: "Hard", text: "During the interfaith panel, we must clearly define Tawheed while maintaining an atmosphere of mutual respect.", translation: "Selama panel lintas agama, kita harus mendefinisikan Tauhid dengan jelas sambil menjaga suasana saling menghormati.", scenario: "Tugas berat menjelaskan akidah di ranah publik/lintas agama." },
      { id: "di_community_dawah_h4", title: "Enjoining Good", category: 'Daily Conversations', difficulty: "Hard", text: "Enjoining good and forbidding evil is an obligation, but it must be done with knowledge and gentleness, not harshness.", translation: "Menyuruh pada kebaikan dan mencegah kemungkaran adalah kewajiban, tapi harus dilakukan dengan ilmu dan kelembutan, bukan kekerasan.", scenario: "Menjelaskan prinsip Amr Ma'ruf Nahi Munkar sesuai manhaj yang benar." },
      { id: "di_community_dawah_h5", title: "Community Defense", category: 'Daily Conversations', difficulty: "Hard", text: "When facing Islamophobia, our community needs to remain united, legally informed, and spiritually resilient.", translation: "Saat menghadapi Islamofobia, komunitas kita harus tetap bersatu, paham hukum, dan tangguh secara spiritual.", scenario: "Diskusi strategis melindungi hak dan martabat umat Islam di tempat minoritas." }
    ]
  }
];
