import { ShadowingTask } from '../../types';
import { ShadowingTheme } from './shadowingData';

export const SLANG_ISLAMIC_THEMES_2: ShadowingTheme[] = [
  {
    id: 'slang_islamic_2',
    title: 'Ramadan & Fasting Vibes',
    category: 'Slang',
    mainCategory: 'Slang',
    subCategory: 'Islamic',
    icon: 'fa-moon',
    description: 'Modern and casual expressions used by young Muslims during the holy month of Ramadan.',
    tasks: [
      { id: 'si2_e1', title: 'Iftar Time', category: 'Slang', difficulty: 'Easy', text: "Are we going to hit that new restaurant for Iftar tonight?", translation: "Apakah kita bakal buka puasa (Iftar) di restoran baru itu malam ini?", scenario: "Bertanya kepada teman tentang rencana buka puasa bersama." },
      { id: 'si2_e2', title: 'Suhoor Struggles', category: 'Slang', difficulty: 'Easy', text: "Waking up for Suhoor is so hard, but my mom always makes sure I eat something.", translation: "Bangun untuk sahur itu susah banget, tapi ibuku selalu mastiin aku makan sesuatu.", scenario: "Menceritakan tantangan bangun pagi untuk sahur." },
      { id: 'si2_e3', title: 'Food Coma', category: 'Slang', difficulty: 'Easy', text: "I ate too much during Iftar, and now I'm in a serious food coma.", translation: "Aku makan terlalu banyak waktu buka, dan sekarang aku kekenyangan parah sampai ngantuk.", scenario: "Mengeluhkan rasa kantuk karena makan berlebihan saat berbuka." },
      { id: 'si2_e4', title: 'Taraweeh Squad', category: 'Slang', difficulty: 'Easy', text: "My Taraweeh squad and I are going to the big mosque downtown tonight.", translation: "Geng tarawihku dan aku bakal pergi ke masjid besar di pusat kota malam ini.", scenario: "Merencanakan shalat tarawih bersama teman-teman." },
      { id: 'si2_e5', title: 'Date Rush', category: 'Slang', difficulty: 'Easy', text: "Make sure you grab the dates before they run out; it's a total date rush over there.", translation: "Pastikan kamu ambil kurmanya sebelum habis; orang-orang pada berebut kurma di sana.", scenario: "Mengingatkan teman untuk mengambil kurma saat takjil dibagikan." },
      { id: 'si2_m1', title: 'Hangry Fasting', category: 'Slang', difficulty: 'Medium', text: "Please excuse my mood today; I'm just feeling a little hangry because of the fast.", translation: "Tolong maklumi suasana hatiku hari ini; aku cuma merasa agak mudah marah karena lapar (hangry) pas puasa.", scenario: "Meminta maaf karena suasana hati memburuk akibat lapar saat berpuasa." },
      { id: 'si2_m2', title: 'Eid Prep', category: 'Slang', difficulty: 'Medium', text: "We need to finish our Eid prep this weekend so we're not stressed out later.", translation: "Kita harus selesaikan persiapan Lebaran akhir pekan ini biar nanti nggak stres.", scenario: "Mengajak keluarga bersiap menyambut Idul Fitri lebih awal." },
      { id: 'si2_m3', title: 'Thirst is Real', category: 'Slang', difficulty: 'Medium', text: "The weather is so hot today, the thirst is absolutely real right now.", translation: "Cuaca panas banget hari ini, rasa hausnya bener-bener kerasa parah sekarang.", scenario: "Mengeluhkan rasa haus yang berat saat berpuasa di cuaca panas." },
      { id: 'si2_m4', title: 'Last Ten Days', category: 'Slang', difficulty: 'Medium', text: "It's the last ten days of Ramadan, so I'm trying to step up my worship game.", translation: "Ini sepuluh hari terakhir Ramadan, jadi aku berusaha ningkatin ibadahku.", scenario: "Membicarakan niat untuk lebih fokus beribadah di akhir Ramadan." },
      { id: 'si2_m5', title: 'Mosque Hopping', category: 'Slang', difficulty: 'Medium', text: "We're planning on doing some mosque hopping to experience different Taraweeh recitations.", translation: "Kami berencana keliling masjid (mosque hopping) buat ngerasain bacaan Tarawih yang beda-beda.", scenario: "Berencana mencoba shalat di berbagai masjid selama bulan puasa." },
      { id: 'si2_h1', title: 'Caffeine Withdrawal', category: 'Slang', difficulty: 'Hard', text: "The caffeine withdrawal is hitting me so hard today, I can barely keep my eyes open.", translation: "Gejala putus kafeinnya kerasa berat banget hari ini, aku hampir nggak bisa melek.", scenario: "Mengeluhkan rasa pusing akibat tidak bisa minum kopi saat puasa." },
      { id: 'si2_h2', title: 'Spiritual Reset', category: 'Slang', difficulty: 'Hard', text: "I treat Ramadan as a complete spiritual reset to fix my bad habits from the rest of the year.", translation: "Aku menganggap Ramadan sebagai momen reset spiritual total untuk memperbaiki kebiasaan burukku selama setahun.", scenario: "Menjelaskan pandangan mendalam tentang fungsi bulan Ramadan." },
      { id: 'si2_h3', title: 'Zakat Flex', category: 'Slang', difficulty: 'Hard', text: "Make sure you calculate your wealth properly; paying Zakat isn't a flex, it's an obligation.", translation: "Pastikan kamu hitung hartamu dengan benar; bayar Zakat itu bukan ajang pamer, itu kewajiban.", scenario: "Mengingatkan teman bahwa sedekah wajib harus ditunaikan tanpa niat pamer." },
      { id: 'si2_h4', title: 'Laylatul Qadr Hunt', category: 'Slang', difficulty: 'Hard', text: "The whole squad is staying up till dawn for the Laylatul Qadr hunt at the Islamic center.", translation: "Satu geng begadang sampai subuh buat ngejar Lailatul Qadar di pusat kajian Islam.", scenario: "Membicarakan semangat teman-teman untuk itikaf bersama." },
      { id: 'si2_h5', title: 'Post-Ramadan Slump', category: 'Slang', difficulty: 'Hard', text: "I always struggle with the post-Ramadan slump when my routine goes back to normal.", translation: "Aku selalu kesulitan ngadepin penurunan semangat ibadah pasca-Ramadan ketika rutinitas kembali normal.", scenario: "Curhat tentang susahnya mempertahankan kebiasaan baik setelah bulan puasa usai." }
    ]
  },
  {
    id: 'slang_islamic_3',
    title: 'Daily Muslim Lifestyle',
    category: 'Slang',
    mainCategory: 'Slang',
    subCategory: 'Islamic',
    icon: 'fa-star-and-crescent',
    description: 'Casual terms and slang used by modern Muslims to describe everyday life, modesty, and community.',
    tasks: [
      { id: 'si3_e1', title: 'Modest Fashion', category: 'Slang', difficulty: 'Easy', text: "I love her style; she really knows how to pull off modest fashion.", translation: "Aku suka gayanya; dia bener-bener tahu gimana caranya tampil modis dengan pakaian tertutup.", scenario: "Memuji gaya berpakaian sopan namun tetap modern dari seorang teman." },
      { id: 'si3_e2', title: 'Salam', category: 'Slang', difficulty: 'Easy', text: "Don't forget to give your uncle my salam when you see him later.", translation: "Jangan lupa sampaikan salamku ke pamanmu pas kamu ketemu dia nanti ya.", scenario: "Menitipkan salam perdamaian khas Islam kepada kerabat." },
      { id: 'si3_e3', title: 'Jummah OOTD', category: 'Slang', difficulty: 'Easy', text: "He always wears his best outfit to the mosque; his Jummah OOTD is always on point.", translation: "Dia selalu pakai baju terbaiknya ke masjid; gaya baju Jumatannya (OOTD) selalu keren.", scenario: "Mengomentari penampilan rapi seseorang saat hendak shalat Jumat." },
      { id: 'si3_e4', title: 'Halal Meat', category: 'Slang', difficulty: 'Easy', text: "We need to check if this butcher shop sells certified halal meat before we buy anything.", translation: "Kita harus ngecek apa toko daging ini jual daging halal bersertifikat sebelum kita beli apa-apa.", scenario: "Mengingatkan untuk memastikan kehalalan makanan sebelum membeli." },
      { id: 'si3_e5', title: 'Dua Request', category: 'Slang', difficulty: 'Easy', text: "I have a big exam tomorrow, so consider this an official dua request from me.", translation: "Besok aku ujian penting, jadi anggap aja ini permintaan doa resmi dari aku ya.", scenario: "Meminta teman-teman mendoakan kelancaran ujian secara kasual." },
      { id: 'si3_m1', title: 'Hijab Struggle', category: 'Slang', difficulty: 'Medium', text: "The wind is so strong today; I'm having a serious hijab struggle right now.", translation: "Anginnya kencang banget hari ini; aku lagi susah payah benerin hijabku nih.", scenario: "Mengeluhkan kerepotan menjaga kerapian hijab saat cuaca berangin." },
      { id: 'si3_m2', title: 'Wudu Friendly', category: 'Slang', difficulty: 'Medium', text: "I only buy makeup that is wudu-friendly so I don't have to remove it constantly.", translation: "Aku cuma beli makeup yang ramah wudu (tembus air) biar nggak usah repot hapus terus.", scenario: "Membahas preferensi kosmetik yang memudahkan ibadah shalat." },
      { id: 'si3_m3', title: 'Ummah Vibes', category: 'Slang', difficulty: 'Medium', text: "Seeing everyone helping each other at the charity event gave me such strong Ummah vibes.", translation: "Melihat semua orang saling bantu di acara amal ngasih aku nuansa persaudaraan umat (Ummah vibes) yang kuat banget.", scenario: "Mengekspresikan kekaguman atas kekompakan komunitas Muslim." },
      { id: 'si3_m4', title: 'InshaAllah Timing', category: 'Slang', difficulty: 'Medium', text: "He said he'd be here at five, but knowing him, it's probably InshaAllah timing.", translation: "Dia bilang bakal ke sini jam lima, tapi tahu dia mah, itu mungkin jam karet (menggunakan InshaAllah sebagai alasan santai).", scenario: "Menyindir teman yang sering terlambat namun menggunakan istilah religius." },
      { id: 'si3_m5', title: 'Halal Check', category: 'Slang', difficulty: 'Medium', text: "Let's do a quick halal check on the ingredients list of these snacks before we eat them.", translation: "Ayo kita periksa halal-haramnya daftar bahan camilan ini cepat-cepat sebelum dimakan.", scenario: "Memastikan komposisi makanan kemasan bebas dari bahan haram." },
      { id: 'si3_h1', title: 'Deen Over Dunya', category: 'Slang', difficulty: 'Hard', text: "She turned down that shady job offer because she always prioritizes Deen over Dunya.", translation: "Dia nolak tawaran kerja mencurigakan itu karena dia selalu memprioritaskan Agama di atas Dunia.", scenario: "Memuji seseorang yang menolak keuntungan materi demi menjaga prinsip agama." },
      { id: 'si3_h2', title: 'Spiritual Glow Up', category: 'Slang', difficulty: 'Hard', text: "Ever since he started attending those lectures, he's had a massive spiritual glow up.", translation: "Semenjak dia mulai ikut kajian-kajian itu, dia ngalamin peningkatan spiritual (glow up) yang luar biasa.", scenario: "Membicarakan perubahan positif teman yang menjadi lebih religius." },
      { id: 'si3_h3', title: 'Gharaad Alert', category: 'Slang', difficulty: 'Hard', text: "The contract terms are way too vague; this is a major Gharaad alert if you ask me.", translation: "Syarat kontraknya terlalu ambigu; ini pertanda kuat adanya ketidakjelasan (Gharar) kalau kata aku.", scenario: "Mewaspadai unsur penipuan/ketidakpastian (gharar) dalam transaksi bisnis." },
      { id: 'si3_h4', title: 'Halal Ratio', category: 'Slang', difficulty: 'Hard', text: "We need to make sure the halal ratio of our investment portfolio strictly meets the sharia board's criteria.", translation: "Kita harus pastikan rasio halal dari portofolio investasi kita benar-benar memenuhi kriteria dewan syariah.", scenario: "Mendiskusikan batas toleransi pendapatan non-halal dalam investasi saham syariah." },
      { id: 'si3_h5', title: 'Sabr Challenge', category: 'Slang', difficulty: 'Hard', text: "Dealing with that incredibly stubborn customer was a true Sabr challenge for me today.", translation: "Nghadapi pelanggan yang luar biasa keras kepala itu bener-bener jadi ujian kesabaran (sabr challenge) buatku hari ini.", scenario: "Menceritakan pengalaman menghadapi cobaan emosi yang menguji kesabaran." }
    ]
  }
];
