import { ShadowingTask } from '../../types';
import { ShadowingTheme } from './shadowingData';

export const IDIOMS_GENERAL_THEMES_2: ShadowingTheme[] = [
  {
    id: 'idioms_general_2',
    title: 'Workplace & Business Idioms',
    category: 'Idioms',
    mainCategory: 'Idioms',
    subCategory: 'General',
    icon: 'fa-briefcase',
    description: 'Learn common idioms used in professional settings, meetings, and business discussions.',
    tasks: [
      { id: 'ig2_e1', title: 'Get Down to Business', category: 'Idioms', difficulty: 'Easy', text: "We have a lot to cover today, so let's get down to business.", translation: "Banyak yang harus kita bahas hari ini, jadi mari kita mulai bekerja.", scenario: "Mengajak rekan kerja untuk mulai fokus pada topik utama rapat." },
      { id: 'ig2_e2', title: 'Learn the Ropes', category: 'Idioms', difficulty: 'Easy', text: "It will take you a few weeks to learn the ropes, but don't worry.", translation: "Butuh beberapa minggu bagimu untuk mempelajari seluk-beluk pekerjaan ini, tapi jangan khawatir.", scenario: "Menenangkan karyawan baru yang sedang masa orientasi." },
      { id: 'ig2_e3', title: 'On the Same Page', category: 'Idioms', difficulty: 'Easy', text: "Before we proceed, I want to make sure everyone is on the same page.", translation: "Sebelum kita lanjut, saya ingin memastikan semua orang sepemahaman.", scenario: "Memastikan kesepakatan visi dengan tim sebelum memulai proyek." },
      { id: 'ig2_e4', title: 'By the Book', category: 'Idioms', difficulty: 'Easy', text: "Our manager is very strict; she does everything strictly by the book.", translation: "Manajer kita sangat ketat; dia melakukan segalanya persis sesuai aturan.", scenario: "Mendeskripsikan atasan yang sangat patuh pada standar operasional (SOP)." },
      { id: 'ig2_e5', title: 'Call the Shots', category: 'Idioms', difficulty: 'Easy', text: "As the project leader, you are the one who gets to call the shots.", translation: "Sebagai pemimpin proyek, kamulah yang berhak mengambil keputusan.", scenario: "Memberikan wewenang kepada seseorang untuk mengambil kendali." },
      { id: 'ig2_m1', title: 'Think Outside the Box', category: 'Idioms', difficulty: 'Medium', text: "We need a creative solution to this problem; try to think outside the box.", translation: "Kita butuh solusi kreatif untuk masalah ini; cobalah berpikir di luar kebiasaan.", scenario: "Meminta tim untuk memberikan ide yang inovatif dan tidak konvensional." },
      { id: 'ig2_m2', title: 'Get the Ball Rolling', category: 'Idioms', difficulty: 'Medium', text: "Let's organize a quick brainstorming session just to get the ball rolling.", translation: "Mari adakan sesi curah pendapat singkat sekadar untuk memulai prosesnya.", scenario: "Menginisiasi langkah pertama dalam sebuah proyek agar terus berjalan." },
      { id: 'ig2_m3', title: 'Touch Base', category: 'Idioms', difficulty: 'Medium', text: "I'll touch base with you next Monday to see how the campaign is progressing.", translation: "Saya akan menghubungi Anda Senin depan untuk melihat bagaimana perkembangan kampanye ini.", scenario: "Menjadwalkan komunikasi singkat untuk memantau progres kerja." },
      { id: 'ig2_m4', title: 'Bring to the Table', category: 'Idioms', difficulty: 'Medium', text: "What unique skills do you bring to the table for this specific role?", translation: "Keahlian unik apa yang bisa Anda tawarkan untuk peran spesifik ini?", scenario: "Pertanyaan wawancara tentang kontribusi pelamar bagi perusahaan." },
      { id: 'ig2_m5', title: 'Up in the Air', category: 'Idioms', difficulty: 'Medium', text: "The new marketing strategy is still up in the air pending final approval.", translation: "Strategi pemasaran yang baru masih belum pasti, menunggu persetujuan akhir.", scenario: "Menjelaskan status proyek yang masih menggantung atau belum diputuskan." },
      { id: 'ig2_h1', title: 'Cut to the Chase', category: 'Idioms', difficulty: 'Hard', text: "We only have ten minutes left, so let's cut to the chase and discuss the budget.", translation: "Waktu kita sisa sepuluh menit, jadi mari langsung ke intinya dan bahas anggarannya.", scenario: "Meminta pembicara untuk melewati basa-basi dan langsung ke pokok permasalahan." },
      { id: 'ig2_h2', title: 'A Long Shot', category: 'Idioms', difficulty: 'Hard', text: "Getting the CEO to agree to this proposal is a long shot, but it's worth trying.", translation: "Membuat CEO setuju dengan proposal ini adalah peluang yang kecil, tapi patut dicoba.", scenario: "Membahas rencana yang berisiko tinggi namun memiliki potensi hasil besar." },
      { id: 'ig2_h3', title: 'Back to the Drawing Board', category: 'Idioms', difficulty: 'Hard', text: "Since the prototype completely failed the safety test, we have to go back to the drawing board.", translation: "Karena prototipe itu benar-benar gagal dalam uji keselamatan, kita harus mengulang rencana dari awal.", scenario: "Menerima kegagalan proyek dan memutuskan untuk merancang ulang." },
      { id: 'ig2_h4', title: 'Red Tape', category: 'Idioms', difficulty: 'Hard', text: "Starting a business here can be exhausting because you have to deal with so much government red tape.", translation: "Memulai bisnis di sini bisa sangat melelahkan karena Anda harus berurusan dengan begitu banyak birokrasi yang rumit.", scenario: "Mengeluhkan prosedur administratif yang terlalu kaku dan berbelit-belit." },
      { id: 'ig2_h5', title: 'Ahead of the Curve', category: 'Idioms', difficulty: 'Hard', text: "By investing heavily in renewable energy early on, the company managed to stay ahead of the curve.", translation: "Dengan berinvestasi besar pada energi terbarukan sejak awal, perusahaan itu berhasil tetap selangkah lebih maju.", scenario: "Memuji strategi perusahaan yang selalu inovatif mendahului kompetitor." }
    ]
  },
  {
    id: 'idioms_general_3',
    title: 'Education & Learning Idioms',
    category: 'Idioms',
    mainCategory: 'Idioms',
    subCategory: 'General',
    icon: 'fa-graduation-cap',
    description: 'Idioms frequently used when talking about school, studying, and gaining knowledge.',
    tasks: [
      { id: 'ig3_e1', title: 'Hit the Books', category: 'Idioms', difficulty: 'Easy', text: "I can't hang out tonight; I have a major exam tomorrow and I need to hit the books.", translation: "Saya nggak bisa main malam ini; besok ada ujian penting dan saya harus belajar keras.", scenario: "Menolak ajakan bermain karena harus fokus belajar." },
      { id: 'ig3_e2', title: 'Pass with Flying Colors', category: 'Idioms', difficulty: 'Easy', text: "She studied every single day, so it's no surprise she passed the test with flying colors.", translation: "Dia belajar setiap hari, jadi nggak heran dia lulus ujian dengan nilai sangat memuaskan.", scenario: "Memuji teman yang lulus ujian dengan nilai yang nyaris sempurna." },
      { id: 'ig3_e3', title: 'Learn by Heart', category: 'Idioms', difficulty: 'Easy', text: "We have to learn this entire poem by heart for tomorrow's literature class.", translation: "Kita harus menghafal seluruh puisi ini di luar kepala untuk kelas sastra besok.", scenario: "Mengingatkan teman sekelas tentang tugas hafalan." },
      { id: 'ig3_e4', title: 'Brainstorm', category: 'Idioms', difficulty: 'Easy', text: "Let's sit down and brainstorm some ideas for our science project.", translation: "Ayo duduk dan cari ide bareng untuk proyek sains kita.", scenario: "Mengajak kelompok kerja untuk mendiskusikan ide." },
      { id: 'ig3_e5', title: 'Drop Out', category: 'Idioms', difficulty: 'Easy', text: "He decided to drop out of college to start his own software company.", translation: "Dia memutuskan berhenti kuliah untuk mendirikan perusahaan perangkat lunaknya sendiri.", scenario: "Menceritakan seseorang yang keluar dari institusi pendidikan sebelum lulus." },
      { id: 'ig3_m1', title: 'Teacher\'s Pet', category: 'Idioms', difficulty: 'Medium', text: "Everyone thinks he's the teacher's pet because he always sits in the front row and volunteers.", translation: "Semua orang mengira dia anak emas guru karena dia selalu duduk di barisan depan dan menawarkan diri.", scenario: "Membicarakan murid yang sangat disukai guru karena sikapnya." },
      { id: 'ig3_m2', title: 'Cram for a Test', category: 'Idioms', difficulty: 'Medium', text: "I stayed up until 3 AM cramming for the history test, and now I'm exhausted.", translation: "Saya begadang sampai jam 3 pagi mengebut belajar (SKS) untuk ujian sejarah, dan sekarang saya kelelahan.", scenario: "Menceritakan pengalaman belajar dengan sistem kebut semalam." },
      { id: 'ig3_m3', title: 'Know the Ropes', category: 'Idioms', difficulty: 'Medium', text: "Ask Maria if you need help with the lab equipment; she really knows the ropes around here.", translation: "Tanya Maria kalau kamu butuh bantuan dengan alat lab; dia sangat paham seluk-beluk di sini.", scenario: "Merekomendasikan senior yang sudah sangat berpengalaman di lab." },
      { id: 'ig3_m4', title: 'Copycat', category: 'Idioms', difficulty: 'Medium', text: "He was accused of being a copycat when his essay looked exactly like mine.", translation: "Dia dituduh sebagai penjiplak saat esainya terlihat persis seperti milik saya.", scenario: "Membahas kasus plagiarisme di sekolah." },
      { id: 'ig3_m5', title: 'Cover a Lot of Ground', category: 'Idioms', difficulty: 'Medium', text: "We have to cover a lot of ground in today's lecture, so please pay close attention.", translation: "Kita harus membahas banyak materi di kuliah hari ini, jadi tolong perhatikan baik-baik.", scenario: "Dosen menginformasikan bahwa materi hari ini sangat padat." },
      { id: 'ig3_h1', title: 'Rack One\'s Brain', category: 'Idioms', difficulty: 'Hard', text: "I've been racking my brain all morning, but I still can't remember the name of that author.", translation: "Saya sudah memeras otak sepanjang pagi, tapi saya tetap tidak ingat nama penulis itu.", scenario: "Berusaha sangat keras untuk mengingat informasi akademis." },
      { id: 'ig3_h2', title: 'Draw a Blank', category: 'Idioms', difficulty: 'Hard', text: "When the professor asked me that question during the presentation, I completely drew a blank.", translation: "Saat profesor menanyakan pertanyaan itu saat presentasi, pikiran saya mendadak kosong sama sekali.", scenario: "Menceritakan momen saat tiba-tiba lupa jawaban di tengah presentasi." },
      { id: 'ig3_h3', title: 'Put Your Thinking Cap On', category: 'Idioms', difficulty: 'Hard', text: "This math puzzle is quite tricky, so you really need to put your thinking cap on to solve it.", translation: "Teka-teki matematika ini cukup menjebak, jadi kamu benar-benar harus berpikir keras untuk memecahkannya.", scenario: "Menyemangati siswa untuk berpikir serius menyelesaikan soal." },
      { id: 'ig3_h4', title: 'School of Hard Knocks', category: 'Idioms', difficulty: 'Hard', text: "He never went to university; everything he knows about business he learned in the school of hard knocks.", translation: "Dia tidak pernah kuliah; semua yang dia tahu tentang bisnis dipelajarinya dari pengalaman hidup yang keras.", scenario: "Memuji seseorang yang sukses bukan dari pendidikan formal, tapi dari pengalaman." },
      { id: 'ig3_h5', title: 'Make the Grade', category: 'Idioms', difficulty: 'Hard', text: "Unfortunately, his final project just didn't make the grade, so he'll have to retake the course next semester.", translation: "Sayangnya, proyek akhirnya tidak memenuhi standar nilai, jadi dia harus mengulang kelas ini semester depan.", scenario: "Menjelaskan situasi ketika seorang mahasiswa gagal memenuhi standar kelulusan." }
    ]
  }
];
