import { ShadowingTask } from '../../types';
import { ShadowingTheme } from './shadowingData';

export const SLANG_GENERAL_THEMES_2: ShadowingTheme[] = [
  {
    id: 'slang_general_2',
    title: 'University & Campus Life',
    category: 'Slang',
    mainCategory: 'Slang',
    subCategory: 'General',
    icon: 'fa-university',
    description: 'Casual terms frequently used by students around campus, studying, and college life.',
    tasks: [
      { id: 'sg2_e1', title: 'All-Nighter', category: 'Slang', difficulty: 'Easy', text: "I had to pull an all-nighter just to finish my final paper.", translation: "Saya harus begadang semalaman cuma buat nyelesain makalah akhirku.", scenario: "Menceritakan kelelahan setelah tidak tidur demi tugas kuliah." },
      { id: 'sg2_e2', title: 'Flunk', category: 'Slang', difficulty: 'Easy', text: "I totally flunked that calculus exam; I didn't know half the answers.", translation: "Saya bener-bener gagal total di ujian kalkulus itu; saya nggak tahu separuh jawabannya.", scenario: "Mengeluh kepada teman setelah mengerjakan ujian yang sangat sulit." },
      { id: 'sg2_e3', title: 'Ace', category: 'Slang', difficulty: 'Easy', text: "Don't worry, you've studied hard, you'll definitely ace the test tomorrow.", translation: "Nggak usah khawatir, kamu udah belajar giat, kamu pasti dapet nilai sempurna besok.", scenario: "Menyemangati teman yang sedang gugup sebelum ujian." },
      { id: 'sg2_e4', title: 'Skip Class', category: 'Slang', difficulty: 'Easy', text: "Are you really going to skip class just to play video games?", translation: "Kamu beneran mau bolos kelas cuma buat main video game?", scenario: "Menegur teman yang ingin bolos kuliah karena alasan remeh." },
      { id: 'sg2_e5', title: 'Freshman 15', category: 'Slang', difficulty: 'Easy', text: "I need to hit the gym before the Freshman 15 catches up to me.", translation: "Saya harus mulai nge-gym sebelum kena 'Freshman 15' (naik berat badan di tahun pertama kuliah).", scenario: "Membicarakan mitos kenaikan berat badan mahasiswa baru." },
      { id: 'sg2_m1', title: 'Syllabus Week', category: 'Slang', difficulty: 'Medium', text: "It's just syllabus week, so the professors aren't giving out any real homework yet.", translation: "Ini kan baru minggu perkenalan silabus, jadi dosen belum ngasih PR beneran.", scenario: "Menjelaskan minggu pertama kuliah yang biasanya masih santai." },
      { id: 'sg2_m2', title: 'Pop Quiz', category: 'Slang', difficulty: 'Medium', text: "The professor gave us a pop quiz today and literally nobody was prepared.", translation: "Dosen ngasih kita kuis dadakan hari ini dan bener-bener nggak ada yang siap.", scenario: "Curhat tentang kuis mendadak yang membuat satu kelas panik." },
      { id: 'sg2_m3', title: 'Cramming', category: 'Slang', difficulty: 'Medium', text: "Cramming the night before an exam is the worst way to study, but we all do it.", translation: "Belajar sistem kebut semalam sebelum ujian itu cara terburuk, tapi kita semua ngelakuinnya.", scenario: "Membahas kebiasaan buruk mahasiswa yang suka menunda belajar." },
      { id: 'sg2_m4', title: 'Group Project Carry', category: 'Slang', difficulty: 'Medium', text: "I ended up having to carry the entire group project because nobody else did their part.", translation: "Akhirnya saya harus ngerjain sendirian seluruh proyek kelompok karena yang lain nggak ngerjain bagian mereka.", scenario: "Mengeluhkan anggota kelompok yang malas dan tidak berkontribusi." },
      { id: 'sg2_m5', title: 'Office Hours', category: 'Slang', difficulty: 'Medium', text: "If you don't understand the assignment, you should really go to his office hours.", translation: "Kalau kamu nggak paham tugasnya, kamu bener-bener harus datang ke jam konsultasi dosennya.", scenario: "Menyarankan teman untuk menemui dosen di luar jam kelas." },
      { id: 'sg2_h1', title: 'Slacker', category: 'Slang', difficulty: 'Hard', text: "He's a total slacker; I've never seen him open a book the entire semester.", translation: "Dia tuh pemalas sejati; saya belum pernah lihat dia buka buku sepanjang semester.", scenario: "Membicarakan teman sekelas yang sama sekali tidak peduli pada pendidikannya." },
      { id: 'sg2_h2', title: 'Burnout', category: 'Slang', difficulty: 'Hard', text: "After taking six advanced classes, I'm experiencing severe academic burnout.", translation: "Setelah ngambil enam kelas tingkat lanjut, saya ngalamin kelelahan akademik (burnout) yang parah.", scenario: "Menceritakan tekanan mental yang sangat tinggi karena beban kuliah." },
      { id: 'sg2_h3', title: 'Double Major', category: 'Slang', difficulty: 'Hard', text: "She's trying to double major in engineering and business, which is absolute madness.", translation: "Dia mencoba ambil dua jurusan utama sekaligus di teknik dan bisnis, yang mana itu gila banget.", scenario: "Mengomentari teman yang sangat ambisius mengambil dua gelar sekaligus." },
      { id: 'sg2_h4', title: 'Curve Setter', category: 'Slang', difficulty: 'Hard', text: "Everyone is annoyed at the curve setter because they ruined the grading scale for the rest of us.", translation: "Semua orang kesal sama perusak kurva (peraih nilai tertinggi) karena dia ngerusak standar nilai buat kita semua.", scenario: "Membicarakan mahasiswa genius yang membuat standar kelulusan kelas jadi tinggi." },
      { id: 'sg2_h5', title: 'Alumni Network', category: 'Slang', difficulty: 'Hard', text: "Don't underestimate the power of a good alumni network when you're looking for a job post-graduation.", translation: "Jangan remehkan kekuatan jaringan alumni yang bagus saat kamu cari kerja setelah lulus.", scenario: "Menasihati mahasiswa tingkat akhir tentang pentingnya koneksi senior." }
    ]
  },
  {
    id: 'slang_general_3',
    title: 'Work & Professional Hustle',
    category: 'Slang',
    mainCategory: 'Slang',
    subCategory: 'General',
    icon: 'fa-laptop-code',
    description: 'Modern corporate slang used in offices, startups, and professional networking.',
    tasks: [
      { id: 'sg3_e1', title: 'ASAP', category: 'Slang', difficulty: 'Easy', text: "The boss needs this report on his desk ASAP, so please hurry up.", translation: "Bos butuh laporan ini di mejanya secepat mungkin (ASAP), jadi tolong cepetan.", scenario: "Meminta rekan kerja menyelesaikan tugas dengan sangat mendesak." },
      { id: 'sg3_e2', title: 'CC Me', category: 'Slang', difficulty: 'Easy', text: "When you send that email to the client, make sure to CC me on it.", translation: "Pas kamu kirim email itu ke klien, pastikan buat nge-CC (tembusan) ke aku juga.", scenario: "Mengingatkan kolega agar menyertakan alamat emailnya dalam percakapan." },
      { id: 'sg3_e3', title: 'Circle Back', category: 'Slang', difficulty: 'Easy', text: "We don't have an answer right now, so let's circle back to this next week.", translation: "Kita belum punya jawabannya sekarang, jadi mari kita bahas kembali masalah ini minggu depan.", scenario: "Menunda pembahasan topik yang belum ada solusinya di rapat." },
      { id: 'sg3_e4', title: 'Bandwidth', category: 'Slang', difficulty: 'Easy', text: "I'd love to help with the new project, but I just don't have the bandwidth right now.", translation: "Aku pengen banget bantu proyek baru itu, tapi aku lagi nggak punya kapasitas/waktu (bandwidth) sekarang.", scenario: "Menolak tugas tambahan dengan sopan karena pekerjaan sudah menumpuk." },
      { id: 'sg3_e5', title: 'Touch Base', category: 'Slang', difficulty: 'Easy', text: "Let's touch base tomorrow morning just to make sure everything is ready.", translation: "Ayo kita ngobrol singkat (touch base) besok pagi cuma buat mastiin semuanya udah siap.", scenario: "Menjadwalkan koordinasi singkat sebelum acara penting dimulai." },
      { id: 'sg3_m1', title: 'Deep Dive', category: 'Slang', difficulty: 'Medium', text: "We need to do a deep dive into the analytics to understand why sales dropped.", translation: "Kita harus menganalisis secara mendalam (deep dive) data analitik untuk paham kenapa penjualan turun.", scenario: "Menginstruksikan tim untuk melakukan investigasi menyeluruh pada data." },
      { id: 'sg3_m2', title: 'Ping Me', category: 'Slang', difficulty: 'Medium', text: "If you run into any issues during the setup process, just ping me on Slack.", translation: "Kalau kamu nemu masalah selama proses instalasi, hubungi/chat aku (ping) aja di Slack.", scenario: "Mempersilakan rekan kerja untuk menghubungi via aplikasi chat jika butuh bantuan." },
      { id: 'sg3_m3', title: 'Low-Hanging Fruit', category: 'Slang', difficulty: 'Medium', text: "Let's focus on the low-hanging fruit first to get some quick wins for the team.", translation: "Mari fokus pada target yang paling gampang diraih dulu (low-hanging fruit) biar tim dapet kemenangan instan.", scenario: "Menentukan prioritas pekerjaan pada tugas yang paling mudah diselesaikan." },
      { id: 'sg3_m4', title: 'Action Item', category: 'Slang', difficulty: 'Medium', text: "Before we end the meeting, let's review the action items for everyone.", translation: "Sebelum kita akhiri rapat, mari kita tinjau daftar tugas (action items) buat masing-masing orang.", scenario: "Membacakan kesimpulan dan pembagian tugas di akhir sebuah rapat." },
      { id: 'sg3_m5', title: 'In the Loop', category: 'Slang', difficulty: 'Medium', text: "Please keep me in the loop regarding any updates from the supplier.", translation: "Tolong terus kasih saya informasi terbaru (in the loop) terkait kabar apa pun dari penyuplai.", scenario: "Meminta untuk terus dilibatkan dan diinformasikan dalam perkembangan proyek." },
      { id: 'sg3_h1', title: 'Synergy', category: 'Slang', difficulty: 'Hard', text: "We need to create better synergy between the marketing and product development teams.", translation: "Kita harus menciptakan kerja sama yang lebih baik (synergy) antara tim pemasaran dan pengembangan produk.", scenario: "Mendorong kolaborasi lintas departemen agar bekerja lebih efektif." },
      { id: 'sg3_h2', title: 'Move the Needle', category: 'Slang', difficulty: 'Hard', text: "This new campaign is nice, but I'm not convinced it will actually move the needle.", translation: "Kampanye baru ini bagus, tapi saya nggak yakin ini bener-bener bakal ngasih dampak signifikan (move the needle).", scenario: "Mengkritisi rencana yang dianggap kurang memberikan perubahan besar bagi perusahaan." },
      { id: 'sg3_h3', title: 'Boil the Ocean', category: 'Slang', difficulty: 'Hard', text: "Let's start small with a pilot program; there's no need to boil the ocean right away.", translation: "Mari mulai perlahan dengan program percontohan; nggak perlu langsung ngerjain hal mustahil yang terlalu besar (boil the ocean).", scenario: "Mengingatkan tim agar tidak terlalu berambisi melakukan hal yang tidak realistis di awal." },
      { id: 'sg3_h4', title: 'Onboarding', category: 'Slang', difficulty: 'Hard', text: "The onboarding process for new hires has been completely restructured to be more efficient.", translation: "Proses pengenalan/orientasi (onboarding) untuk karyawan baru telah dirombak total agar lebih efisien.", scenario: "Membahas perbaikan sistem pelatihan untuk pegawai yang baru masuk." },
      { id: 'sg3_h5', title: 'Pivot', category: 'Slang', difficulty: 'Hard', text: "The market changed unexpectedly, forcing the startup to quickly pivot their entire business model.", translation: "Pasar berubah secara tak terduga, memaksa startup itu dengan cepat mengubah haluan (pivot) seluruh model bisnis mereka.", scenario: "Menceritakan perusahaan yang harus beradaptasi dan mengganti strategi utama karena krisis." }
    ]
  }
];
