import { ShadowingTheme } from './shadowingData';

export const DAILY_ISLAMIC_ORIGINAL_THEMES_2: ShadowingTheme[] = [
  {
    id: "isl_mosque",
    title: "Mosque & Community Life",
    category: "Islamic",
    icon: "fa-mosque",
    description: "Phrases for engaging with your local mosque, attending halaqahs, and community service.",
    tasks: [
      // Easy (5)
      { id: "mosque_e1", title: "Finding a Mosque", category: 'Islamic', difficulty: "Easy", text: "Is there a mosque or a prayer room anywhere near the mall?", translation: "Apa ada masjid atau ruang shalat di dekat mall ini?", scenario: "Mencari tempat shalat saat bepergian." },
      { id: "mosque_e2", title: "Jum'ah Parking", category: 'Islamic', difficulty: "Easy", text: "Parking for Friday prayers is always a nightmare. Let's go early.", translation: "Parkir buat shalat Jumat itu selalu susah banget. Ayo berangkat awal.", scenario: "Mengingatkan teman agar datang lebih awal." },
      { id: "mosque_e3", title: "Shoe Rack", category: 'Islamic', difficulty: "Easy", text: "Just leave your shoes on the rack outside before entering the carpet area.", translation: "Taruh aja sepatumu di rak luar sebelum masuk area karpet.", scenario: "Memberi tahu aturan di masjid pada teman." },
      { id: "mosque_e4", title: "Mosque Announcement", category: 'Islamic', difficulty: "Easy", text: "Did you hear the announcement about the community BBQ this weekend?", translation: "Kamu dengar pengumuman soal acara BBQ komunitas akhir pekan ini nggak?", scenario: "Membahas acara masjid." },
      { id: "mosque_e5", title: "Donation Box", category: 'Islamic', difficulty: "Easy", text: "Do you have any small change? I want to put something in the donation box.", translation: "Kamu punya uang receh nggak? Saya mau masukin sesuatu ke kotak amal.", scenario: "Bersedekah di masjid." },
      // Medium (5)
      { id: "mosque_m1", title: "Joining Halaqah", category: 'Islamic', difficulty: "Medium", text: "Are you going to the Tafsir class after Maghrib tonight?", translation: "Kamu mau ikut kajian Tafsir habis Maghrib nanti malam nggak?", scenario: "Mengajak teman ikut kajian rutin." },
      { id: "mosque_m2", title: "Volunteering", category: 'Islamic', difficulty: "Medium", text: "The mosque committee needs volunteers to help clean the carpets on Sunday.", translation: "Takmir masjid butuh relawan buat bantu bersihin karpet hari Minggu.", scenario: "Mengajak kerja bakti di masjid." },
      { id: "mosque_m3", title: "Meeting Imam", category: 'Islamic', difficulty: "Medium", text: "I have a quick meeting with the Imam to ask him a question about Zakat.", translation: "Saya ada janjian singkat dengan Imam buat nanya soal Zakat.", scenario: "Konsultasi agama dengan ustaz." },
      { id: "mosque_m4", title: "Kids at Mosque", category: 'Islamic', difficulty: "Medium", text: "It's okay if the kids are a bit noisy, they need to feel welcome at the mosque.", translation: "Nggak apa-apa kalau anak-anak agak ribut, mereka harus merasa disambut di masjid.", scenario: "Bersikap toleran pada anak-anak di masjid." },
      { id: "mosque_m5", title: "Community Support", category: 'Islamic', difficulty: "Medium", text: "If anyone knows a brother looking for a job, let me know. My company is hiring.", translation: "Kalau ada yang tahu saudara kita yang lagi cari kerja, kasih tahu saya ya. Perusahaan saya lagi buka lowongan.", scenario: "Saling bantu urusan duniawi di komunitas." },
      // Hard (5)
      { id: "mosque_h1", title: "Resolving Disputes", category: 'Islamic', difficulty: "Hard", text: "The community leaders are trying to mediate the dispute between the two families.", translation: "Para tokoh masyarakat sedang mencoba memediasi perselisihan antara dua keluarga itu.", scenario: "Peran masjid sebagai tempat islah (damai)." },
      { id: "mosque_h2", title: "Inclusive Space", category: 'Islamic', difficulty: "Hard", text: "We really need to make the sisters' prayer section larger and more comfortable.", translation: "Kita benar-benar harus bikin area shalat akhwat jadi lebih luas dan nyaman.", scenario: "Mengkritik dan memberi saran perbaikan fasilitas." },
      { id: "mosque_h3", title: "Youth Engagement", category: 'Islamic', difficulty: "Hard", text: "If we don't create programs for the youth, they'll stop coming to the mosque entirely.", translation: "Kalau kita nggak bikin program buat anak muda, mereka bakal berhenti datang ke masjid sama sekali.", scenario: "Tantangan dakwah anak muda." },
      { id: "mosque_h4", title: "Mosque Board", category: 'Islamic', difficulty: "Hard", text: "Running for the mosque board requires a lot of patience because people complain a lot.", translation: "Mencalonkan diri jadi pengurus masjid itu butuh banyak sabar karena orang sering komplain.", scenario: "Realita menjadi pengurus/takmir masjid." },
      { id: "mosque_h5", title: "Building Bridges", category: 'Islamic', difficulty: "Hard", text: "Our mosque is hosting an open house to invite the neighbors and clear up misconceptions.", translation: "Masjid kita ngadain 'open house' buat ngundang warga sekitar dan meluruskan salah paham.", scenario: "Dakwah ke masyarakat umum di sekitar masjid." }
    ]
  },
  {
    id: "isl_sahaba",
    title: "The Companions (Sahaba)",
    category: "Islamic",
    icon: "fa-users",
    description: "Discussing the inspiring lives and sacrifices of the Prophet's companions.",
    tasks: [
      // Easy (5)
      { id: "sahaba_e1", title: "Abu Bakr's Loyalty", category: 'Islamic', difficulty: "Easy", text: "Abu Bakr believed the Prophet instantly, without a single doubt.", translation: "Abu Bakar langsung mempercayai Nabi, tanpa ragu sedikit pun.", scenario: "Membahas keimanan Abu Bakar As-Siddiq." },
      { id: "sahaba_e2", title: "Umar's Justice", category: 'Islamic', difficulty: "Easy", text: "Umar was so strict but he was also incredibly just and fair to everyone.", translation: "Umar itu sangat keras tapi beliau juga luar biasa adil ke semua orang.", scenario: "Mengagumi kepemimpinan Umar bin Khattab." },
      { id: "sahaba_e3", title: "Uthman's Modesty", category: 'Islamic', difficulty: "Easy", text: "Even the angels felt shy around Uthman because he was so modest.", translation: "Bahkan malaikat pun merasa malu di dekat Utsman karena beliau sangat pemalu/sopan.", scenario: "Mengingat sifat malu Utsman bin Affan." },
      { id: "sahaba_e4", title: "Ali's Bravery", category: 'Islamic', difficulty: "Easy", text: "Ali sleeping in the Prophet's bed on the night of migration was so brave.", translation: "Ali yang tidur di kasur Nabi pada malam hijrah itu berani banget.", scenario: "Kisah keberanian Ali bin Abi Thalib." },
      { id: "sahaba_e5", title: "Bilal's Voice", category: 'Islamic', difficulty: "Easy", text: "I can't imagine how beautiful the Adhan must have sounded coming from Bilal.", translation: "Saya nggak bisa ngebayangin seindah apa suara azan dari Bilal dulu.", scenario: "Membayangkan azan pertama Bilal." },
      // Medium (5)
      { id: "sahaba_m1", title: "Khadijah's Support", category: 'Islamic', difficulty: "Medium", text: "Khadijah was the first person to ever accept Islam. Her support was everything.", translation: "Khadijah adalah orang pertama yang menerima Islam. Dukungannya adalah segalanya.", scenario: "Peran sentral Khadijah di awal kenabian." },
      { id: "sahaba_m2", title: "Aisha's Knowledge", category: 'Islamic', difficulty: "Medium", text: "Aisha narrated so many Hadiths. She was a brilliant scholar at such a young age.", translation: "Aisyah meriwayatkan banyak banget Hadis. Beliau adalah ulama cerdas di usia yang sangat muda.", scenario: "Membahas kecerdasan Aisyah r.a." },
      { id: "sahaba_m3", title: "Khalid's Strategy", category: 'Islamic', difficulty: "Medium", text: "Khalid bin Walid was a military genius. He never lost a single battle.", translation: "Khalid bin Walid adalah jenius militer. Beliau tidak pernah kalah dalam satu pertempuran pun.", scenario: "Kekaguman pada taktik perang Pedang Allah." },
      { id: "sahaba_m4", title: "Salman's Idea", category: 'Islamic', difficulty: "Medium", text: "Digging the trench was actually Salman Al-Farsi's idea. The Prophet loved it.", translation: "Menggali parit itu sebenarnya ide Salman Al-Farisi. Nabi sangat menyukainya.", scenario: "Sejarah Perang Khandaq." },
      { id: "sahaba_m5", title: "Abdurrahman's Wealth", category: 'Islamic', difficulty: "Medium", text: "Abdurrahman bin Auf was super rich, but he spent almost all of it for Islam.", translation: "Abdurrahman bin Auf itu super kaya, tapi dia menghabiskan hampir semuanya untuk Islam.", scenario: "Inspirasi pengusaha Muslim yang dermawan." },
      // Hard (5)
      { id: "sahaba_h1", title: "Mus'ab's Sacrifice", category: 'Islamic', difficulty: "Hard", text: "Mus'ab left a life of extreme luxury just to follow the Prophet and died with nothing.", translation: "Mus'ab meninggalkan kehidupan sangat mewah hanya demi ikut Nabi dan wafat tanpa harta.", scenario: "Kisah pengorbanan mengharukan Mus'ab bin Umair." },
      { id: "sahaba_h2", title: "Humanity of Sahaba", category: 'Islamic', difficulty: "Hard", text: "They weren't perfect angels; they made mistakes too, but their repentance was immediate.", translation: "Mereka bukan malaikat sempurna; mereka juga buat salah, tapi taubat mereka sangat cepat.", scenario: "Memahami Sahabat sebagai manusia biasa yang bertakwa." },
      { id: "sahaba_h3", title: "Brotherhood in Madinah", category: 'Islamic', difficulty: "Hard", text: "The way the Ansar shared half their wealth with the Muhajirun is just unprecedented in history.", translation: "Cara kaum Ansar membagi separuh harta mereka dengan kaum Muhajirin itu belum pernah ada dalam sejarah.", scenario: "Solidaritas puncak di Madinah." },
      { id: "sahaba_h4", title: "Standing Firm", category: 'Islamic', difficulty: "Hard", text: "Under unimaginable torture, Bilal just kept repeating 'Ahad, Ahad' (One, One).", translation: "Di bawah siksaan yang tak terbayangkan, Bilal terus saja mengulang 'Ahad, Ahad' (Satu, Satu).", scenario: "Kekuatan akidah di tengah ujian berat." },
      { id: "sahaba_h5", title: "The Righteous Caliphs", category: 'Islamic', difficulty: "Hard", text: "Studying the era of the Rightly Guided Caliphs teaches us the blueprint for a just society.", translation: "Mempelajari era Khulafaur Rasyidin mengajarkan kita cetak biru untuk masyarakat yang adil.", scenario: "Relevansi sejarah untuk sistem politik modern." }
    ]
  },
  {
    id: "isl_art",
    title: "Islamic Art & History",
    category: "Islamic",
    icon: "fa-palette",
    description: "Appreciating calligraphy, architecture, and the rich history of the Islamic world.",
    tasks: [
      // Easy (5)
      { id: "art_e1", title: "Calligraphy Class", category: 'Islamic', difficulty: "Easy", text: "I signed up for an Arabic calligraphy workshop this weekend.", translation: "Saya daftar workshop kaligrafi Arab akhir pekan ini.", scenario: "Mencoba hobi baru bernuansa Islam." },
      { id: "art_e2", title: "Mosque Design", category: 'Islamic', difficulty: "Easy", text: "The dome and the minarets of this mosque look absolutely stunning.", translation: "Kubah dan menara masjid ini kelihatan cantik banget.", scenario: "Memuji desain masjid." },
      { id: "art_e3", title: "Museum Visit", category: 'Islamic', difficulty: "Easy", text: "We saw some beautiful old Quran manuscripts at the museum today.", translation: "Kami lihat beberapa manuskrip Al-Quran kuno yang indah di museum hari ini.", scenario: "Kunjungan ke pameran seni Islam." },
      { id: "art_e4", title: "Geometric Patterns", category: 'Islamic', difficulty: "Easy", text: "I love how Islamic art uses geometric patterns instead of drawing people.", translation: "Saya suka gimana seni Islam pakai pola geometris alih-alih menggambar orang.", scenario: "Kekaguman pada ciri khas seni Islam." },
      { id: "art_e5", title: "Historical Trip", category: 'Islamic', difficulty: "Easy", text: "I really want to visit Andalusia in Spain to see the Islamic architecture there.", translation: "Saya pengen banget ke Andalusia di Spanyol buat lihat arsitektur Islam di sana.", scenario: "Rencana liburan sejarah." },
      // Medium (5)
      { id: "art_m1", title: "The Alhambra", category: 'Islamic', difficulty: "Medium", text: "The details in the Alhambra palace show how advanced their architecture was.", translation: "Detail di istana Alhambra menunjukkan betapa majunya arsitektur mereka dulu.", scenario: "Mendiskusikan kejayaan Islam di Spanyol." },
      { id: "art_m2", title: "Avoiding Pictures", category: 'Islamic', difficulty: "Medium", text: "We avoid hanging pictures with faces in the house, so we use calligraphy art instead.", translation: "Kami menghindari pajang foto berwajah di rumah, jadi kami pakai seni kaligrafi.", scenario: "Menerapkan adab menghias rumah Islami." },
      { id: "art_m3", title: "Ottoman Mosques", category: 'Islamic', difficulty: "Medium", text: "The mosques built by the Ottomans in Turkey are just on another level.", translation: "Masjid-masjid yang dibangun Kesultanan Utsmaniyah di Turki itu benar-benar levelnya beda.", scenario: "Kekaguman pada arsitek Mimar Sinan." },
      { id: "art_m4", title: "Reading History", category: 'Islamic', difficulty: "Medium", text: "If you don't know your history, you won't understand why the Middle East is like this today.", translation: "Kalau kamu nggak tahu sejarahmu, kamu nggak bakal paham kenapa Timur Tengah jadi seperti ini sekarang.", scenario: "Pentingnya belajar sejarah kekhalifahan." },
      { id: "art_m5", title: "Salahuddin's Chivalry", category: 'Islamic', difficulty: "Medium", text: "Even his European enemies respected Salahuddin because he was so honorable in war.", translation: "Bahkan musuh Eropanya menghormati Salahuddin karena beliau sangat terhormat dalam perang.", scenario: "Membahas tokoh pahlawan Islam." },
      // Hard (5)
      { id: "art_h1", title: "Art as Devotion", category: 'Islamic', difficulty: "Hard", text: "For Muslim artists back then, writing the Quran beautifully was an act of worship, not just art.", translation: "Bagi seniman Muslim dulu, menulis Al-Quran dengan indah adalah bentuk ibadah, bukan sekadar seni.", scenario: "Makna filosofis kaligrafi." },
      { id: "art_h2", title: "The Fall of Baghdad", category: 'Islamic', difficulty: "Hard", text: "The Mongols destroying the library in Baghdad was a devastating loss for human knowledge.", translation: "Mongol yang menghancurkan perpustakaan di Baghdad adalah kerugian luar biasa bagi ilmu pengetahuan manusia.", scenario: "Mengenang tragedi runtuhnya Baitul Hikmah." },
      { id: "art_h3", title: "Preserving Heritage", category: 'Islamic', difficulty: "Hard", text: "We need to do a better job of preserving our historical sites before they turn into hotels.", translation: "Kita harus lebih baik dalam menjaga situs sejarah kita sebelum semuanya berubah jadi hotel.", scenario: "Kritik terhadap penghancuran situs bersejarah di tanah suci." },
      { id: "art_h4", title: "Cultural Blending", category: 'Islamic', difficulty: "Hard", text: "You can see how Islamic architecture blended with local cultures in places like China and Mali.", translation: "Kamu bisa lihat gimana arsitektur Islam berpadu dengan budaya lokal di tempat seperti China dan Mali.", scenario: "Bukti universalitas Islam." },
      { id: "art_h5", title: "Learning from the Past", category: 'Islamic', difficulty: "Hard", text: "History isn't just dates; it's learning how past empires fell when they abandoned justice.", translation: "Sejarah bukan cuma soal tanggal; ini soal belajar gimana kerajaan masa lalu runtuh saat mereka meninggalkan keadilan.", scenario: "Mengambil ibrah (pelajaran) dari kejatuhan umat terdahulu." }
    ]
  },
  {
    id: "isl_finance",
    title: "Halal Finance & Business",
    category: "Islamic",
    icon: "fa-coins",
    description: "Navigating modern life while avoiding Riba (interest) and earning Halal income.",
    tasks: [
      // Easy (5)
      { id: "finance_e1", title: "Halal Income", category: 'Islamic', difficulty: "Easy", text: "I turned down the job because the company sells alcohol. I want my income to be halal.", translation: "Saya tolak pekerjaan itu karena perusahaannya jual alkohol. Saya ingin penghasilan saya halal.", scenario: "Menolak tawaran kerja karena prinsip agama." },
      { id: "finance_e2", title: "Paying Zakat", category: 'Islamic', difficulty: "Easy", text: "Don't forget we have to calculate and pay our Zakat before the end of the year.", translation: "Jangan lupa kita harus ngitung dan bayar Zakat kita sebelum akhir tahun.", scenario: "Mengingatkan kewajiban Zakat Maal." },
      { id: "finance_e3", title: "Avoiding Riba", category: 'Islamic', difficulty: "Easy", text: "I'm saving up cash to buy a car because I really want to avoid car loans with interest.", translation: "Saya nabung uang tunai buat beli mobil karena saya benar-benar ingin menghindari kredit mobil berbunga.", scenario: "Prinsip menghindari riba dalam cicilan." },
      { id: "finance_e4", title: "Honest Business", category: 'Islamic', difficulty: "Easy", text: "The Prophet said an honest merchant will be with the prophets on Judgment Day.", translation: "Nabi bersabda pedagang yang jujur akan bersama para nabi di Hari Kiamat.", scenario: "Prinsip kejujuran dalam berdagang." },
      { id: "finance_e5", title: "Charity Habit", category: 'Islamic', difficulty: "Easy", text: "Try to set aside a small percentage of your salary for charity every month.", translation: "Coba sisihkan persentase kecil dari gajimu untuk sedekah setiap bulan.", scenario: "Kebiasaan sedekah rutin." },
      // Medium (5)
      { id: "finance_m1", title: "Halal Mortgage", category: 'Islamic', difficulty: "Medium", text: "Do you know any Islamic banks that offer genuine halal mortgages around here?", translation: "Kamu tahu bank syariah yang nawarin KPR halal sungguhan di sekitar sini nggak?", scenario: "Mencari opsi pembiayaan rumah bebas riba." },
      { id: "finance_m2", title: "Student Loans", category: 'Islamic', difficulty: "Medium", text: "Taking out student loans with interest is a huge dilemma for Muslim students right now.", translation: "Mengambil pinjaman mahasiswa berbunga itu dilema besar buat mahasiswa Muslim sekarang.", scenario: "Tantangan biaya pendidikan bagi Muslim." },
      { id: "finance_m3", title: "Stock Investment", category: 'Islamic', difficulty: "Medium", text: "I use an app that screens my stock portfolio to make sure I only invest in halal companies.", translation: "Saya pakai aplikasi yang menyaring portofolio saham saya untuk memastikan saya cuma investasi di perusahaan halal.", scenario: "Investasi saham syariah." },
      { id: "finance_m4", title: "Paying Debts", category: 'Islamic', difficulty: "Medium", text: "I need to pay off my debts first before I can save up for the Umrah trip.", translation: "Saya harus lunasin utang-utang saya dulu sebelum bisa nabung buat perjalanan Umrah.", scenario: "Prioritas melunasi utang." },
      { id: "finance_m5", title: "Fair Wages", category: 'Islamic', difficulty: "Medium", text: "Paying your employees on time and fairly is an Islamic obligation, not just good business.", translation: "Membayar karyawanmu tepat waktu dan adil itu kewajiban Islam, bukan sekadar bisnis yang bagus.", scenario: "Etika menggaji karyawan (Qabul Amal)." },
      // Hard (5)
      { id: "finance_h1", title: "Credit Card Trap", category: 'Islamic', difficulty: "Hard", text: "I strictly pay off my credit card in full every month so I never get hit with late fees and interest.", translation: "Saya ketat melunasi kartu kredit saya penuh tiap bulan agar tidak pernah kena denda keterlambatan dan bunga.", scenario: "Strategi memakai kartu kredit tanpa kena riba." },
      { id: "finance_h2", title: "Inheritance Law", category: 'Islamic', difficulty: "Hard", text: "Dividing the inheritance strictly by Shariah law caused some tension, but it's the right thing to do.", translation: "Membagi warisan ketat sesuai hukum Syariat menyebabkan sedikit ketegangan, tapi itu hal yang benar untuk dilakukan.", scenario: "Sensitivitas pembagian warisan (Faraid)." },
      { id: "finance_h3", title: "Islamic Banking Critique", category: 'Islamic', difficulty: "Hard", text: "Some people argue that Islamic banks are just doing conventional banking disguised with Arabic terms.", translation: "Sebagian orang berargumen bahwa bank syariah cuma melakukan perbankan konvensional yang disamarkan dengan istilah Arab.", scenario: "Kritis terhadap praktik perbankan syariah." },
      { id: "finance_h4", title: "Cryptocurrency Debate", category: 'Islamic', difficulty: "Hard", text: "Scholars are still debating whether trading cryptocurrencies is considered halal or a form of gambling.", translation: "Para ulama masih berdebat apakah trading mata uang kripto itu dianggap halal atau bentuk perjudian (Gharar).", scenario: "Membahas hukum aset digital modern." },
      { id: "finance_h5", title: "Barakah in Wealth", category: 'Islamic', difficulty: "Hard", text: "A smaller income with Barakah (blessing) goes much further than a huge salary earned through haram means.", translation: "Gaji kecil yang ada Barakah-nya jauh lebih awet daripada gaji besar yang didapat dari jalan haram.", scenario: "Konsep keberkahan dalam rezeki." }
    ]
  },
  {
    id: "isl_dawah",
    title: "Dawah & Sharing Islam",
    category: "Islamic",
    icon: "fa-bullhorn",
    description: "Explaining Islam to non-Muslim friends and correcting misconceptions respectfully.",
    tasks: [
      // Easy (5)
      { id: "dawah_e1", title: "Answering Questions", category: 'Islamic', difficulty: "Easy", text: "My coworker asked why I don't eat pork, so I explained it to him over lunch.", translation: "Teman kerjaku tanya kenapa aku nggak makan babi, jadi aku jelaskan ke dia pas makan siang.", scenario: "Menjawab pertanyaan sederhana dari non-Muslim." },
      { id: "dawah_e2", title: "Giving a Gift", category: 'Islamic', difficulty: "Easy", text: "I gave my neighbor an English translation of the Quran as a gift.", translation: "Saya kasih tetangga saya terjemahan Al-Quran bahasa Inggris sebagai hadiah.", scenario: "Membagikan Al-Quran terjemahan." },
      { id: "dawah_e3", title: "Open Mosque Day", category: 'Islamic', difficulty: "Easy", text: "Our local mosque is having an open day for non-Muslims to come and ask questions.", translation: "Masjid lokal kita ngadain 'open day' buat non-Muslim datang dan bertanya.", scenario: "Mengundang warga ke acara masjid." },
      { id: "dawah_e4", title: "Leading by Example", category: 'Islamic', difficulty: "Easy", text: "The best Dawah is just being a good person and showing excellent manners.", translation: "Dakwah terbaik itu ya dengan menjadi orang baik dan menunjukkan akhlak luar biasa.", scenario: "Prinsip dakwah bil hal (melalui perbuatan)." },
      { id: "dawah_e5", title: "Clarifying Fasting", category: 'Islamic', difficulty: "Easy", text: "No, not even water. That's usually the first thing people ask about fasting.", translation: "Nggak, bahkan air pun nggak boleh. Itu biasanya hal pertama yang orang tanyakan soal puasa.", scenario: "Menjelaskan aturan puasa ke teman kantor." },
      // Medium (5)
      { id: "dawah_m1", title: "Discussing Jesus", category: 'Islamic', difficulty: "Medium", text: "Many Christians are surprised when I tell them how much Muslims love and revere Jesus.", translation: "Banyak orang Kristen kaget saat saya kasih tahu seberapa besar Muslim mencintai dan menghormati Yesus (Nabi Isa).", scenario: "Membangun jembatan dialog lintas agama." },
      { id: "dawah_m2", title: "Hijab Misconception", category: 'Islamic', difficulty: "Medium", text: "I had to explain that wearing the hijab is my own choice and not a sign of oppression.", translation: "Saya harus jelaskan bahwa memakai hijab itu pilihan saya sendiri dan bukan tanda penindasan.", scenario: "Meluruskan stigma tentang jilbab." },
      { id: "dawah_m3", title: "Handling Hate", category: 'Islamic', difficulty: "Medium", text: "When someone makes an Islamophobic comment, getting angry usually just proves their stereotype right.", translation: "Saat ada yang bikin komentar Islamofobia, marah-marah biasanya cuma membenarkan stereotip mereka.", scenario: "Cara elegan merespon kebencian/Islamofobia." },
      { id: "dawah_m4", title: "Inviting to Iftar", category: 'Islamic', difficulty: "Medium", text: "I invited my non-Muslim classmates to Iftar so they could experience the vibe.", translation: "Saya undang teman sekelas yang non-Muslim ke buka puasa biar mereka bisa rasakan suasananya.", scenario: "Menggunakan momen Ramadan untuk dakwah." },
      { id: "dawah_m5", title: "Explaining Tawheed", category: 'Islamic', difficulty: "Medium", text: "It's all about pure monotheism. We believe God has no partners and no son.", translation: "Ini murni soal monoteisme murni. Kami percaya Tuhan tidak punya sekutu dan tidak punya anak.", scenario: "Menjelaskan konsep inti Tauhid." },
      // Hard (5)
      { id: "dawah_h1", title: "Debating Gently", category: 'Islamic', difficulty: "Hard", text: "You can win a debate but lose a heart. We must argue with wisdom and beautiful preaching.", translation: "Kamu bisa menang debat tapi kehilangan hati orangnya. Kita harus berdebat dengan hikmah dan tutur kata yang baik.", scenario: "Mengingatkan adab dalam berdebat agama." },
      { id: "dawah_h2", title: "Supporting Reverts", category: 'Islamic', difficulty: "Hard", text: "When someone converts to Islam, they often lose their family support. The community needs to step in.", translation: "Saat seseorang masuk Islam, mereka sering kehilangan dukungan keluarga. Komunitas harus turun tangan.", scenario: "Tanggung jawab merawat Mualaf." },
      { id: "dawah_h3", title: "Media Stereotypes", category: 'Islamic', difficulty: "Hard", text: "It's exhausting having to constantly apologize for the actions of extremists that have nothing to do with Islam.", translation: "Sangat melelahkan harus terus-menerus minta maaf atas tindakan ekstremis yang sama sekali nggak ada hubungannya dengan Islam.", scenario: "Keluhan Muslim minoritas melawan framing media." },
      { id: "dawah_h4", title: "The Status of Women", category: 'Islamic', difficulty: "Hard", text: "Actually, Islam gave women the right to own property and seek divorce centuries before Europe did.", translation: "Sebenarnya, Islam memberi wanita hak memiliki harta dan meminta cerai berabad-abad sebelum Eropa melakukannya.", scenario: "Menjelaskan sejarah hak-hak perempuan dalam Islam." },
      { id: "dawah_h5", title: "Firm Boundaries", category: 'Islamic', difficulty: "Hard", text: "I respect your beliefs, but please don't disrespect the Prophet in front of me.", translation: "Saya menghormati keyakinanmu, tapi tolong jangan merendahkan Nabi di depan saya.", scenario: "Memberi batasan tegas saat agama dihina." }
    ]
  },
  {
    id: "isl_environment",
    title: "Environment & Nature",
    category: "Islamic",
    icon: "fa-leaf",
    description: "Discussions on eco-friendliness, avoiding waste, and our duty as stewards of Earth.",
    tasks: [
      // Easy (5)
      { id: "environment_e1", title: "Wasting Water", category: 'Islamic', difficulty: "Easy", text: "Don't leave the tap running while you make Wudhu. That's wasting water.", translation: "Jangan biarkan kerannya nyala terus pas kamu wudhu. Itu buang-buang air.", scenario: "Mengingatkan agar hemat air saat wudhu." },
      { id: "environment_e2", title: "Planting Trees", category: 'Islamic', difficulty: "Easy", text: "The Prophet said planting a tree is considered an ongoing charity (Sadaqah Jariyah).", translation: "Nabi bilang menanam pohon itu dianggap sebagai sedekah jariyah.", scenario: "Motivasi menanam pohon/berkebun." },
      { id: "environment_e3", title: "Littering", category: 'Islamic', difficulty: "Easy", text: "Please throw that in the trash. Keeping the environment clean is part of faith.", translation: "Tolong buang itu di tempat sampah. Menjaga kebersihan lingkungan itu sebagian dari iman.", scenario: "Menegur teman yang buang sampah sembarangan." },
      { id: "environment_e4", title: "Food Waste", category: 'Islamic', difficulty: "Easy", text: "Take only what you can eat. Throwing away food is a sin.", translation: "Ambil secukupnya saja. Membuang-buang makanan itu dosa.", scenario: "Peringatan saat mengambil makanan prasmanan." },
      { id: "environment_e5", title: "Enjoying Nature", category: 'Islamic', difficulty: "Easy", text: "Looking at the mountains always makes me say Subhanallah.", translation: "Melihat gunung selalu bikin saya refleks bilang Subhanallah.", scenario: "Mentadabburi ciptaan Allah di alam bebas." },
      // Medium (5)
      { id: "environment_m1", title: "Eco-Friendly Mosque", category: 'Islamic', difficulty: "Medium", text: "Our mosque just installed solar panels to reduce the electricity bill and be more eco-friendly.", translation: "Masjid kita baru pasang panel surya buat ngurangin tagihan listrik dan lebih ramah lingkungan.", scenario: "Inovasi hijau di fasilitas umum umat." },
      { id: "environment_m2", title: "Plastic Waste", category: 'Islamic', difficulty: "Medium", text: "I started bringing my own bag to the grocery store. We use way too much plastic.", translation: "Saya mulai bawa tas sendiri ke swalayan. Kita pakai terlalu banyak plastik.", scenario: "Kesadaran mengurangi sampah plastik." },
      { id: "environment_m3", title: "Animal Rights", category: 'Islamic', difficulty: "Medium", text: "A woman went to hell for starving a cat. Islam takes animal rights very seriously.", translation: "Seorang wanita masuk neraka karena menelantarkan kucing. Islam sangat serius soal hak hewan.", scenario: "Mengingatkan adab pada binatang peliharaan." },
      { id: "environment_m4", title: "Ramadan Waste", category: 'Islamic', difficulty: "Medium", text: "The amount of food wasted during Iftar buffets is honestly heartbreaking.", translation: "Jumlah makanan yang dibuang saat prasmanan buka puasa itu sejujurnya sangat menyedihkan.", scenario: "Kritik terhadap budaya mubazir saat puasa." },
      { id: "environment_m5", title: "Steward of Earth", category: 'Islamic', difficulty: "Medium", text: "Allah made us Khalifah (stewards) of the Earth, which means we have to protect it.", translation: "Allah menjadikan kita Khalifah (pengurus) di bumi, yang berarti kita harus melindunginya.", scenario: "Mengingatkan fungsi manusia memakmurkan bumi." },
      // Hard (5)
      { id: "environment_h1", title: "Overconsumption", category: 'Islamic', difficulty: "Hard", text: "The modern culture of buying things we don't need totally contradicts Islamic moderation.", translation: "Budaya modern membeli barang yang nggak kita butuh itu benar-benar bertentangan dengan kesederhanaan Islam.", scenario: "Mengkritik gaya hidup konsumtif." },
      { id: "environment_h2", title: "Climate Change", category: 'Islamic', difficulty: "Hard", text: "If the ice caps melt and cities flood, the poorest communities will suffer the most, which is an injustice we must fight.", translation: "Kalau es mencair dan kota-kota banjir, komunitas termiskin yang paling menderita, yang mana itu ketidakadilan yang harus kita lawan.", scenario: "Diskusi kepedulian perubahan iklim dari kacamata keadilan." },
      { id: "environment_h3", title: "Green Zakat", category: 'Islamic', difficulty: "Hard", text: "Some charities are now using Zakat money to dig wells and install water purifiers in remote villages.", translation: "Beberapa lembaga amal sekarang pakai uang Zakat buat gali sumur dan pasang penjernih air di desa terpencil.", scenario: "Membahas pemanfaatan dana umat untuk isu krisis air." },
      { id: "environment_h4", title: "Ethical Meat", category: 'Islamic', difficulty: "Hard", text: "I'm trying to eat less meat, and when I do, I make sure the animal was raised ethically, not just slaughtered halal.", translation: "Saya nyoba kurangi makan daging, dan kalau makan, saya pastikan hewannya diternak dengan etis (tayyib), bukan cuma disembelih halal.", scenario: "Konsep Halalan Thayyiban pada industri daging massal." },
      { id: "environment_h5", title: "Balance of Nature", category: 'Islamic', difficulty: "Hard", text: "The Quran talks about the 'Mizan' or balance; human greed is destroying the natural balance Allah created.", translation: "Al-Quran bahas soal 'Mizan' atau keseimbangan; keserakahan manusia sedang menghancurkan keseimbangan alam yang Allah ciptakan.", scenario: "Tafsir ayat keseimbangan alam (ekologi)." }
    ]
  },
  {
    id: "isl_science_legacy",
    title: "Muslim Science Legacy",
    category: "Islamic",
    icon: "fa-microscope",
    description: "Chatting about the historical contributions of Muslims to science and technology.",
    tasks: [
      // Easy (5)
      { id: "science_legacy_e1", title: "Algebra Roots", category: 'Islamic', difficulty: "Easy", text: "I hated Algebra in school, until I found out a Muslim scholar named Al-Khwarizmi invented it.", translation: "Saya benci Aljabar di sekolah, sampai saya tahu ternyata ulama Muslim bernama Al-Khawarizmi yang menemukannya.", scenario: "Candaan ringan tentang penemu matematika." },
      { id: "science_legacy_e2", title: "Coffee Origin", category: 'Islamic', difficulty: "Easy", text: "If scholars in Yemen didn't invent coffee to stay up for night prayers, how would we survive Mondays?", translation: "Kalau ulama di Yaman nggak nemuin kopi buat begadang shalat malam, gimana kita bisa selamat lewat hari Senin?", scenario: "Fakta sejarah yang nyambung ke kehidupan ngantor." },
      { id: "science_legacy_e3", title: "Surgical Tools", category: 'Islamic', difficulty: "Easy", text: "It's crazy that many surgical tools doctors use today were designed by a Muslim surgeon a thousand years ago.", translation: "Gila ya, banyak alat bedah yang dipakai dokter hari ini didesain sama ahli bedah Muslim seribu tahun lalu.", scenario: "Kekaguman pada Ibnu Sina / Al-Zahrawi." },
      { id: "science_legacy_e4", title: "First University", category: 'Islamic', difficulty: "Easy", text: "Did you know the oldest existing university in the world was founded by a Muslim woman in Morocco?", translation: "Tahu nggak universitas tertua di dunia yang masih ada itu didirikan oleh wanita Muslim di Maroko?", scenario: "Membahas Fatima al-Fihri dan pentingnya pendidikan wanita." },
      { id: "science_legacy_e5", title: "Optics", category: 'Islamic', difficulty: "Easy", text: "Without Ibn al-Haytham studying how light works, we wouldn't have cameras today.", translation: "Tanpa Ibnu al-Haytham yang belajar cara kerja cahaya, kita nggak bakal punya kamera hari ini.", scenario: "Menyadari peran penemu kamera (Kamera Obscura)." },
      // Medium (5)
      { id: "science_legacy_m1", title: "House of Wisdom", category: 'Islamic', difficulty: "Medium", text: "Imagine reading books at the House of Wisdom in Baghdad back in the day. Must have been awesome.", translation: "Bayangin baca buku di Baitul Hikmah di Baghdad zaman dulu. Pasti keren banget.", scenario: "Bicara soal masa keemasan Islam." },
      { id: "science_legacy_m2", title: "Medical Canon", category: 'Islamic', difficulty: "Medium", text: "Ibn Sina's medical book was the standard textbook in Europe for hundreds of years. That's insane.", translation: "Buku kedokteran Ibnu Sina jadi buku teks standar di Eropa selama ratusan tahun. Itu gila sih.", scenario: "Mendiskusikan pengaruh kitab Qanun fi At-Tibb." },
      { id: "science_legacy_m3", title: "Aviation Pioneer", category: 'Islamic', difficulty: "Medium", text: "The Wright brothers are famous, but Abbas ibn Firnas tried to fly centuries before them in Spain.", translation: "Wright bersaudara memang terkenal, tapi Abbas bin Firnas mencoba terbang berabad-abad sebelum mereka di Spanyol.", scenario: "Membahas pionir penerbangan pertama." },
      { id: "science_legacy_m4", title: "Hygiene Focus", category: 'Islamic', difficulty: "Medium", text: "While Europe was in the Dark Ages, Muslims were building public baths because cleanliness is half of faith.", translation: "Saat Eropa di Abad Pertengahan, umat Muslim membangun pemandian umum karena kebersihan adalah sebagian iman.", scenario: "Hubungan antara syariat wudhu dan sanitasi publik." },
      { id: "science_legacy_m5", title: "Sociology Father", category: 'Islamic', difficulty: "Medium", text: "I'm reading Ibn Khaldun's Muqaddimah. The guy basically invented sociology and economics.", translation: "Saya lagi baca Muqaddimah Ibnu Khaldun. Orang ini pada dasarnya yang nemuin sosiologi dan ekonomi.", scenario: "Membahas bapak ilmu sosial." },
      // Hard (5)
      { id: "science_legacy_h1", title: "Faith and Science", category: 'Islamic', difficulty: "Hard", text: "Back then, studying science wasn't seen as opposite to religion; it was a way to understand God's creation.", translation: "Zaman dulu, belajar sains nggak dilihat bertentangan dengan agama; itu adalah cara untuk memahami ciptaan Tuhan.", scenario: "Diskusi integrasi ilmu dan agama." },
      { id: "science_legacy_h2", title: "Lost History", category: 'Islamic', difficulty: "Hard", text: "It's sad how our school history books completely skip over the Islamic Golden Age.", translation: "Sedih rasanya gimana buku sejarah sekolah kita benar-benar melompati Masa Keemasan Islam.", scenario: "Mengeluhkan kurikulum sejarah yang Euro-sentris." },
      { id: "science_legacy_h3", title: "Astrolabe Tech", category: 'Islamic', difficulty: "Hard", text: "Muslims perfected the astrolabe not just for navigation, but to accurately determine prayer times and the Qibla.", translation: "Umat Muslim menyempurnakan astrolab bukan cuma buat navigasi, tapi untuk menentukan waktu shalat dan arah kiblat dengan akurat.", scenario: "Dorongan ibadah yang memicu penemuan teknologi." },
      { id: "science_legacy_h4", title: "Intellectual Decline", category: 'Islamic', difficulty: "Hard", text: "Why did the scientific output in the Muslim world decline? Was it politics, or did we lose the passion for knowledge?", translation: "Kenapa hasil karya sains di dunia Muslim menurun? Apa karena politik, atau kita yang hilang hasrat akan ilmu?", scenario: "Diskusi berat tentang kemunduran intelektual umat." },
      { id: "science_legacy_h5", title: "Reviving the Spirit", category: 'Islamic', difficulty: "Hard", text: "We don't need to just brag about the past; we need to revive that spirit of innovation in the modern Ummah.", translation: "Kita nggak perlu cuma pamer masa lalu; kita harus membangkitkan kembali semangat inovasi itu di Umat modern.", scenario: "Kesimpulan motivasi ke depan." }
    ]
  },
  {
    id: "isl_family_first",
    title: "Family & Household",
    category: "Islamic",
    icon: "fa-home",
    description: "Conversations about marriage, raising kids, and treating parents with respect.",
    tasks: [
      // Easy (5)
      { id: "family_first_e1", title: "Greeting Parents", category: 'Islamic', difficulty: "Easy", text: "Always kiss your mother's hand before you leave the house.", translation: "Selalu cium tangan ibumu sebelum kamu keluar rumah.", scenario: "Adab harian pada orang tua." },
      { id: "family_first_e2", title: "Helping at Home", category: 'Islamic', difficulty: "Easy", text: "The Prophet used to mend his own clothes. Helping out at home is Sunnah, guys.", translation: "Nabi dulu biasa menjahit bajunya sendiri. Bantuin kerjaan rumah itu Sunnah lho, teman-teman.", scenario: "Mengingatkan suami/anak laki-laki untuk mandiri." },
      { id: "family_first_e3", title: "Eating Together", category: 'Islamic', difficulty: "Easy", text: "Let's all sit down and eat dinner together. Food eaten together is more blessed.", translation: "Ayo semuanya duduk dan makan malam bareng. Makanan yang dimakan bersama itu lebih berkah.", scenario: "Membangun kehangatan meja makan keluarga." },
      { id: "family_first_e4", title: "Saying I Love You", category: 'Islamic', difficulty: "Easy", text: "Don't be shy to tell your parents you love them. Time is short.", translation: "Jangan malu bilang ke orang tuamu kalau kamu sayang mereka. Waktu itu singkat.", scenario: "Menasihati teman agar mengekspresikan kasih sayang." },
      { id: "family_first_e5", title: "Waking for Fajr", category: 'Islamic', difficulty: "Easy", text: "Can you wake me up for Fajr tomorrow? Splash some water on me if you have to.", translation: "Bisa bangunin aku buat Subuh besok nggak? Cipratin air aja ke aku kalau terpaksa.", scenario: "Saling bantu bangun shalat antar saudara/suami-istri." },
      // Medium (5)
      { id: "family_first_m1", title: "Spouse Support", category: 'Islamic', difficulty: "Medium", text: "Marriage is a partnership. The Quran says spouses are like garments for each other.", translation: "Pernikahan itu kemitraan. Al-Quran bilang pasangan suami istri itu seperti pakaian bagi satu sama lain.", scenario: "Membahas konsep saling melengkapi dan melindungi dalam rumah tangga." },
      { id: "family_first_m2", title: "Screen Time for Kids", category: 'Islamic', difficulty: "Medium", text: "We try to limit the kids' iPad time and make them listen to Quran stories instead.", translation: "Kami nyoba batasi waktu main iPad anak-anak dan nyuruh mereka dengar kisah Quran sebagai gantinya.", scenario: "Aturan parenting digital." },
      { id: "family_first_m3", title: "Patience with Elderly", category: 'Islamic', difficulty: "Medium", text: "Taking care of sick parents is exhausting, but it's a direct ticket to Jannah.", translation: "Merawat orang tua yang sakit itu melelahkan, tapi itu tiket langsung ke Surga.", scenario: "Penyemangat bagi yang merawat orang tua sepuh (Birrul Walidain)." },
      { id: "family_first_m4", title: "Resolving Fights", category: 'Islamic', difficulty: "Medium", text: "Don't go to sleep angry at your husband. Resolve it before the day ends.", translation: "Jangan tidur dalam keadaan marah pada suamimu. Selesaikan sebelum hari berakhir.", scenario: "Nasihat meredam konflik rumah tangga." },
      { id: "family_first_m5", title: "Choosing a Name", category: 'Islamic', difficulty: "Medium", text: "We want to name the baby something meaningful, maybe after a Sahaba.", translation: "Kami mau kasih nama bayi sesuatu yang bermakna, mungkin nama salah satu Sahabat Nabi.", scenario: "Bicara persiapan kelahiran anak." },
      // Hard (5)
      { id: "family_first_h1", title: "Answering Kids' Questions", category: 'Islamic', difficulty: "Hard", text: "When my son asks 'Where is Allah?', I have to answer him carefully using simple logic.", translation: "Saat anak cowokku nanya 'Allah di mana?', aku harus jawab hati-hati pakai logika sederhana.", scenario: "Tantangan menanamkan tauhid pada balita." },
      { id: "family_first_h2", title: "In-Law Boundaries", category: 'Islamic', difficulty: "Hard", text: "It's important to respect your in-laws, but the couple also needs their own private space.", translation: "Penting menghormati mertua, tapi pasangan juga butuh ruang pribadi mereka sendiri.", scenario: "Membahas isu sensitif batasan dengan mertua." },
      { id: "family_first_h3", title: "Divorce Stigma", category: 'Islamic', difficulty: "Hard", text: "We need to stop treating divorced sisters like outcasts in the community.", translation: "Kita harus berhenti memperlakukan janda seperti orang buangan di komunitas.", scenario: "Kritik budaya yang menyudutkan perceraian." },
      { id: "family_first_h4", title: "Balancing Work and Family", category: 'Islamic', difficulty: "Hard", text: "Providing halal food is important, but if you're never home, you're failing as a father.", translation: "Menyediakan makanan halal itu penting, tapi kalau kamu nggak pernah di rumah, kamu gagal sebagai ayah.", scenario: "Peringatan agar tidak gila kerja (workaholic)." },
      { id: "family_first_h5", title: "Toxic Relatives", category: 'Islamic', difficulty: "Hard", text: "Silaturahim is an obligation, but you are allowed to keep a safe distance from toxic relatives to protect your mental health.", translation: "Silaturahim itu wajib, tapi kamu diizinkan menjaga jarak aman dari kerabat yang toxic demi melindungi kesehatan mentalmu.", scenario: "Fiqih menyambung tali silaturahim dengan kerabat yang menyakiti." }
    ]
  }
];
