import { q } from '../helpers.mjs';

export const reviews = [
  {
    id: 'a1-akhlak-01', level: 'A1', scriptDecision: 'keep story; simplify selected abstract words',
    replaceText: [['significant to his family', 'important to his family'], ['anything extraordinary', 'anything special'], ['this quiet, ordinary kind of honesty', 'this simple kind of honesty']],
    tags: { 0: 'reflective', 4: 'tempted', 7: 'determined', 10: 'relieved', 14: 'thoughtful', 15: 'warmly' },
    additions: [
      q('Why did the narrator return to the shop?', 'The money did not belong to her', 'She needed more groceries', 'Pak Hasan called her', 'She had lost her shoes', 'She understood that keeping the extra change would be dishonest.'),
      q('What does “profit” mean in this story?', 'Money the shop earns after its costs', 'Money given by a school', 'Change inside a customer’s bag', 'The price of one coin', 'Pak Hasan needed the shop’s earnings for his family.'),
      q('When was honesty most difficult for the narrator?', 'When nobody was watching', 'When Pak Hasan thanked her', 'When she entered the shop', 'When she bought groceries', 'She could have kept the money without anyone seeing her choice.'),
      q('How did she feel while walking home?', 'Lighter and peaceful', 'Angry and cheated', 'Afraid of the shop', 'Confused about the price', 'Returning the money removed the uncomfortable feeling she had carried.'),
      q('What is the voice memo mainly showing?', 'An honest choice made in private', 'A lesson about grocery prices', 'A plan for school fees', 'A complaint about a long workday', 'The narrator records how honesty mattered when no one checked her.'),
    ],
  },
  {
    id: 'a1-akhlak-02', level: 'A1', scriptDecision: 'keep; clear mentor dialogue with concrete workplace pressure',
    tags: { 0: 'worried', 1: 'calmly', 4: 'tense', 7: 'gently', 14: 'reflective', 19: 'encouraging' },
    additions: [
      q('Why did the customer shout at Reza?', 'A delivery was late', 'Reza closed the shop', 'A product was missing', 'The customer lost a phone', 'The customer was angry about a delivery delay.'),
      q('What does “lost my temper” mean?', 'Became very angry', 'Forgot the delivery time', 'Lost an office object', 'Felt too tired to work', 'Reza means that he nearly reacted with uncontrolled anger.'),
      q('What helps Ibu Sinta stay calm?', 'She remembers the anger is about the problem', 'She leaves every customer', 'She never feels angry', 'She ends the conversation at once', 'She does not treat the customer’s frustration as a personal attack.'),
      q('What should Reza do before his next task?', 'Take a few quiet minutes', 'Call the customer again', 'Work without a break', 'Explain the delay to everyone', 'Ibu Sinta recommends time to breathe and reset.'),
      q('What does the conversation teach about patience?', 'It grows through practice', 'It removes anger immediately', 'It is natural from birth', 'It means accepting rude behavior forever', 'Ibu Sinta says calm reactions are built one difficult moment at a time.'),
    ],
  },
  {
    id: 'a1-akhlak-03', level: 'A1', scriptDecision: 'keep; promotion topic suits adults and the dialogue gives clear context for harder words',
    tags: { 0: 'excited', 1: 'warmly', 7: 'nervous', 12: 'reflective', 18: 'sincerely', 19: 'encouraging' },
    additions: [
      q('Why is Umar nervous about the new role?', 'Some team members have more experience', 'He does not know his job title', 'His sister works on the team', 'The promotion begins tomorrow', 'Leading older or more experienced people feels challenging to him.'),
      q('What does “arrogant” mean in this conversation?', 'Acting as if you know more than others', 'Feeling happy about good news', 'Asking people for advice', 'Working hard for a promotion', 'Laila sounded too sure of herself and did not listen enough.'),
      q('How did Laila improve as a supervisor?', 'She asked more questions', 'She gave more instructions', 'She avoided coworkers', 'She changed her job title', 'She learned to listen instead of speaking all the time.'),
      q('Why does Laila call Umar’s nervousness good?', 'It shows he takes the role seriously', 'It will make him leave the job', 'It proves the team is difficult', 'It means he needs another email', 'His concern shows that he does not think he already knows everything.'),
      q('What should Umar remember after the promotion?', 'The people who helped him', 'Only his new title', 'His old email address', 'The date of every meeting', 'Laila asks him to remain kind and remember other people’s support.'),
    ],
  },
  {
    id: 'a1-akhlak-04', level: 'A1', scriptDecision: 'keep adult conflict; simplify abstract phrases about resentment and forgiveness',
    replaceText: [['resentment', 'anger'], ['not defensive like I had expected it to sound', 'not angry or full of excuses as I had expected'], ['carry this anger forward', 'stay angry every day'], ['with this weight put down instead of carried through another restless night', 'because I have chosen not to carry the anger through another night']],
    tags: { 0: 'tired', 2: 'angry', 6: 'reflective', 8: 'regretfully', 12: 'thoughtful', 15: 'peacefully' },
    additions: [
      q('Why could the narrator not sleep?', 'He kept thinking about Bram’s mistake', 'He had worked all night', 'His phone kept ringing', 'His father was calling him', 'The broken trust and anger stayed in his mind.'),
      q('What does “the damage was already done” mean?', 'The private story had already spread', 'The phone had stopped working', 'Their university had closed', 'Bram had lost his job', 'People already knew information that should have stayed private.'),
      q('Why does the narrator remember his father’s illness?', 'Bram supported him during that time', 'Bram caused the illness', 'The secret was about a doctor', 'His father called that night', 'The memory helps him see Bram as more than one mistake.'),
      q('Does forgiveness mean full trust at once?', 'No, he will be more careful with secrets', 'Yes, nothing needs to change', 'No, the friendship must end', 'Yes, Bram may share more stories', 'He forgives Bram but keeps a sensible boundary.'),
      q('What will the narrator probably do tomorrow?', 'Reply calmly to Bram', 'Send the harsh message', 'Tell the whole friend group', 'Avoid Bram forever', 'He plans to answer after choosing forgiveness.'),
    ],
  },
  {
    id: 'a1-akhlak-05', level: 'A1', scriptDecision: 'keep workplace lesson; simplify two difficult phrases',
    replaceText: [['It damaged my reputation there for months afterward.', 'People at work trusted me less for months afterward.'], ['felt exaggerated', 'felt too strong'], ['some was probably exaggerated', 'some was probably too strong']],
    tags: { 0: 'gently', 1: 'frustrated', 4: 'reflective', 10: 'honestly', 15: 'reassuring', 20: 'encouraging' },
    additions: [
      q('Why did Dimas stay quiet in the meeting?', 'He remembered an earlier angry mistake', 'He agreed with every word', 'He could not hear Pak Joko', 'He wanted to leave his job', 'His past reaction taught him not to argue in front of others.'),
      q('What does “snapped at my supervisor” mean?', 'Spoke suddenly and angrily', 'Asked a careful question', 'Sent a polite message', 'Left work quietly', 'Dimas describes an uncontrolled angry response.'),
      q('Did Dimas agree with all the feedback?', 'No, some parts felt too strong', 'Yes, every part was fair', 'No, he heard none of it', 'Yes, he wrote it himself', 'He accepts some feedback while questioning other parts.'),
      q('Why does Bu Ratna offer to join the later talk?', 'To help Dimas speak calmly', 'To argue with Pak Joko', 'To cancel the next meeting', 'To repeat the criticism publicly', 'Her support can make the private follow-up more constructive.'),
      q('What is the key difference between feeling and action?', 'Anger may stay while behavior remains calm', 'Calm behavior removes every feeling', 'Strong feelings must be spoken at once', 'Anger always proves feedback is wrong', 'The dialogue shows that self-control guides action even before feelings fade.'),
    ],
  },
  {
    id: 'a1-akhlak-06', level: 'A1', scriptDecision: 'replace; previous file mixed three-speaker remnants and wrong pronouns',
    replaceScript: [
      "Mira: [warmly] Welcome back to the show. Tonight Yuni and I are talking about promises at work and in friendship.",
      "Yuni: Thank you, Mira. Promises sound simple, but they are one of the main ways people learn to trust us.",
      "Mira: [curious] Can you give us an example from your work?",
      "Yuni: Last month, I promised a client that a report would be ready on Monday. I had not checked the date with my team first.",
      "Mira: What happened when you checked?",
      "Yuni: [regretfully] We needed two more days. I felt embarrassed because the problem came from my quick promise.",
      "Mira: Did you wait until Monday to tell the client?",
      "Yuni: No. I called on Friday, explained my mistake, and gave a new date that the team could truly meet.",
      "Mira: How did the client respond?",
      "Yuni: She was disappointed, but she thanked me for telling her early. We delivered the report on Wednesday as promised.",
      "Mira: You also mentioned a promise to a friend.",
      "Yuni: [thoughtful] Yes. I forgot that I had promised to help her move. I called, apologized, and helped her unpack the next morning.",
      "Mira: Did the apology repair the friendship?",
      "Yuni: It helped because I did more than say sorry. I gave her my time and did the work I could still do.",
      "Mira: What have these two mistakes taught you?",
      "Yuni: Check before saying yes. If a promise may fail, speak early, tell the truth, and offer a clear repair.",
      "Mira: [warmly] So trust does not require a person to be perfect, but it does require honest action.",
      "Yuni: Exactly. I now promise more slowly and work hard to do what I said."
    ],
    tags: { 0: 'warmly', 2: 'curious', 5: 'regretfully', 11: 'thoughtful', 16: 'warmly' },
    baseQuiz: [
      q('What is the talk-show topic?', 'Keeping promises', 'Finding a new office', 'Planning a holiday', 'Writing a radio advert', 'Mira introduces a discussion about promises in work and friendship.'),
      q('What mistake did Yuni make at work?', 'She promised a date before checking', 'She lost the client’s report', 'She forgot the client’s name', 'She called on the wrong day', 'Yuni gave a Monday date before asking her team.'),
      q('When did Yuni warn the client?', 'On Friday', 'On Monday evening', 'After Wednesday', 'One month later', 'She spoke before the missed deadline became a surprise.'),
      q('How did Yuni repair the promise to her friend?', 'She apologized and helped unpack', 'She sent a short text only', 'She asked another friend to go', 'She avoided the next call', 'Yuni gave an apology and practical help the next morning.'),
      q('What does Yuni do before promising now?', 'She checks what is possible', 'She always says no', 'She waits for a mistake', 'She asks the client to decide', 'She learned to check time and ability before saying yes.'),
    ],
    additions: [
      q('Why was the client disappointed?', 'The report needed two extra days', 'Yuni ended the project', 'The team sent the wrong report', 'The client forgot the date', 'The first promised date could not be met.'),
      q('What does “repair” mean in this conversation?', 'Take action to make a mistake better', 'Fix a broken office machine', 'Write a new report title', 'Move to another house', 'Yuni repairs trust through truth, apology, and useful action.'),
      q('What happened after Yuni gave the new date?', 'The team delivered on Wednesday', 'The client canceled the report', 'The report arrived on Monday', 'The team needed another week', 'Yuni kept the second, carefully checked promise.'),
      q('Why was Yuni’s apology to her friend stronger than words alone?', 'She also gave practical help', 'She called very late', 'She described her work stress', 'She made another quick promise', 'Helping unpack showed that she wanted to correct what she could.'),
      q('What advice would Yuni give before saying yes?', 'Check your time and ability', 'Promise quickly to sound helpful', 'Wait until people complain', 'Hide possible delays', 'Her final lesson is to make careful promises and communicate early.'),
    ],
  },
  {
    id: 'a1-akhlak-07', level: 'A1', scriptDecision: 'keep; simplify one figurative line while retaining the late-night advice format',
    replaceText: [['Our tongues get us into more trouble than almost anything else we do, I honestly think.', 'Our careless words can cause a lot of trouble, I honestly think.']],
    tags: { 0: 'worried', 1: 'calmly', 4: 'frustrated', 8: 'reflective', 12: 'regretfully', 18: 'grateful' },
    additions: [
      q('Why did Dinda want others to know about the mistake?', 'She wanted them to know it was not her fault', 'She wanted Wulan to get promoted', 'She needed help with a phone', 'She planned a team celebration', 'Her frustration made her want to protect her own image.'),
      q('What does “gossip” mean in this situation?', 'Talking about someone’s problem behind them', 'Asking a person for help', 'Correcting a project file', 'Calling an old friend', 'Dinda was sharing Wulan’s mistake with people who could not fix it.'),
      q('Why does Ilham ask Dinda to imagine Wulan nearby?', 'It helps her judge her words', 'It helps Wulan hear the call', 'It makes the project easier', 'It tells her where Wulan works', 'Dinda would speak differently if Wulan could hear her.'),
      q('What should Dinda ask the two coworkers to do?', 'Keep the story from spreading', 'Tell the whole office', 'Speak to the manager first', 'Delete the project', 'A quiet request may limit more harm from her earlier gossip.'),
      q('What is better than discussing Wulan with others?', 'Speaking to Wulan about the solution', 'Waiting for another mistake', 'Calling more friends at night', 'Pretending the project is finished', 'Direct respectful conversation can help repair the work.'),
    ],
  },
  {
    id: 'a1-akhlak-08', level: 'A1', scriptDecision: 'keep; coherent digital-literacy story with simple verification steps',
    tags: { 0: 'concerned', 2: 'thoughtful', 5: 'relieved', 8: 'calmly', 13: 'firmly' },
    additions: [
      q('Why did the message create urgency?', 'It asked people to forward it quickly', 'It offered a shop discount', 'It included a recent news report', 'It named an official worker', 'The wording pushed readers to share before checking.'),
      q('What does “reliable” mean here?', 'Able to be trusted', 'Easy to forward', 'Very popular online', 'Written by a family member', 'Reliable information comes from a source that can be trusted.'),
      q('What did the narrator check after the shop page?', 'A local news website', 'A private family photo', 'The shop’s food prices', 'A friend’s old message', 'He used another source to look for an official warning.'),
      q('Why did the aunt delete her post?', 'The claim was old and false', 'The shop had closed', 'Her phone was full', 'The narrator became angry', 'The checked links showed that the warning was not current or true.'),
      q('What should someone do when a message causes fear?', 'Pause and check its source and date', 'Share it with many people', 'Remove the shop’s name', 'Believe it because it sounds serious', 'Strong emotion is a reason to verify before forwarding.'),
    ],
  },
  {
    id: 'a1-akhlak-09', level: 'A1', scriptDecision: 'keep; concrete honesty story with a realistic result that cannot be fully repaired',
    tags: { 0: 'warmly', 1: 'shocked', 4: 'honestly', 6: 'regretfully', 9: 'thoughtful', 13: 'reflective' },
    additions: [
      q('Why did the narrator first think about hiding the accident?', 'Nobody else was in the kitchen', 'The cup belonged to him', 'Sinta had many blue cups', 'The floor was already clean', 'He thought he could clean the pieces without anyone knowing.'),
      q('What does “making excuses” mean here?', 'Giving reasons to avoid responsibility', 'Offering to buy a new cup', 'Explaining where the cup came from', 'Writing a note to Sinta', 'He tells the truth without blaming the sink or the cup.'),
      q('Why could a new cup not fully replace the old one?', 'The old cup was a gift from Sinta’s sister', 'The new cup was a different color', 'The shop had no cups', 'Sinta did not drink at work', 'The first cup had personal meaning beyond its practical use.'),
      q('What changed between the coworkers after the apology?', 'They kept trust and later laughed together', 'Sinta stopped speaking to him', 'The narrator left the office', 'They removed every kitchen cup', 'Honesty allowed the relationship to continue after the loss.'),
      q('What does the story show about responsibility?', 'It starts with truth even when harm remains', 'It always returns the lost object', 'It removes another person’s sadness', 'It means every mistake needs punishment', 'The narrator cannot restore the gift but can be honest and try to repair.'),
    ],
  },
  {
    id: 'a1-akhlak-10', level: 'A1', scriptDecision: 'keep; simplify abstract closing language and preserve the balanced anger lesson',
    replaceText: [['without trying to hurt or humiliate him', 'without trying to hurt or shame him'], ['with fairness and self-respect', 'feeling calm and fair']],
    tags: { 0: 'tired', 2: 'angry', 4: 'concerned', 7: 'understanding', 10: 'firmly', 13: 'reflective' },
    additions: [
      q('What details made the narrator pause?', 'The worker was wet, shaking, and worried', 'The machine was already fixed', 'The rain had stopped', 'Another customer arrived', 'Those signs suggested that something difficult had happened.'),
      q('What does “speak sharply” mean?', 'Speak in an angry and hurtful way', 'Speak quietly and slowly', 'Ask a clear question', 'Explain a repair plan', 'The narrator first wanted his words to show strong anger.'),
      q('Why could the worker not call?', 'His phone battery was dead', 'He did not know the number', 'His hands were wet', 'The workshop had his phone', 'The dead battery prevented an update during the delay.'),
      q('Did calm behavior remove the customer’s complaint?', 'No, he still asked for better updates', 'Yes, he said the delay was fine', 'No, he refused the repair', 'Yes, he paid for the motorcycle', 'He stayed respectful while clearly naming the service problem.'),
      q('What did one calm question provide?', 'The missing part of the story', 'A faster washing machine', 'A new work schedule', 'A free repair', 'Asking what happened helped him respond with more information.'),
    ],
  },
];
