import { q } from '../helpers.mjs';

export const reviews = [
  {
    id: 'a1-health-01', level: 'A1', scriptDecision: 'keep; doctor-supported change with gradual progress and clear personal results',
    replaceText: [['The first morning was humiliating', 'The first morning felt embarrassing'], ['One thing, done consistently', 'One thing, done regularly']],
    tags: { 0: 'discouraged', 3: 'concerned', 7: 'determined', 9: 'tired', 12: 'hopeful', 16: 'proud', 20: 'encouraging' },
    additions: [
      q('Why did the doctor ask for one small change?', 'A simple start felt possible', 'The narrator needed a gym', 'The stairs were closed', 'Walking was the only exercise', 'One manageable action helped the narrator begin.'),
      q('What does “breathless” mean?', 'Having difficulty breathing after effort', 'Unable to speak to the doctor', 'Feeling sleepy at work', 'Having pain in the hands', 'The stairs and first walk made breathing difficult.'),
      q('How did the walking distance change?', 'One block grew into a longer route', 'Forty minutes became five minutes', 'The park loop was removed', 'The narrator stopped after one week', 'The narrator increased the route gradually over several weeks.'),
      q('Which result appeared besides easier walking?', 'Less back pain and better sleep', 'A new work schedule', 'Faster medical tests', 'More time at a desk', 'The narrator reports several personal improvements after two months.'),
      q('What is the safe lesson from this story?', 'Begin with a suitable small step and medical guidance', 'Copy the same plan without checking health', 'Exercise through dizziness', 'Change everything in one day', 'The narrator begins after a doctor’s check and progresses slowly.'),
    ],
  },
  {
    id: 'a1-health-02', level: 'A1', scriptDecision: 'keep; clinical check occurs before routine advice and includes follow-up',
    tags: { 0: 'warmly', 1: 'exhausted', 5: 'concerned', 10: 'nervous', 12: 'relieved', 16: 'practical', 23: 'hopeful' },
    additions: [
      q('What happens before the doctor gives advice?', 'She checks Farid and asks questions', 'Farid drinks more coffee', 'The manager changes deadlines', 'Farid goes home to sleep', 'The doctor first gathers information and examines him.'),
      q('What does “recover” mean here?', 'Rest and regain energy', 'Finish a work deadline', 'Drink coffee at night', 'Measure blood pressure', 'The doctor says sleep helps the body regain strength.'),
      q('Why may afternoon coffee be a problem?', 'It can make sleep harder', 'It always raises blood pressure', 'It replaces every meal', 'It creates more work deadlines', 'The doctor connects late caffeine with difficulty falling asleep.'),
      q('Why do short screen breaks sound possible to Farid?', 'They need only a few minutes', 'His manager canceled work', 'He already takes long breaks', 'The laptop is broken', 'A five-minute break feels manageable during a busy day.'),
      q('Why is the one-month return important?', 'The doctor can review whether symptoms changed', 'Farid needs another coffee plan', 'The office requires a note', 'The first check was not completed', 'Follow-up checks whether the plan helped or more care is needed.'),
    ],
  },
  {
    id: 'a1-health-03', level: 'A1', scriptDecision: 'keep; personal recovery story clearly describes rest and family support, not a universal treatment',
    tags: { 0: 'unwell', 3: 'thoughtful', 5: 'tired', 8: 'grateful', 12: 'hopeful', 17: 'relieved', 19: 'warmly' },
    additions: [
      q('Why did the narrator stay home?', 'Work might make the illness worse', 'The supervisor closed the office', 'His sister needed help', 'The book was difficult to read', 'He chose rest instead of forcing himself through work.'),
      q('What does “pushing myself” mean here?', 'Forcing himself to continue while sick', 'Moving a heavy object', 'Calling the clinic many times', 'Walking quickly to work', 'He usually continues working even when his body needs rest.'),
      q('What improved on the second day?', 'The headache became lighter', 'All symptoms disappeared', 'The narrator returned to work', 'His eyes could read for hours', 'The fever remained, but the head pain softened.'),
      q('Why was the sister’s soup important?', 'It provided care and made him feel supported', 'It immediately ended the illness', 'It replaced the need for rest', 'It allowed him to work from home', 'Her daily visit was both practical and emotionally meaningful.'),
      q('What should happen before returning to normal activity?', 'The person should be well enough and follow health guidance', 'A fixed four-day period must pass', 'The fever should be ignored', 'Work should begin while symptoms grow', 'The story is personal; readiness and appropriate guidance matter.'),
    ],
  },
  {
    id: 'a1-health-04', level: 'A1', scriptDecision: 'keep; doctor assessment precedes stress-management changes and the story avoids self-diagnosis',
    replaceText: [['basic maintenance for your whole body and mind', 'basic care for your body and mind'], ['Enormously.', 'A lot.']],
    tags: { 0: 'warmly', 3: 'stressed', 5: 'frightened', 7: 'calmly', 11: 'relieved', 17: 'encouraging', 23: 'warmly' },
    additions: [
      q('What did Nadia do after her heart raced?', 'She visited a doctor', 'She searched only online', 'She stopped sleeping', 'She worked through the night', 'She sought medical help instead of deciding the cause herself.'),
      q('What does “scattered” mean for her thoughts?', 'Hard to organize', 'Easy to remember', 'Focused on one task', 'Ready for sleep', 'Stress made her thoughts feel divided and difficult to control.'),
      q('What does Nadia avoid during her five-minute break?', 'Her phone', 'Slow breathing', 'A closed laptop', 'A quiet room', 'She creates a real pause without another screen.'),
      q('Where did Nadia notice stress in her body?', 'Shoulders, stomach, and sleep', 'Only her hands', 'Only her eyesight', 'Her feet after walking', 'She explains that stress can have physical signs.'),
      q('What is Nadia’s main purpose?', 'Share small habits that helped after medical advice', 'Promise one method works for everyone', 'Replace professional health care', 'Teach listeners to ignore a racing heart', 'Her experience encourages small steps while beginning with proper assessment.'),
    ],
  },
  {
    id: 'a1-health-05', level: 'A1', scriptDecision: 'keep family memory; add a clear boundary that one person’s habits are not a guarantee',
    replaceText: [['Simple advice, but I finally understand why it worked so well.', 'These habits suited her life and later helped me too, but every person may need different health advice.']],
    tags: { 0: 'warmly', 3: 'admiring', 7: 'amused', 10: 'reflective', 14: 'inspired', 18: 'thoughtful' },
    additions: [
      q('Why did the grandmother refuse many rides?', 'She wanted to keep walking', 'She disliked the market', 'The garden needed a car', 'She could not ride safely', 'Walking was a regular part of her daily life.'),
      q('What does “old-fashioned” mean here?', 'Belonging to an earlier way of life', 'Dangerous for an older person', 'New and difficult', 'Only used at a gym', 'As a teenager, the narrator thought the habits seemed from another time.'),
      q('How did the narrator eat differently later?', 'More slowly and away from a screen', 'Only from the garden', 'Earlier than everyone', 'Without home cooking', 'The narrator adopted part of the grandmother’s calm routine.'),
      q('What made the grandmother’s routine consistent?', 'She repeated simple habits for many years', 'She followed a special short program', 'She changed the habits weekly', 'She used expensive equipment', 'The same ordinary choices continued over decades.'),
      q('What important limit is stated at the end?', 'Different people may need different advice', 'The habits guarantee a long life', 'Everyone should refuse every ride', 'Medical guidance is unnecessary', 'A personal family experience should not be treated as a promise for all people.'),
    ],
  },
  {
    id: 'a1-health-06', level: 'A1', scriptDecision: 'replace; previous friend gave unsafe direct medication instructions without checking the label or professional advice',
    replaceScript: [
      "Sami: [concerned] Hi Rania. I heard you have been sick since yesterday. How are you feeling now?",
      "Rania: I still have a fever and a sore throat. I feel weak, and I did not sleep well.",
      "Sami: Have you spoken with a clinic or another health professional?",
      "Rania: [tired] I called the clinic this morning. They asked about my symptoms and told me which warning signs need urgent help.",
      "Sami: Good. Do you have their instructions written down?",
      "Rania: Yes. They told me to rest, drink small amounts often, and call again if the fever continues or anything becomes worse.",
      "Sami: Have you been able to drink today?",
      "Rania: Only a little. Getting up to fill the bottle feels difficult.",
      "Sami: I can leave water and soup at your door this evening. Is six o'clock suitable?",
      "Rania: [grateful] That would help a lot. Please message before you arrive so I can open the door safely.",
      "Sami: Of course. Is there anyone nearby who can check on you sooner if you need help?",
      "Rania: My neighbor has my number, and my sister will call again this afternoon.",
      "Sami: You mentioned medicine yesterday. Have you checked the label and the clinic's advice?",
      "Rania: Yes. I wrote down the correct dose and the next time. I will not take extra or mix it with another product.",
      "Sami: That sounds careful. If you are unsure, call the pharmacist or clinic instead of guessing.",
      "Rania: [relieved] I will. Thank you for helping without acting like my doctor.",
      "Sami: Friendship can mean food, company, and helping you reach qualified care when you need it.",
      "Rania: The call already makes me feel less alone. I will rest now and follow the clinic's plan.",
      "Sami: [warmly] Good. I will message at six, and you can tell me if your needs change.",
      "Rania: Thank you, Sami. I appreciate the practical help."
    ],
    tags: { 0: 'concerned', 3: 'tired', 9: 'grateful', 15: 'relieved', 18: 'warmly' },
    baseQuiz: [
      q('What symptoms does Rania mention?', 'A fever, sore throat, and weakness', 'A broken arm and headache', 'Only a cough', 'No symptoms now', 'Rania explains that she still feels unwell and weak.'),
      q('Whom did Rania call?', 'A clinic', 'Her manager', 'A food shop', 'A bus driver', 'The clinic asked about symptoms and explained warning signs.'),
      q('What will Sami bring?', 'Water and soup', 'Two kinds of medicine', 'A work laptop', 'A medical report', 'Sami offers practical non-medical support.'),
      q('What has Rania written down?', 'The dose and next medicine time', 'Her work schedule', 'Sami’s home address', 'A new food recipe', 'She follows the label and professional advice instead of guessing.'),
      q('What will Rania do if unsure?', 'Call a pharmacist or clinic', 'Take an extra dose', 'Ask a social-media group', 'Mix two products', 'Qualified advice is the safe next step for medicine questions.'),
    ],
    additions: [
      q('Why does Rania keep the clinic instructions?', 'They guide safe next steps', 'They replace every future check', 'They prove the illness is minor', 'They tell Sami what medicine to choose', 'Written guidance helps her remember care and warning signs.'),
      q('What does “warning signs” mean?', 'Symptoms that may need quick medical help', 'Signs outside the clinic', 'Normal changes in a food order', 'Reasons to return to work', 'The clinic explains when Rania should seek more urgent care.'),
      q('Why does Sami message before arriving?', 'Rania asked for a safe and easy visit', 'Sami needs the clinic address', 'The soup is not ready', 'The neighbor closed the door', 'Planning the delivery respects Rania’s condition and space.'),
      q('What medical boundary does Sami keep?', 'He supports Rania but does not prescribe treatment', 'He chooses a larger dose', 'He tells her to stop clinic care', 'He decides the illness is harmless', 'Sami offers food, water, contact, and access to qualified help.'),
      q('What is the main value of the call?', 'Rania receives safe support and feels less alone', 'Rania returns to work immediately', 'Sami solves the illness himself', 'Medicine becomes unnecessary', 'The friends combine practical care with professional boundaries.'),
    ],
  },
  {
    id: 'a1-health-07', level: 'A1', scriptDecision: 'keep personal sleep story; soften cause language and avoid a universal promise',
    replaceText: [['I get sick far less often than before', 'I have also been sick less often, although many things can affect health'], ['Absolutely. It costs nothing, just discipline, and it changed how my whole day feels', 'The simple routine helped me, but anyone with continuing sleep problems should seek proper advice']],
    tags: { 0: 'cheerfully', 1: 'tired', 5: 'concerned', 9: 'determined', 15: 'surprised', 20: 'carefully' },
    additions: [
      q('What was difficult on weekends?', 'Keeping the same bedtime', 'Turning on brighter lights', 'Waking without an alarm', 'Talking with the radio host', 'The caller was used to staying up late without limits.'),
      q('What does “irritable” mean?', 'Easily annoyed', 'Very sleepy', 'Often hungry', 'Ready to exercise', 'Poor sleep was connected with impatient behavior toward family.'),
      q('Why does the caller dim the lights?', 'To help the body slow down', 'To save the phone battery', 'To wake without an alarm', 'To make the room colder', 'Lower light becomes a signal that bedtime is near.'),
      q('What personal result appeared after two weeks?', 'Waking without an alarm', 'Never becoming sick again', 'Sleeping only five hours', 'Using the phone in bed', 'The caller noticed easier natural waking.'),
      q('What should someone do if sleep problems continue?', 'Seek appropriate professional advice', 'Copy one caller’s routine only', 'Stay awake until exhausted', 'Ignore effects on daily life', 'The revised ending makes clear that one experience is not universal care.'),
    ],
  },
  {
    id: 'a1-health-08', level: 'A1', scriptDecision: 'keep; nurse-supported walking habit states its limits clearly',
    tags: { 0: 'tired', 2: 'reflective', 4: 'practical', 6: 'surprised', 9: 'cheerful', 11: 'relieved', 13: 'warmly' },
    additions: [
      q('Why did the narrator once avoid exercise?', 'It seemed to need time and special equipment', 'Walking caused every headache', 'The nurse advised no movement', 'Work was outside all day', 'The narrator had an unrealistic picture of what exercise required.'),
      q('What does “routine checkup” mean?', 'A regular health visit', 'An emergency operation', 'A meeting with a coworker', 'A daily walk', 'The nurse asked about sitting during a normal health appointment.'),
      q('Why do coworkers avoid work talk on the walk?', 'The walk is meant to be a real break', 'Their manager is nearby', 'They have no unfinished tasks', 'The market is too loud', 'Keeping work out of the conversation helps attention rest.'),
      q('How did they continue on a rainy day?', 'They walked through a covered market', 'They ran outside without cover', 'They canceled the whole habit', 'They exercised at a gym', 'The routine changed location instead of requiring perfect weather.'),
      q('What limit does the narrator state?', 'A short walk cannot solve every health problem', 'Seven minutes never counts', 'Walking always changes weight', 'Medical advice is no longer needed', 'The narrator continues professional care and avoids a broad promise.'),
    ],
  },
  {
    id: 'a1-health-09', level: 'A1', scriptDecision: 'keep; strong medication-safety script centered on pharmacist guidance and label use',
    tags: { 0: 'unwell', 2: 'concerned', 4: 'surprised', 7: 'attentive', 10: 'thoughtful', 13: 'firmly' },
    additions: [
      q('Why did the two boxes seem different?', 'They were for different symptoms', 'They came from different pharmacies', 'Only one had a label', 'One belonged to a friend', 'The front labels focused on headache and cold symptoms.'),
      q('What is an “ingredient” in medicine?', 'A substance used in the product', 'The measuring cup', 'The time between doses', 'A health condition', 'Both products contained the same active substance.'),
      q('Why did the pharmacist ask about other medicine?', 'Different products can affect safe use', 'She wanted to sell more boxes', 'The narrator forgot the price', 'The cold had already ended', 'The full medicine list helps prevent unsafe combinations.'),
      q('Why is a kitchen spoon not used?', 'It may not measure the correct amount', 'It is too clean', 'It changes the ingredient', 'It belongs to the nephew', 'The package cup is made for accurate dosing.'),
      q('Which action protects the young nephew?', 'Keeping medicine out of his reach', 'Showing him both labels', 'Using a larger cup', 'Leaving the box open', 'Safe storage prevents a child from taking the medicine.'),
    ],
  },
  {
    id: 'a1-health-10', level: 'A1', scriptDecision: 'keep; gradual return includes warning symptoms, rest days, and a health-check boundary',
    tags: { 0: 'eager', 1: 'carefully', 5: 'practical', 7: 'firmly', 9: 'relieved', 15: 'thoughtful', 19: 'encouraging' },
    additions: [
      q('Why is the old five-kilometer ability not enough?', 'The body has changed during a year off', 'The route no longer exists', 'The coach dislikes running', 'New shoes make it unsafe', 'Past ability does not remove the need to rebuild gradually.'),
      q('What does “recover well” mean?', 'Feel ready again after a session', 'Run faster during the session', 'Buy more equipment', 'Exercise every day', 'The coach wants Tariq’s body to handle and recover from the activity.'),
      q('When should Tariq stop during a session?', 'With pain, dizziness, or unusual breathing', 'When walking begins', 'After exactly one minute', 'Whenever another runner passes', 'Those warning signs require him to stop and respond safely.'),
      q('Why does Tariq keep a note?', 'To track how each session feels', 'To compare with other runners', 'To record shoe prices', 'To avoid rest days', 'A simple record supports a careful decision about progress.'),
      q('What does “not a race against your past” mean?', 'Do not force the body to match old ability now', 'Try to beat every old time', 'Never remember earlier exercise', 'Choose a competitive route', 'Safe current progress matters more than proving former fitness.'),
    ],
  },
];
