import { q } from '../helpers.mjs';

export const reviews = [
  {
    id: 'a1-prophets-01', level: 'A1', scriptDecision: 'revise lightly; preserve the repentance lesson while avoiding unsupported detail and simplifying abstract language',
    replaceText: [['breathed life into him', 'gave him life'], ['close to their Lord', 'with Allah’s guidance'], ['because they admitted the mistake fully, without excuses and without blaming each other', 'after they admitted their wrong and asked Him for mercy'], ['That same door stays open for us today, my child.', 'Allah teaches us not to lose hope in His mercy, my child.']],
    tags: { 0: 'warmly', 2: 'gently', 5: 'cautiously', 7: 'sadly', 8: 'hopeful', 10: 'thoughtful', 14: 'warmly' },
    additions: [
      q('What did Allah teach Adam?', 'The names of many things', 'How to build a ship', 'How to make armor', 'The meaning of a dream', 'The father mentions this near the beginning.'),
      q('What did shaytan do?', 'Whispered about the forbidden tree', 'Asked Adam to leave the garden', 'Taught the names of animals', 'Offered Adam a new home', 'The whisper made the forbidden choice seem attractive.'),
      q('How did Adam and Hawa respond after the mistake?', 'They asked Allah for forgiveness', 'They blamed the garden', 'They forgot Allah completely', 'They returned to the tree', 'They turned back with honest repentance.'),
      q('What does “repentance” mean here?', 'Returning to Allah after doing wrong', 'Hiding a mistake forever', 'Living in a garden', 'Learning a family skill', 'The story connects repentance with admitting wrong and asking mercy.'),
      q('What does the father want the child to remember?', 'Do not lose hope after a mistake', 'People never make mistakes', 'Every warning is difficult', 'Life on earth has no work', 'The final lesson centers on honest return and Allah’s mercy.'),
    ],
  },
  {
    id: 'a1-prophets-02', level: 'A1', scriptDecision: 'revise; correct the Quranic time statement and keep the podcast focused on patient, sincere effort',
    replaceText: [['Yes, nearly nine hundred and fifty years, according to the Quran. Most people still refused to listen.', 'The Quran says he remained among his people for nine hundred and fifty years. Most still refused his call.'], ['saving only Nuh and the believers with him', 'and Allah saved Nuh and the believers who were with him'], ['never giving up completely', 'continuing his call with patience']],
    tags: { 0: 'warmly', 3: 'thoughtful', 5: 'carefully', 7: 'sadly', 9: 'reflective', 11: 'seriously', 13: 'warmly', 17: 'hopeful' },
    additions: [
      q('What did Nuh call his people to leave?', 'The worship of idols', 'Their homes at night', 'Work near the sea', 'A large city', 'His message called them back to worshipping Allah alone.'),
      q('How did many people treat Nuh?', 'They mocked or ignored him', 'They immediately followed him', 'They helped build from the first day', 'They made him their king', 'The dialogue describes long rejection.'),
      q('What did Allah tell Nuh to build?', 'A large ship', 'A high wall', 'A stone house', 'A metal bridge', 'The ship was built before the flood.'),
      q('What does “faithful” mean in this lesson?', 'Remaining true to Allah', 'Receiving fast results', 'Never feeling pain', 'Winning every argument', 'The guest separates faithfulness from quick success.'),
      q('Who controls the final result of sincere effort?', 'Allah', 'The podcast host', 'The largest group', 'The person who speaks longest', 'The guest says people try sincerely while results belong to Allah.'),
    ],
  },
  {
    id: 'a1-prophets-03', level: 'A1', scriptDecision: 'revise lightly; retain Quranic and established account while removing a changing numerical claim and simplifying the final comparison',
    replaceText: [['millions of people still drink from that same well every single year', 'pilgrims still drink Zamzam water today'], ['True trust isn\'t tested once. It gets tested repeatedly, in different ways, throughout a whole life.', 'Trust in Allah may be needed many times and in different tests.'], ['The situations change, but the choice between fear and trust stays the same for all of us.', 'Our lives are different, but we still need courage and trust in Allah.']],
    tags: { 0: 'curious', 2: 'thoughtful', 4: 'amazed', 6: 'serious', 8: 'softly', 9: 'relieved', 12: 'reflective', 17: 'warmly' },
    additions: [
      q('Why did Ibrahim tell the people to ask the largest idol?', 'To show that an idol could not speak', 'To learn who made the idols', 'To ask for water', 'To find Hajar and Ismail', 'The question showed the idol’s lack of power.'),
      q('Who asked whether Allah had commanded the desert journey?', 'Hajar', 'Nadia', 'Bilal', 'A pilgrim', 'Hajar’s question led to her statement of trust.'),
      q('What appeared in the desert?', 'The well of Zamzam', 'A large ship', 'A garden of tomatoes', 'A wall of water', 'Water came when Hajar and Ismail needed it.'),
      q('What does “shaky” mean when Nadia describes her trust?', 'Not strong or steady', 'Loud and confident', 'Easy to explain', 'Ready for travel', 'She says one difficult week can weaken her confidence.'),
      q('Why do the friends return to Ibrahim’s story?', 'It reminds them to trust Allah in tests', 'They want to count old idols', 'They are planning a mountain trip', 'They need a coffee recipe', 'They connect his example with challenges in their own lives.'),
    ],
  },
  {
    id: 'a1-prophets-04', level: 'A1', scriptDecision: 'revise; keep the Quranic story sequence but narrow claims about Egypt and simplify difficult wording',
    replaceText: [['A passing caravan found him and, sadly, sold him into slavery far away, in the land of Egypt.', 'A traveling group found him, and he was later sold in Egypt.'], ['his wise advice saved all of Egypt from starvation', 'his wise plan helped Egypt prepare for the years of famine'], ['trusted completely by the king to manage the entire land', 'given an important position to manage the food stores'], ['his brothers froze in fear', 'his brothers became afraid']],
    tags: { 0: 'warmly', 2: 'sadly', 3: 'with sorrow', 5: 'seriously', 7: 'hopeful', 9: 'thoughtful', 11: 'tense', 12: 'mercifully', 14: 'warmly' },
    additions: [
      q('Why did Yaqub tell Yusuf to keep the dream quiet?', 'The dream had an important meaning', 'The stars were difficult to count', 'Yusuf needed more sleep', 'The family was traveling', 'His father understood that the dream was special.'),
      q('What caused the brothers to harm Yusuf?', 'Jealousy', 'Hunger', 'Fear of Egypt', 'A king’s order', 'They were jealous of their father’s love for him.'),
      q('What ability did Allah give Yusuf?', 'Understanding dreams', 'Splitting the sea', 'Making armor', 'Building a ship', 'This gift later brought his knowledge to the ruler.'),
      q('Why did the brothers travel to Egypt?', 'To find food during famine', 'To visit Yusuf in prison', 'To sell a caravan', 'To learn about stars', 'The shortage brought them before Yusuf years later.'),
      q('How did Yusuf treat his brothers at the end?', 'He forgave them', 'He left them in a well', 'He sent them to prison', 'He refused to speak', 'His mercy is the final focus of the story.'),
    ],
  },
  {
    id: 'a1-prophets-05', level: 'A1', scriptDecision: 'keep with light simplification; chronological classroom account clearly connects Musa’s rescue, mission, and Pharaoh’s pride',
    replaceText: [['without knowing who he truly was at first', 'while he was still a baby'], ['proved Musa\'s message was true', 'supported Musa’s message'], ['pride can blind a person, even when the truth is completely obvious', 'pride can make a person refuse the truth even after clear signs']],
    tags: { 0: 'warmly', 1: 'seriously', 2: 'gently', 4: 'thoughtful', 5: 'firmly', 7: 'tense', 8: 'dramatically', 9: 'amazed', 12: 'curious', 15: 'sadly' },
    additions: [
      q('How did Musa’s mother place him on the river?', 'Inside a basket', 'On a wooden ship', 'Behind a wall', 'With an army', 'She trusted Allah while protecting her baby.'),
      q('Where did Musa grow up?', 'In Pharaoh’s household', 'Inside a prison', 'Beside the sea', 'In a farming village', 'The same ruling household later raised him.'),
      q('What message did Musa give Pharaoh?', 'Release the oppressed Israelites', 'Build a larger palace', 'Send the army to sea', 'Raise Musa as a child', 'Musa called for an end to slavery and oppression.'),
      q('What did Musa strike the sea with?', 'His staff', 'A basket', 'A metal ring', 'A stone idol', 'Allah commanded him to use his staff.'),
      q('Why did Pharaoh continue refusing?', 'His pride', 'He did not hear Musa', 'He wanted to cross first', 'The student stopped asking', 'The teacher names pride as the main reason.'),
    ],
  },
  {
    id: 'a1-prophets-06', level: 'A1', scriptDecision: 'revise; preserve the Quranic account while stating that Isa’s miracles occurred only by Allah’s permission',
    replaceText: [['that this child would be a sign and a mercy for all people', 'that this child would be a sign and a mercy from Allah'], ['Allah gave him the ability to heal the sick and speak with wisdom beyond his years', 'Allah allowed him to heal the sick by His permission'], ['Yet through every miracle, Isa never claimed power for himself. He always pointed people back toward worshipping Allah alone.', 'Isa was Allah’s servant and messenger, and he called people to worship Allah alone.'], ['always redirecting praise toward his Lord instead of himself', 'remaining a servant and messenger of Allah']],
    tags: { 0: 'softly', 2: 'amazed', 3: 'confused', 5: 'sadly', 6: 'with wonder', 8: 'thoughtful', 9: 'firmly', 12: 'peacefully' },
    additions: [
      q('What news did the angel bring Maryam?', 'She would have a son', 'She would travel to Egypt', 'She would build a place of worship', 'She would meet a king', 'The birth would happen by Allah’s command.'),
      q('Why was Maryam confused?', 'She had no husband', 'She did not know the angel', 'She was already old', 'She could not speak', 'She wondered how the promised birth could happen.'),
      q('How did baby Isa defend his mother?', 'He spoke from the cradle', 'He wrote a letter', 'He called another angel', 'He left the crowd', 'His speech was a sign from Allah.'),
      q('By whose permission did Isa heal?', 'Allah’s permission', 'His own independent power', 'The crowd’s permission', 'Maryam’s medicine', 'The revised script makes the source of the miracle clear.'),
      q('What personal lesson does the narrator take?', 'Use gifts with humility', 'Hide every useful skill', 'Ask people for praise', 'Stop learning new things', 'The reflection connects blessings with humble service.'),
    ],
  },
  {
    id: 'a1-prophets-07', level: 'A1', title: 'A Phone Call About Mercy After Ta’if', scriptDecision: 'replace; remove a disputed popular conquest quotation and use the well-established account of mercy after Ta’if',
    replaceScript: [
      'Amir: [thoughtful] Laila, I read a report about the Prophet Muhammad after his difficult visit to Ta’if.',
      'Laila: What happened during that visit?',
      'Amir: He invited the people to worship Allah, but they rejected him and treated him cruelly.',
      'Laila: [sadly] He must have felt deep pain after leaving the city.',
      'Amir: Yes. Later, the angel of the mountains came with an offer to crush the people between two mountains.',
      'Laila: That was a moment when punishment was possible. How did the Prophet respond?',
      'Amir: [gently] He did not ask for their destruction. He hoped that their descendants would worship Allah alone.',
      'Laila: He hoped for good from families whose people had just harmed him?',
      'Amir: Exactly. His mercy looked beyond his own pain and beyond that one terrible day.',
      'Laila: [reflective] Mercy is much harder when a person has the power to answer harm with harm.',
      'Amir: That is why this account stayed with me. He did not call cruelty good, but he still wanted guidance for them.',
      'Laila: So forgiveness does not mean saying that the wrong action was acceptable.',
      'Amir: [carefully] Right. We can name a wrong, protect people from harm, and still avoid personal revenge.',
      'Laila: How can we use that lesson in an ordinary disagreement?',
      'Amir: We can pause before answering, choose fair words, and ask Allah to guide everyone involved.',
      'Laila: [honestly] I often prepare a sharp reply before I think about what it may cause.',
      'Amir: I do too. The story gives us a higher example, even if our own problems are much smaller.',
      'Laila: It also reminds me that another person may change later.',
      'Amir: [hopeful] Yes. We should not close the door to guidance because of one painful moment.',
      'Laila: Thank you for calling. This is a clear lesson in mercy, truth, and self-control.'
    ],
    tags: { 0: 'thoughtful', 3: 'sadly', 6: 'gently', 9: 'reflective', 12: 'carefully', 15: 'honestly', 18: 'hopeful' },
    baseQuiz: [
      q('Where had the Prophet Muhammad visited?', 'Ta’if', 'Egypt', 'A mountain campsite', 'A farm', 'The phone call discusses his difficult visit to Ta’if.'),
      q('How did the people respond to his message?', 'They rejected and harmed him', 'They all accepted at once', 'They gave him a ship', 'They asked him to rule', 'The visit ended with painful rejection.'),
      q('What did the angel of the mountains offer?', 'To punish the people severely', 'To guide a caravan', 'To build a safe house', 'To bring food', 'Punishment was possible after the harm.'),
      q('What did the Prophet hope for?', 'Their descendants would worship Allah', 'The city would become empty', 'Nobody would return there', 'His pain would be praised', 'He chose hope for future guidance.'),
      q('What did he refuse to seek?', 'Personal destruction of the people', 'Fair protection from harm', 'Guidance from Allah', 'Truth about the wrong', 'Mercy did not require pretending the harm was right.'),
    ],
    additions: [
      q('What does “descendants” mean?', 'Children and later family generations', 'People living on mountains', 'Travelers from another city', 'Angels offering help', 'The Prophet hoped for faith among later generations.'),
      q('What does Laila learn about forgiveness?', 'It does not make a wrong action acceptable', 'It requires calling harm good', 'It removes every safety step', 'It means never speaking honestly', 'Truth and mercy can exist together.'),
      q('What practical action does Amir suggest?', 'Pause before giving a sharp reply', 'Answer harm immediately', 'Repeat private news', 'End every relationship', 'A pause supports fair words and self-control.'),
      q('Why should the door to guidance stay open?', 'A person may change later', 'Every action is already correct', 'Pain is never real', 'Disagreements always end quickly', 'The conversation looks beyond one bad moment.'),
      q('What is the main focus of the phone call?', 'Mercy while still recognizing wrong', 'Travel directions to Ta’if', 'The size of two mountains', 'A debate about family names', 'The friends connect a prophetic example with daily self-control.'),
    ],
  },
  {
    id: 'a1-prophets-08', level: 'A1', scriptDecision: 'keep; well-grounded practical reflection connects Dawud’s armor craft with lawful, careful service',
    tags: { 0: 'warmly', 2: 'carefully', 4: 'thoughtful', 6: 'respectfully', 7: 'honestly', 10: 'carefully', 12: 'reflective' },
    additions: [
      q('What material did the class picture show?', 'Linked metal rings', 'Wooden shelves', 'River baskets', 'Farm tools', 'The rings helped students understand armor making.'),
      q('Why did every ring need care?', 'One weak part could reduce protection', 'The rings were only decoration', 'Dawud wanted quick results', 'The teacher planned to sell them', 'Armor depends on correctly connected parts.'),
      q('Which workers did the narrator notice?', 'A tailor and a mechanic', 'A farmer and a doctor', 'A host and a guest', 'A king and a guard', 'Both examples show quiet care in useful work.'),
      q('What did the uncle teach before repairing?', 'Measure and choose the right tool', 'Buy a new shelf immediately', 'Hide the loose part', 'Work without checking safety', 'Preparation came before using the shelf.'),
      q('What connects faith and skilled work?', 'Sincere, accurate, useful service', 'Fame for every worker', 'Finishing before everyone', 'Avoiding repeated practice', 'The final lesson values lawful work done responsibly.'),
    ],
  },
  {
    id: 'a1-prophets-09', level: 'A1', scriptDecision: 'keep; careful dua reflection avoids promising every requested outcome and combines trust with lawful action',
    tags: { 0: 'warmly', 2: 'carefully', 3: 'humbly', 5: 'reflective', 6: 'restless', 7: 'determined', 9: 'disappointed', 11: 'honestly', 13: 'hopeful' },
    additions: [
      q('Why did Zakariyya’s situation look impossible to people?', 'He was already old', 'He had stopped making dua', 'He needed a training place', 'He lived beside a closed road', 'His age made the request seem beyond normal expectation.'),
      q('What unhelpful habit did the narrator develop?', 'Checking email many times a day', 'Forgetting all documents', 'Sleeping through every morning', 'Asking other students for money', 'Restless waiting became repeated checking.'),
      q('What happened with the first program?', 'It rejected the application', 'It accepted the narrator immediately', 'It lost every document', 'It closed for one day', 'The first answer was disappointing.'),
      q('How did earlier preparation help later?', 'It supported an application to a better program', 'It changed the first rejection', 'It removed the need for effort', 'It guaranteed every future result', 'Responsible action remained useful after the first answer.'),
      q('What does the narrator refuse to claim?', 'Knowing why every delay happens', 'Having received a rejection', 'Applying to a second program', 'Learning from the story', 'The reflection keeps humility about Allah’s reasons.'),
    ],
  },
  {
    id: 'a1-prophets-10', level: 'A1', scriptDecision: 'keep; unusually strong and responsible discussion prevents prophetic patience from becoming harmful medical or social advice',
    tags: { 0: 'concerned', 1: 'understanding', 3: 'carefully', 5: 'firmly', 7: 'gently', 9: 'thoughtful', 11: 'practical', 15: 'seriously', 18: 'determined' },
    additions: [
      q('Why can a short reminder sound cold?', 'The listener may be living with real pain', 'The story has no lesson', 'Hospital visits are always long', 'Patience is only a slogan', 'Words need care when someone is suffering.'),
      q('What does patience not require?', 'Pretending pain does not exist', 'Turning to Allah', 'Seeking lawful treatment', 'Accepting helpful support', 'The teacher clearly rejects hiding or denying suffering.'),
      q('What should Huda do first at the hospital?', 'Listen and ask what help is useful', 'Give medical instructions', 'Compare her friend with others', 'Share the health news', 'Respectful support begins with the patient’s needs.'),
      q('Why should Huda ask before sharing news?', 'The friend’s privacy matters', 'The meal is a secret', 'The teacher needs permission', 'The visit must be longer', 'Health information belongs to the person affected.'),
      q('How will Huda give practical support?', 'Arrange dinner with the sister', 'Choose a treatment herself', 'Deliver a long speech', 'Ask many private questions', 'The planned meal is useful help within a safe boundary.'),
    ],
  },
];
