import { q } from '../helpers.mjs';

export const reviews = [
  {
    id:'a1-sahabah-01',level:'A1',scriptDecision:'revise; center the cave account on the Quran and remove invented public reactions and absolute claims',
    replaceText:[['believed him instantly, without asking for any proof at all','was among the earliest people to believe and support him'],['People later said that if Abu Bakr had doubted even one moment, the whole city might have doubted with him.','His early belief and support became important to the Muslim community.'],['The Prophet answered gently, asking what Abu Bakr thought of two people when Allah himself was their third companion.','The Prophet comforted him: “Do not grieve; indeed Allah is with us.”'],['the truthful one who never once doubted','As-Siddiq, a title connected with truthfulness and firm belief'],['until his last breath','through many difficult moments']],
    tags:{0:'warmly',3:'seriously',5:'loyally',7:'tense',9:'worried',10:'calmly',12:'relieved',14:'thoughtful',17:'reflective'},
    additions:[q('Where were the two travelers going?','Madinah','Egypt','Persia','Iraq','They left Makkah during the Hijrah.'),q('How long did they remain near the cave?','Three days','One night','One week','Forty days','They continued after three days.'),q('What words gave Abu Bakr comfort?','Allah is with us','The cave is empty','The road is short','The search has ended','The Quranic statement turns fear toward trust.'),q('What does “persecution” mean here?','Cruel treatment for faith','A friendly invitation','A business journey','A public celebration','The Muslims faced growing danger in Makkah.'),q('What later role did Abu Bakr hold?','First caliph','History teacher','Governor of Egypt','Leader of the search party','He led the community after the Prophet’s death.')],
  },
  {
    id:'a1-sahabah-02',level:'A1',scriptDecision:'revise; keep Umar’s justice theme but remove a weakly sourced popular donkey quotation',
    replaceText:[["I've also heard a famous quote about a donkey and a road. What's that story?",'How did this direct care connect with justice?'],["Umar once said that if a donkey stumbled on a broken road far away in Iraq, he feared Allah would still ask him why he had not fixed it.",'He understood leadership as a trust before Allah. He believed he was responsible for protecting people and answering their needs.'],["That's an incredible sense of responsibility for someone so far from his own city.",'That is a serious view of responsibility, not just a powerful title.'],['But the poor and the weak always felt safe coming to him for help.','His leadership is remembered for taking the needs of poor and vulnerable people seriously.']],
    tags:{0:'warmly',3:'honestly',5:'thoughtful',7:'carefully',9:'smiling',11:'seriously',13:'reflective',15:'thoughtful',18:'warmly'},
    additions:[q('What had Umar once done before accepting Islam?','Opposed the Prophet’s message','Led the Muslims','Taught history','Helped every poor family','His earlier position later changed greatly.'),q('Why did he walk through Madinah?','To learn people’s needs directly','To sell goods at night','To avoid his officials','To find a new house','He wanted more than reports from others.'),q('What does “caliph” mean in this audio?','A leader of the Muslim community','A history student','A market owner','A radio guest','Umar’s public responsibility is discussed.'),q('How did Umar view leadership?','As a trust before Allah','As a way to gain praise','As freedom from questions','As control without service','Responsibility, not title, is the focus.'),q('What should real strength do?','Protect people','Make people afraid','Hide hardship','Avoid ordinary families','The guest’s final lesson connects strength with protection.')],
  },
  {
    id:'a1-sahabah-03',level:'A1',scriptDecision:'keep with careful wording; established account presents Bilal’s faith, suffering, freedom, and service without graphic excess',
    replaceText:[['the one who gave the very first call to prayer','the Companion known for giving the call to prayer'],['paid to purchase his freedom immediately','helped purchase his freedom'],['because of his beautiful voice','and his strong voice carried the call clearly']],
    tags:{0:'thoughtful',2:'seriously',4:'sadly',6:'firmly',8:'steadfastly',10:'relieved',12:'warmly',14:'reflective',17:'encouraging'},
    additions:[q('What did Bilal’s enslaver want him to do?','Leave Islam and worship idols','Give the adhan','Travel to Madinah','Buy his freedom','The punishment tried to force a change of faith.'),q('What does “Ahad” express?','Allah is One','Patience is easy','Freedom is near','The sun is hot','Bilal repeated the truth of Allah’s oneness.'),q('How did Abu Bakr help?','He helped free Bilal','He placed the stone','He asked Bilal to hide','He taught him a trade','His action changed Bilal’s outward situation.'),q('What later service did Bilal perform?','He gave the adhan','He became a merchant','He hosted a radio show','He made armor','His voice called Muslims to prayer.'),q('What does Dewi mean by Bilal’s heart being free?','His faith was not controlled by the enslaver','He had already left Makkah','He felt no physical pain','He owned a large home','Inner belief remained firm during outward oppression.')],
  },
  {
    id:'a1-sahabah-04',level:'A1',scriptDecision:'keep; warm family narration accurately emphasizes Khadijah’s belief, comfort, wealth, and loyal support',
    replaceText:[['terrified, unsure of what had just happened to him','deeply shaken by what had happened'],['Loyalty like Khadijah\'s isn\'t loud or dramatic.','Loyalty like Khadijah’s can be quiet and steady.']],
    tags:{0:'warmly',2:'admiringly',3:'seriously',4:'gently',5:'reassuringly',7:'supportively',9:'reflective',11:'remembering',14:'softly'},
    additions:[q('What work was Khadijah known for?','Business','Farming','Teaching in Yathrib','Making armor','She was a respected businesswoman in Makkah.'),q('What did she do when the Prophet returned home?','Comforted and covered him','Asked him to leave','Called a search party','Gave a public speech','Her first response was calm care.'),q('Which qualities did she mention?','Honesty, kindness, and helping others','Wealth and travel','Strength and loud speech','Age and family size','She used his good character to reassure him.'),q('How did she use her wealth?','To support and protect the mission','To buy a private well','To organize a reunion','To build a road in Iraq','Her resources served the early Muslim community.'),q('Why does the grandmother’s voice remain important?','Her lesson still guides the narrator','She recorded a podcast','She owned the house in Makkah','She met Khadijah herself','The memory connects two examples of care.')],
  },
  {
    id:'a1-sahabah-05',level:'A1',scriptDecision:'revise; present the reported well account carefully and remove unsupported claims about intention and current condition',
    replaceText:[['There\'s a well in Madinah that\'s still connected to a companion named Uthman.','I read about the Well of Rumah and the Companion Uthman.'],['there was only one well in Madinah with truly fresh, clean water','people in Madinah needed the good water from a privately owned well'],['And here\'s the part I love most. Uthman never asked for public praise or recognition for it.','The lasting part I love is that his wealth made needed water available to other people.'],['He just wanted to please Allah, not to be thanked by people.','His charity is remembered as service given for Allah’s reward.'],['That well is even said to still exist today, still giving water after all these centuries.','The story of the well is still remembered today.'],['one generous decision could still matter, this many years later','one act of useful charity can be remembered many years later']],
    tags:{0:'curious',3:'seriously',5:'thoughtful',7:'warmly',9:'explaining',11:'relieved',13:'reflective',15:'carefully',17:'gently'},
    additions:[q('Why was the water difficult for some families?', 'The owner charged high prices','The well was always empty','Only travelers could drink','The water was in Makkah','Cost limited access to useful water.'),q('What did Uthman first purchase?', 'A share of the well','A farm beside it','Every well in Madinah','A water shop','The owner did not first sell all of it.'),q('How did the shared arrangement work?', 'Uthman had water on alternating days','Water was available once a month','Only merchants used it','Each family bought a new well','Days were divided between the owners.'),q('What happened after the whole well was purchased?', 'People could take water freely','Prices became higher','The well was closed','The water went only to rich families','The charity made the resource broadly available.'),q('What makes this charity useful?','It meets a continuing public need','It brings quick public praise','It helps only one visitor','It requires an invented modern claim','Water access serves many people over time.')],
  },
  {
    id:'a1-sahabah-06',level:'A1',scriptDecision:'revise; retain the sirah account while removing invented inner thoughts and absolute claims about hesitation',
    replaceText:[['Ali agreed immediately, without asking for time to think it over or weighing the danger to himself.','Ali accepted the dangerous task and remained in the house.'],['knowing full well that the men outside might discover the truth at any moment','while the men outside believed the Prophet was still there'],['He did not know, lying there, whether he would survive until morning. Yet he stayed completely still and calm.','The situation was dangerous, yet Ali completed the role given to him.'],["the complete absence of hesitation in his decision",'his willingness to accept a serious risk'],["He didn't need applause or recognition. He simply loved the Prophet and trusted Allah more than he feared death.",'His action showed loyalty, courage, and trust in Allah.']],
    tags:{0:'thoughtful',2:'seriously',4:'carefully',5:'bravely',6:'tense',8:'steady',9:'surprised',11:'reflective',15:'warmly'},
    additions:[q('Why did someone remain in the bed?','To delay the enemies’ discovery','To sleep after traveling','To wait for Abu Bakr','To protect some tools','The plan gave the Prophet time to leave.'),q('Who accepted this role?','Ali ibn Abi Talib','Umar ibn al-Khattab','Salman al-Farisi','Uthman ibn Affan','Ali remained in the house.'),q('What did the armed men expect?', 'To find the Prophet','To find a teacher','To find an empty cave','To find a merchant','They were surprised in the morning.'),q('Where was the Prophet going?', 'Toward Madinah','Toward Persia','Toward Iraq','Toward Egypt','The migration route led away from Makkah.'),q('Which qualities does the account show?', 'Loyalty, courage, and trust','Wealth, trade, and fame','Anger, speed, and praise','Silence, sleep, and surprise','The revised conclusion stays with supported outward actions.')],
  },
  {
    id:'a1-sahabah-07',level:'A1',title:'Asma and the Careful Hijrah Supplies',scriptDecision:'replace; avoid duplicating Salman and use a well-known female Companion’s practical service during the Hijrah',
    replaceScript:['Radio Host: [warmly] Today we are learning about Asma bint Abu Bakr and her service during the Hijrah.','Caller: I know she helped prepare supplies. What exactly did she do?','Radio Host: The Prophet Muhammad and Abu Bakr needed food for their journey from Makkah.','Caller: [curious] Carrying supplies must have required care because enemies were searching for them.','Radio Host: Yes. Asma prepared food and needed something to tie the food bag and water container.','Caller: What did she use?','Radio Host: [thoughtful] She divided her waist belt into two pieces and used them as ties.','Caller: Is that why she became known as the woman of the two belts?','Radio Host: Yes. Her simple solution became part of how Muslims remember her.','Caller: [impressed] The action sounds small, but safe travel depended on details like food and water.','Radio Host: Exactly. Important work is not always a public speech or a large event.','Caller: Did she only help once?','Radio Host: [carefully] The sound reports also show her courage when people came asking where her father was.','Caller: Did she reveal the travelers’ location?','Radio Host: No. She protected the private plan during a dangerous time.','Caller: [reflective] So her service included preparation, quick thinking, and keeping trusted information safe.','Radio Host: That is a good summary. We should tell the established account without inventing secret conversations.','Caller: How can we apply the lesson today?','Radio Host: [encouraging] Prepare useful details, protect people’s privacy, coordinate calmly with trusted people, and value the quiet work behind a good mission.','Caller: Thank you. Asma’s example makes practical service feel important in ordinary community life every day too.'],
    tags:{0:'warmly',3:'curious',6:'thoughtful',9:'impressed',12:'carefully',15:'reflective',18:'encouraging'},
    baseQuiz:[q('Who is the segment about?','Asma bint Abu Bakr','Aishah','Khadijah','Maryam','The radio segment introduces Asma.'),q('What journey needed supplies?','The Hijrah from Makkah','A trip to Persia','A visit to Egypt','A journey to Iraq','Food and water supported the migration.'),q('What did Asma divide?', 'Her waist belt','A water well','A food plate','A road map','Two pieces became useful ties.'),q('What information did she protect?', 'The travelers’ location','The price of water','A class schedule','A family recipe','Enemies were searching during a dangerous time.'),q('What lesson is emphasized?', 'Practical quiet service matters','Only public work matters','Details are unimportant','Every story needs invented dialogue','Preparation and privacy supported a major mission.')],
    additions:[q('What items needed ties?', 'A food bag and water container','Two school books','A sword and shield','A radio and phone','The travel supplies had to be secured.'),q('What title came from her solution?', 'The woman of the two belts','The owner of the well','The truthful teacher','The first caller','Her divided belt became a remembered detail.'),q('Why was the task important?', 'Travelers needed food and water safely packed','The supplies were for sale','The journey had many restaurants','The enemies asked for food','Small preparation supported survival on the road.'),q('What does “established account” mean?', 'A report supported by trustworthy sources','A dramatic scene someone invented','A private guess about feelings','A story with no known source','The host warns against adding unsupported scenes.'),q('How can a learner copy the good principle?', 'Prepare details and protect privacy','Share every travel plan','Wait for public praise','Ignore quiet tasks','The application stays ordinary and practical.')],
  },
  {
    id:'a1-sahabah-08',level:'A1',scriptDecision:'keep; responsible sirah script values patient teaching and explicitly rejects invented scenes',tags:{0:'warmly',2:'thoughtful',4:'calmly',6:'encouraging',7:'reflective',9:'seriously',11:'carefully',13:'gently'},additions:[q('What was Yathrib later called?','Madinah','Makkah','Persia','Iraq','Musab taught there before the Hijrah.'),q('With whom did Musab stay?','Asad ibn Zurarah','Salman al-Farisi','Abu Bakr','Umar ibn al-Khattab','The name is given in the account.'),q('What did Musab recite?', 'The Quran','A history article','A private letter','A travel map','He taught by reciting and explaining faith.'),q('What does “without forcing” show?', 'People were invited to listen and decide','Angry leaders were removed','Every family accepted immediately','Teaching required no patience','His calm manner created room for understanding.'),q('What unseen work does the narrator value?', 'Preparation before visible change','Public praise after success','Invented private conversations','Comfort without service','Small meetings helped prepare the city.')],
  },
  {
    id:'a1-sahabah-09',level:'A1',scriptDecision:'keep; careful educational script highlights Aishah’s scholarship, evidence, context, and responsible teaching',tags:{0:'warmly',2:'thoughtful',3:'firmly',5:'carefully',7:'honestly',9:'curious',11:'respectfully',13:'reflective'},additions:[q('Who learned from Aishah?', 'Men and women','Only family members','Only rulers','Only doctors','Her teaching served many students.'),q('What was knowledge more than?', 'Collecting many facts','Writing one question','Learning poetry','Remembering an event','Understanding evidence and context also mattered.'),q('What did the narrator add to class notes?', 'Sources and questions to check','Only every spoken sentence','Invented stories','Names without ideas','The new method organized reliable learning.'),q('Why ask where information came from?', 'To protect learning from weak claims','To embarrass the teacher','To avoid taking notes','To make class longer','Respectful evidence questions improve accuracy.'),q('What community reminder is included?', 'Value knowledgeable women as teachers','Keep knowledge private','Repeat every claim','Turn history into entertainment','Aishah’s example supports women’s learning and teaching.')],
  },
  {
    id:'a1-sahabah-10',level:'A1',scriptDecision:'keep; strong source-conscious dialogue balances sincere searching, verification, hardship, and community service',tags:{0:'warmly',2:'curious',5:'seriously',7:'thoughtful',9:'approving',11:'relieved',13:'explaining',15:'warmly',18:'carefully',21:'gently'},additions:[q('How did Salman continue learning?', 'He learned from teachers and followed guidance','He traveled without any plan','He accepted every person as honest','He stayed in one comfortable home','The journey had a thoughtful learning path.'),q('What serious hardship happened?', 'He was sold into slavery','He lost a radio job','He forgot his language','He missed a class','The script names betrayal and enslavement.'),q('Where did he hear about the Prophet?', 'Madinah','Makkah','Egypt','A cave','He checked signs there before accepting Islam.'),q('What useful idea came from Persia?', 'A defensive trench','A water well','Metal armor','A food list','His earlier background helped the community.'),q('Why avoid dramatic additions?', 'Trustworthy lessons do not need invented scenes','The journey was too short','Questions are not allowed','All details are unimportant','Reliable history separates known reports from imagination.')],
  },
];
