import { q } from '../helpers.mjs';
const R=(id,decision,additions,extra={})=>({id:`a1-tauhid-${id}`,level:'A1',scriptDecision:decision,tags:{0:'thoughtful',2:'reflective',4:'honestly',6:'determined',8:'warmly',10:'peacefully',12:'gently',15:'encouraging',18:'warmly'},additions,...extra});
export const reviews=[
R('01','revise; keep practical focus on khushu while avoiding a false choice between short and long prayer',[
q('What usually took the narrator’s attention?', 'A phone','A market','A train','A radio','The phone returned to the narrator’s hand immediately.'),q('What was different one evening?', 'The prayer was slower and more attentive','The prayer was skipped','A friend led the prayer','The phone rang loudly','Tiredness led to an unhurried moment.'),q('What does “rushing” mean?', 'Moving too quickly','Standing quietly','Learning meanings','Preparing early','Earlier movements happened with little attention.'),q('What helps before prayer now?', 'Putting the phone away','Opening more apps','Making a work list','Calling a friend','Distance from the device reduces distraction.'),q('What is the improved lesson?', 'Pray calmly with attention','Make every prayer shorter','Length alone creates focus','Ignore the meaning','The revision values presence, not a length comparison.')
],{replaceText:[['A short, slow prayer feels better than a long, fast one. That is what I learned this year.','Prayer feels different when I complete it calmly and pay attention to what I say. That is what I am learning.']]}),
R('02','revise; balance tawakkul, emotional honesty, job-search effort, and uncertainty without promising hardship always teaches one unique lesson',[
q('What did Nurul ask Allah for besides work?', 'Guidance','A larger house','A quick holiday','Public praise','Her dua became wider than one result.'),q('When did a smaller job appear?', 'After two months','The next morning','After one year','Before she lost work','It was enough though not perfect.'),q('Did prayer guarantee a faster job?', 'No, Nurul does not claim that','Yes, immediately','Yes, after one week','The host proves it did','She separates spiritual support from a guaranteed timeline.'),q('What does trust not mean?', 'Stopping all effort','Asking Allah for help','Working responsibly','Being patient with oneself','Nurul says a person still tries.'),q('What would she tell her past self?', 'Take responsible steps and be patient','Every hardship has one clear lesson','Anger is never human','A perfect job is certain','The revised ending avoids claiming knowledge of every test.')
],{replaceText:[['this hard season will teach you something you cannot learn any other way. Be patient with yourself.','keep taking responsible steps, ask Allah for guidance, and be patient with yourself. You may not understand every part of this test.']]}),
R('03','keep; ordinary coworker conversation uses brief observation and gratitude without claiming it solves workload',[
q('What fills Dewi’s week?', 'Meetings and deadlines','Travel and shopping','Family calls','Medical visits','She describes a heavy work schedule.'),q('When does Fajar pause?', 'Before opening the laptop','After leaving work','During every meeting','Before sleeping','His morning pause comes before work starts.'),q('What does Dewi usually open first?', 'Her phone','A window','A notebook','The office door','Her normal habit begins with the screen.'),q('How long is the suggested pause?', 'One minute','One hour','One afternoon','Ten seconds','The experiment is deliberately small.'),q('What is the purpose of noticing small things?', 'To begin with awareness and gratitude','To remove every deadline','To avoid doing work','To judge other workers','The dialogue offers a calm start, not a cure.')
]),
R('04','revise; keep personal experience of mercy without implying visible help always follows the same pattern',[
q('How many children did the grandmother raise?', 'Five','Two','Seven','One','She raised them after losing her husband.'),q('What did she say Allah gave her?', 'Strength','A new house','An easy life','A public award','Her answer focused on support during hardship.'),q('What later hardship did the narrator face?', 'Job loss','Serious travel delay','A broken radio','A missed prayer','The grandmother’s words returned during unemployment.'),q('Why did the narrator call more often?', 'To hear and understand her stories','To ask for money','To find a new manager','To plan a reunion','Adult experience created new questions.'),q('What balanced idea about mercy remains?', 'Mercy may give support without removing every hardship','Help always arrives as money','Hardship follows one fixed pattern','A believer always knows the reason','The revision avoids promising a visible form.')
],{replaceText:[['Every story had the same pattern. Hardship, and then, quietly, help arriving from somewhere unexpected.','Her stories helped me notice many forms of mercy, while she also admitted that some questions remained difficult.'],['Money arrived when I needed it most.','A small paid task helped with one urgent bill.']]}),
R('05','keep; compassionate pre-surgery call validates fear, recognizes clinical preparation, uses dua, breathing, and family presence',[
q('When will the surgery begin?', 'In one hour','Tomorrow evening','Next month','After one week','Rafi calls shortly before the operation.'),q('What preparation does the mother mention?', 'The doctors have prepared carefully','Rafi chose the medicine','The family changed the operation','No one checked anything','Trust exists beside medical work.'),q('What feeling is accepted as normal?', 'Fear','Pride','Boredom','Anger at staff','The mother does not shame Rafi.'),q('What can Rafi do before entering?', 'Make dua and breathe slowly','Cancel without speaking to doctors','Choose the surgical method','Ignore every instruction','The actions are spiritual and calming, not medical advice.'),q('What makes Rafi calmer?', 'His mother’s support and reminder','A guaranteed outcome','Control over everything','Leaving the hospital','The call gives presence without a promise.')
]),
R('06','revise; avoid forcing a hidden lesson from suffering and state humility about divine wisdom while allowing emotion and appropriate help',[
q('Does the narrator claim a perfect answer?', 'No','Yes, in one sentence','Yes, from personal pain alone','No, because faith has no guidance','The reflection begins with humility.'),q('What truth about this life is mentioned?', 'It is not the whole story','It has no hardship','It explains every event now','It removes the need for help','The hereafter gives a wider frame.'),q('Are crying and anger treated as human?', 'Yes','No, they always show weak faith','Only crying is allowed','Only anger is allowed','The narrator allows honest feelings.'),q('What should a person avoid forcing?', 'A quick lesson from every pain','Support from trusted people','Dua during hardship','Safe practical steps','The revision rejects simplistic meaning-making.'),q('What may help during a hard time?', 'Dua, safe help, and the next responsible step','Pretending sadness is gone','Knowing Allah’s full reason','Handling everything alone','The ending combines faith with support.')
],{replaceText:[['He is often closest during our lowest moments.','His knowledge, mercy, and care are never absent during hardship.'],['Instead of staying stuck, I try to look for the lesson quietly hidden inside it.','I try to take the next responsible step, seek support, and avoid forcing a quick lesson from every pain.'],['Not why is this happening, but what can I learn, and how is Allah near me right now.','I may still ask why, while also asking what safe step I can take and how I can turn to Allah now.']]}),
R('07','keep with modest wording; gratitude remains a personal family practice that does not replace financial action',[
q('What problem does the family face?', 'Financial hardship','A travel mistake','A stolen phone','A school reunion','Money has been difficult this year.'),q('How many things did the caller first write?', 'Three','One','Five','Ten','The list was short each night.'),q('Where does the family now share?', 'At dinner','At work','On the radio only','At the market','Each person names one thing.'),q('Did the list fix the money problem?', 'No','Yes, immediately','Yes, after two minutes','The host says it did','The caller clearly separates gratitude from finances.'),q('What continues beside gratitude?', 'Hard work on the real problem','Ignoring bills','Waiting without action','Telling everyone to copy','The caller still works to improve the situation.')
],{replaceText:[['Definitely. It costs nothing, takes two minutes, and it genuinely shifted how our whole family feels.','It helped our family, and others may try a short list while still seeking practical help for their problems.']]}),
R('08','keep; excellent tawakkul story combines planning, weather change, accessibility, teamwork, and acceptance of outcomes',[
q('What event was planned?', 'Outdoor food distribution','A job interview','A school trip','A family dinner','The forecast affected a community service plan.'),q('Why did the team change location?', 'Heavy rain arrived','Food was unavailable','The hall was closed','No volunteers came','Weather made the outdoor plan unsuitable.'),q('Who benefited from delivery help?', 'People unable to reach the site','Only the drivers','Weather reporters','Shop owners','The disruption revealed an access need.'),q('What does “forecast” mean?', 'A prediction of weather','A food list','A prayer schedule','A road rule','The expected clear morning changed.'),q('How is tawakkul shown?', 'Plan well, adapt, and trust Allah with results','Make no plan','Expect weather always to agree','Refuse every change','Effort and trust work together.')
]),
R('09','keep; concrete seed observation distinguishes human care from Allah creating life and avoids careless root testing',[
q('Where was the pot placed?', 'Beside a window','Under a bed','On a train','Inside a cupboard','Light came through the window.'),q('How often did the niece measure?', 'Once a week','Every hour','Once a year','Never','Weekly measuring avoided harming roots.'),q('Why was the pot moved?', 'The afternoon sun became too hot','The soil was missing','The window broke','The plant was fully grown','Care changed with conditions.'),q('What could the family control?', 'Water, light, and care','The creation of life','The exact day of every leaf','The seed’s inner power','Their effort had real but limited scope.'),q('What does Alhamdulillah express?', 'Praise and gratitude to Allah','Fear of the plant','A request for a grade','A measurement','The plant reminds them of blessings and care.')
]),
R('10','keep; clear interview dialogue defines tawakkul as preparation, dua, honest participation, and acceptance beyond one result',[
q('What has Farah researched?', 'The company and role','Train times','Hospital rules','Weather forecasts','Her preparation is already practical.'),q('What does Nadia advise about rest?', 'Stop preparing at a reasonable time','Practice all night','Skip the interview','Keep checking messages','Sleep is part of responsible readiness.'),q('Why not demand only one exact result?', 'Allah may know another outcome is better','The job is certainly wrong','Dua cannot mention work','Preparation has no value','Farah may ask while leaving the result to Allah.'),q('What can Farah control?', 'Preparation and honest answers','The interviewer’s final decision','Every future job','The company budget','Tawakkul recognizes the boundary.'),q('What should rejection not mean?', 'Every door is closed','The interview happened','One employer said no','More effort may be needed','Nadia keeps hope wider than one decision.')
])];
