import { q } from '../helpers.mjs';
const R=(id,decision,additions,extra={})=>({id:`a1-technology-${id}`,level:'A1',scriptDecision:decision,tags:{0:'warmly',2:'curious',4:'honestly',6:'carefully',8:'thoughtful',10:'practically',12:'reflective',14:'encouraging',17:'warmly'},additions,...extra});
export const reviews=[
R('01','keep; personal screen-time change uses gradual steps, sleep boundaries, and a realistic nonzero goal',[
q('When did the narrator use the phone at night?', 'Until falling asleep','Only before dinner','Never in bed','Once a week','The screen stayed in bed with the narrator.'),q('What app type was removed first?', 'The most-used social app','The alarm clock','The screen-time report','A banking app','One focused removal began the change.'),q('Why was the phone kept outside the bedroom?', 'To protect sleep and reduce checking','To improve the camera','To charge it faster','To answer more messages','An alarm clock replaced its nighttime job.'),q('Was the change immediate?', 'No, it happened through small steps','Yes, nine hours ended in one day','No, the report never changed','Yes, the phone was discarded','The script describes several habits over time.'),q('What is the current personal result?', 'About three hours of screen time','No screen use','Nine hours again','Three minutes a day','The report fell without claiming a universal target.')
]),
R('02','revise; add confidentiality and workplace-policy safeguards while keeping human review and fact checking central',[
q('Who still does most of the thinking?', 'Mira','The AI tool','The podcast host','Mira’s manager','The tool supports a human process.'),q('What almost went into an email?', 'A wrong meeting date','A private password','A correct salary','A new policy','The confident-looking output still contained an error.'),q('What must Mira check?', 'Facts and numbers','Only grammar','Nothing after generation','Whether the answer is long','Human verification is required.'),q('What information should not be pasted?', 'Private or confidential work data','A public idea','A common greeting','A blank outline','Policy and privacy come before convenience.'),q('What task is a safer small start?', 'A non-sensitive repetitive task','A final important decision','Sharing client records','Replacing all judgment','The advice limits risk while learning.')
],{replaceText:[['I ask myself one question before using it: am I saving time, or avoiding effort I actually need?','I first check workplace rules and never paste private client or company information. Then I ask whether I am saving time or avoiding needed thinking.'],['Start small. Use it for boring, repetitive tasks first, and keep your judgment for the important decisions.','Start with a non-sensitive repetitive task. Check every result, follow workplace policy, and keep human judgment for important decisions.']]}),
R('03','keep; practical notification dialogue distinguishes urgent contacts from optional alerts and gives the user control over checking time',[
q('What does buzzing interrupt?', 'Dewi’s train of thought','The office internet','Fajar’s lunch','A phone call','Repeated alerts break concentration.'),q('When did Fajar change settings?', 'A few months ago','That morning','Last year at school','After the conversation','His experience supports the suggestion.'),q('Which alerts remain?', 'Calls from close family and work needs','Every social reaction','All news updates','Game messages','Important contact stays possible.'),q('How are other apps checked?', 'At chosen times','Whenever they make noise','Only once a year','During meetings','The person, not the notification, chooses.'),q('What is Dewi’s first experiment?', 'Turn off nonessential alerts for an afternoon','Delete every app','Buy another phone','Ignore urgent calls','The trial is small and reversible.')
]),
R('04','keep; warm repair story teaches diagnosis, patience, and safe understanding rather than automatic replacement',[
q('What question did the father ask?', 'Why did it stop working?','How much is a new one?','Who broke every radio?','Where is the shop?','He began with the cause.'),q('What device later failed?', 'The narrator’s laptop','A market phone','A station screen','A work radio','The earlier method guided a modern problem.'),q('How was the laptop fixed?', 'By finding the problem step by step','By immediately replacing it','By ignoring the error','By guessing a password','Diagnosis came before action.'),q('Who now learns the same habit?', 'The narrator’s daughter','A hotel clerk','A coworker','The father’s manager','The lesson continues in the family.'),q('What does the story value?', 'Understanding before replacing','Keeping unsafe devices open','Repairing without skill','Never asking for help','Curiosity is useful within safe limits.')
]),
R('05','revise; improve stolen-phone response with personal safety, official account access, carrier contact, financial monitoring, and police reporting',[
q('What matters before the device?', 'Rafi’s physical safety','Buying a new phone','Saving the calendar','Finding the thief alone','His sister checks whether he is safe.'),q('Where should account changes happen?', 'Through official apps or websites','Through links in random messages','On a stranger’s phone without logout','By replying to the thief','Official access reduces another security risk.'),q('Why contact the mobile carrier?', 'To block the SIM','To recover photos','To buy a camera','To call the market','A stolen SIM may receive codes.'),q('Who should be told about suspicious bank activity?', 'The bank through an official channel','A public social group','Only the phone shop','Nobody','Financial accounts need prompt protection.'),q('What records the theft?', 'A police report','A cloud backup','A new password','A screen lock','Reporting creates an official record.')
],{replaceText:[['Change your important passwords, starting with your email and your banking app, just to be careful.','Use official apps or websites to secure your email and financial accounts. Contact the mobile carrier to block the SIM too.'],['Okay. I\'ll report it to the police first, then go buy a simple new phone tomorrow.','Okay. I’ll report it to the police, call the carrier and bank through official numbers, and watch for unusual account activity.']]}),
R('06','revise lightly; strengthen phishing advice and allow safer second-factor methods without overclaiming company behavior',[
q('Why was the friend’s password weak?', 'It used a name and birth year','It was stored in a manager','It had too many random words','It changed daily','Personal details were easy to guess.'),q('Why use different passwords?', 'One leak should not open every account','They are easier to post publicly','Two-factor login needs one password','Companies ask for all of them','Unique credentials limit damage.'),q('What may provide a second factor?', 'An authenticator, security key, or code','The displayed sender name','An urgent email link','A birth year','More than one safe method exists.'),q('How should an urgent request be checked?', 'Open the official app or site directly','Click its link quickly','Reply with a password','Trust the logo alone','A separate official route avoids a fake link.'),q('What will a legitimate service not request by email?', 'Your full password','Your account name','A public help page','A normal notice','Passwords should never be sent through email.')
],{replaceText:[['This means even if someone guesses my password, they also need a code sent to my own phone.','This adds another check, such as an authenticator app, security key, or one-time code.'],['Real companies rarely ask for your password directly through email. That small fact has saved me twice already.','A legitimate service will not ask for my full password by email. I open its official app or website directly instead of using a message link.']]}),
R('07','revise; keep intentional offline time while preserving emergency access and duties',[
q('What problem did the caller notice?', 'Weekends disappeared into scrolling','The phone was stolen','Parents stopped visiting','Books felt too long','Screen use left little memory of rest.'),q('How is urgent contact preserved?', 'Trusted family can call through emergency settings','The phone has no battery','Every app stays open','Nobody can reach the caller','Offline time should not block real needs.'),q('What activities replaced scrolling?', 'Reading, cooking, and visiting parents','More office work','Shopping for phones','Watching notifications','The alternative activities were present and slow.'),q('What did the mother notice?', 'The caller listened better','The caller arrived late','The meal was faster','Messages increased','Less glancing improved conversation.'),q('Must the break last a whole weekend?', 'No, a few planned hours can help','Yes, exactly two days','No, one minute only','Yes, the phone must be discarded','The advice is flexible and responsible.')
],{replaceText:[['I just turned off my phone from Saturday morning until Sunday evening, once a month.','I plan offline hours once a month, while allowing urgent calls from trusted family and checking any work duty first.'],['Definitely, even just one afternoon. It doesn\'t need to be a whole weekend to make a difference.','A few planned hours may help. Keep emergency contact available and choose a time that does not ignore family or work duties.']]}),
R('08','keep; excellent update procedure uses official verification, backup, power, trusted internet, and enough completion time',[
q('How long was the message delayed?', 'Nearly two weeks','Two hours','One month','One day','The narrator repeatedly pressed later.'),q('Why can an update matter?', 'It may fix security problems','It always adds games','It removes backups','It changes every password','Security is more important than visible features.'),q('How was the source checked?', 'Through the device’s official settings','Through a random message','By calling a stranger','By opening an advertisement','Built-in settings confirmed legitimacy.'),q('What was found on the laptop?', 'Automatic updates were off','The battery was missing','All files were gone','The screen was broken','Another device needed attention too.'),q('Why allow enough time?', 'An update should finish without interruption','It makes internet public','It removes the need for power','It guarantees no future bug','Safe completion is part of the routine.')
]),
R('09','keep; inclusive family-call story addresses roles, rehearsal, older relatives, time limits, and access alternatives',[
q('Why were early calls difficult?', 'People spoke together and had technical trouble','Nobody wanted contact','The family had no devices','Grandmother refused dua','The format needed structure and support.'),q('What did the narrator prepare?', 'A simple call plan','A public photo','A password list','A travel booking','Roles and timing made participation clearer.'),q('How were older relatives helped?', 'A short practice call','A new account for every app','A longer main meeting','Written exams','Rehearsal reduced technical stress.'),q('Why was the main call limited?', 'To keep it manageable','To end family contact','To exclude children','To avoid all updates','A clear length helped attention.'),q('What if video access is difficult?', 'Offer another way to join','Assume everyone has the same access','Remove the person','Share private login details','Technology should not become a barrier.')
]),
R('10','keep; excellent photo-consent dialogue separates taking, posting, child permission, metadata, background details, and public reach',[
q('What is different from taking-photo consent?', 'Permission to post publicly','Permission to attend volunteering','Permission to use a camera','Permission to stand together','Public distribution reaches a wider audience.'),q('Whose image needs special care?', 'A child’s','Only the photographer’s','The empty room’s','The page manager’s','A guardian must approve the child’s image.'),q('What safer image exists?', 'A photo of supplies without faces','A closer child portrait','A tagged home address','An unedited group photo','The alternative tells the story with less privacy risk.'),q('What background detail should be checked?', 'Names, badges, documents, and screens','Only wall color','The weather','Camera brand','Private information may appear accidentally.'),q('Why avoid a location tag?', 'It can reveal where people are','It always lowers quality','The app has no maps','Volunteers requested advertisements','Location can expose more than intended.')
])];
