import { q } from '../helpers.mjs';
const R=(id,decision,additions,extra={})=>({id:`a1-travel-${id}`,level:'A1',scriptDecision:decision,tags:{0:'warmly',2:'thoughtful',4:'honestly',6:'carefully',8:'curious',10:'relieved',12:'reflective',14:'encouraging',17:'warmly',20:'pleasantly'},additions,...extra});
export const reviews=[
R('01','keep; coherent slow-travel reflection contrasts checklist pressure with attentive local experience',[
q('How did old trips leave the narrator?', 'Exhausted','Well rested','Ready for work','Lost without photos','Too many stops created tiredness.'),q('What ruined the original schedule?', 'An airport delay','A stolen bag','A closed hotel','A wrong passport','The delay forced a change of pace.'),q('Where did the narrator go instead of a monument?', 'A small market','Another airport','A mountain trail','A work office','The unplanned local visit became memorable.'),q('What does “curiosity” mean?', 'A desire to learn or notice','A need to hurry','Fear of missing a train','A fixed checklist','The narrator explored without a strict goal.'),q('How are trips planned now?', 'With open time for one place','With more cities each day','Without checking safety','Only around photos','Flexibility supports attention.')
]),
R('02','keep; useful airport-counter dialogue covers documents, luggage, seat, direct flight, gate, and food directions',[
q('What two documents are requested?', 'Passport and booking confirmation','Visa and food receipt','Map and hotel key','Train ticket and ID card','The check-in begins with travel records.'),q('Is the suitcase over the limit?', 'No','Yes, by ten kilograms','The agent does not weigh it','It has no label','The stated weight is accepted.'),q('Why does the traveler prefer an aisle?', 'It is easier to get up','It has a larger window','It is always cheaper','It shortens the flight','The request is practical.'),q('What does “direct” mean?', 'No stop before the destination','A flight with two trains','A seat near the gate','A ticket bought today','The agent confirms the route.'),q('When should the traveler reach the gate?', 'Before boarding time','After the plane leaves','Only after eating','The next morning','Airport instructions require time to board.')
]),
R('03','revise lightly; keep family warmth while adding specific solo-travel safety communication rather than relying only on a friendly hostel owner',[
q('What does Lina do after arriving somewhere?', 'Messages her mother','Posts her room publicly','Turns off her phone','Changes hostels immediately','A check-in confirms safe arrival.'),q('What travel details has she shared privately?', 'Hostel address and next route','Every photo publicly','Her bank password','A stranger’s schedule','Trusted family can follow the plan.'),q('What did Lina buy?', 'A blue scarf','A train map','A phone charger','A water bottle','The color reminded her of her mother.'),q('What health reminder does her mother give?', 'Drink water and rest','Walk all night','Skip unfamiliar food','Avoid every train','Basic care supports the journey.'),q('What will Lina do after the next train?', 'Call when she arrives safely','Wait one week','Meet an unknown driver','Post her live location publicly','The agreed check-in continues.')
],{replaceText:[['I always message you when I arrive somewhere new, remember?','I message you when I arrive, and you have my hostel address and tomorrow’s train details in our private chat.']]}),
R('04','keep; practical packing story uses personal experience to teach lighter, deliberate choices',[
q('What did the father carry?', 'One small bag','Three suitcases','No luggage','A heavy box','His work travel stayed simple.'),q('What happened at age nineteen?', 'The narrator packed too much','The father lost a bag','A flight was canceled','The hotel closed','The first independent trip tested the advice.'),q('How did heavy luggage affect travel?', 'It made moving harder','It improved every choice','It saved time','It made tickets cheaper','Unneeded items became a burden.'),q('What happens before packing now?', 'Each item is questioned','Everything is packed twice','A new suitcase is bought','Clothes are chosen at random','Deliberate selection replaces fear.'),q('Is the final line only about weight?', 'No, it also means fewer unnecessary worries','Yes, it is a luggage rule only','No, it means avoiding travel','Yes, it requires one exact bag','The narrator applies the idea more widely.')
]),
R('05','revise; preserve confidence gained from solo travel while replacing reckless booking advice with preparation, trusted check-ins, and permission to change plans',[
q('Why did Maya stop waiting?', 'Friends were never free at the same time','She disliked all friends','The host bought a ticket','Her work required the trip','Different schedules delayed her plan.'),q('What safety preparation is added?', 'Research, insurance, copies, and check-ins','No plan after booking','Talking to every stranger','Sharing live plans publicly','Solo travel needs more than courage.'),q('Did Maya ever feel lonely?', 'Yes, on some evenings','No, never','Only on the plane','Only after returning','The interview includes a difficult part.'),q('What helped at dinner?', 'Writing in a notebook','Canceling the trip','Calling strangers','Skipping meals','A quiet routine helped her handle the moment.'),q('What is the revised advice?', 'Plan carefully and change course if unsafe','Fear always vanishes on takeoff','Everyone should travel alone','Book before thinking','Capability includes safe decisions.')
],{replaceText:[['One night I got tired of waiting, and I booked a flight before I could talk myself out of it.','I researched the route, chose reviewed accommodation, bought suitable insurance, and then booked the flight.'],['How easy it was to talk to strangers when nobody familiar was around. I made friends at every hostel.','How much planning mattered. I kept document copies, used trusted transport, and checked in with family at agreed times.'],["Completely. You learn how capable you are when there's nobody else to rely on.",'It can suit some adults, but prepare carefully, keep trusted contact, and change plans if a place feels unsafe.'],["I'd say, book the ticket. The fear disappears the moment the plane actually takes off.",'I would say: learn the risks, make a safe plan, and know that coming home early is allowed.']]}),
R('06','revise; keep memorable kindness but add public verification, location sharing, and safe boundaries before following an unfamiliar person',[
q('How did the narrator notice the mistake?', 'An unfamiliar town was announced','A stranger took the ticket','The phone showed a map','The restaurant closed','The train name did not match the plan.'),q('What safe step came first at the station?', 'Confirming directions with staff','Following the man immediately','Leaving luggage behind','Boarding another train at random','Official information should guide the next move.'),q('Why was the restaurant setting safer?', 'It was public, nearby, and open with families','It was hidden and empty','The narrator gave away a passport','Nobody knew the location','Visible public conditions reduced risk.'),q('Who received the narrator’s location?', 'The hotel through a message','Every stranger online','Nobody','The man’s grandchildren only','A trusted contact knew the change of plan.'),q('What is the balanced memory?', 'Kindness was meaningful, but safety checks still mattered','Wrong trains always improve trips','Every stranger should be followed','Travel plans are unnecessary','A good outcome does not remove responsible caution.')
],{replaceText:[['instead of just giving directions, he invited me to his family\'s small restaurant nearby.','he pointed me to station staff first. After they confirmed my next train, he mentioned his family’s busy restaurant across the public square.'],['I hesitated at first, but something about his kindness felt genuine, so I followed him down the street.','I checked that the restaurant was open and full of families, kept my bag with me, and messaged my hotel before walking across the square.'],['Sometimes the wrong train takes you exactly where a trip actually needed you to go.','The wrong train brought unexpected kindness, but checking official information and keeping safe boundaries still mattered.']]}),
R('07','keep; light travel mishap remains realistic and ends with a concrete booking-verification habit',[
q('When did the caller reach the desk?', 'Late at night','Early at breakfast','Before booking','At noon','A long flight had left the caller tired.'),q('Why was no reservation found?', 'The booking was in another city','The email was deleted','The clerk used a wrong name','The hotel was full','Similar hotel names caused the mistake.'),q('Who found a nearby room?', 'The hotel clerk','The radio host','A train driver','The correct hotel','The clerk called other places.'),q('How did the caller travel next morning?', 'By early train','By late flight','On foot for two hours','By private boat','The correct city was two hours away.'),q('What must be checked before confirmation?', 'The city as well as the hotel name','Only the room color','Only breakfast time','The radio schedule','Location prevents a repeated error.')
]),
R('08','keep; strong faith-sensitive station story combines salah, accessibility, timing, signage, and calm return to the platform',[
q('Why did the narrator mark the lift?', 'To find an accessible route back','To store luggage','To buy a ticket','To charge a phone','The route could help another traveler too.'),q('What did staff provide?', 'Directions to the prayer room','A new train','A meal','A hotel room','Asking early saved time.'),q('How much time remained after prayer?', 'Twenty-five minutes','Five minutes','Fifty minutes','One hour','There was still time to return calmly.'),q('What was checked on return?', 'The electronic board','A restaurant list','A hotel email','The weather only','Updated platform information matters.'),q('What two things worked together?', 'Prayer and careful travel planning','Speed and panic','Guessing and rushing','Photos and shopping','Faith practice fit safely inside the journey.')
]),
R('09','keep; phone-failure story responsibly uses a paper map, meeting point, memory, and later charging rather than romanticizing being unreachable',[
q('What was left at home?', 'The charging cable','The paper map','The wallet','The train ticket','The phone battery could not be restored immediately.'),q('Who provided useful help?', 'A station worker','A hotel manager','A radio caller','A mountain guide','A paper map and key places supported the day.'),q('How did the narrator avoid getting lost?', 'Used the map and fixed meeting points','Followed strangers','Walked without directions','Posted a live location','Offline navigation was still planned.'),q('What became easier to remember?', 'Faces and sounds','App notifications','Photo filters','Charging times','Attention shifted away from the camera.'),q('Did the narrator remain unreachable forever?', 'No, the phone was charged later','Yes, for the whole trip','No, a new phone was bought immediately','Yes, by choice','The story values attention without rejecting useful technology.')
]),
R('10','keep; excellent professional hiking decision uses weather closure, beginner ability, group rules, emergency access, and clear explanation',[
q('Who closed the long trail?', 'Park authorities','Ihsan alone','The beginners','A hotel clerk','The closure follows official safety information.'),q('Why is the shorter route chosen?', 'It is open and suitable for the group','It reaches a higher summit','It avoids every rest stop','It has no guide rules','Conditions and group ability guide the decision.'),q('What must happen at path crossings?', 'The group waits and counts people','Everyone chooses a route','Beginners walk alone','The guide turns back','Group control prevents separation.'),q('What emergency support remains available?', 'A known route and guide plan','Only a social photo','A stranger’s advice','No communication','The guide retains safety structure.'),q('What does Ihsan accept?', 'A responsible change over the original goal','Breaking the trail closure','Leaving beginners behind','Hiding information','Clear reasons make the change understandable.')
])];
