import { q } from '../helpers.mjs';
const R=(id,decision,additions,extra={})=>({id:`a1-work-${id}`,level:'A1',scriptDecision:decision,tags:{0:'warmly',2:'honestly',4:'thoughtful',6:'carefully',8:'reflective',10:'practically',12:'calmly',14:'encouraging',17:'warmly',20:'pleasantly'},additions,...extra});
export const reviews=[
R('01','revise lightly; retain first-job growth while acknowledging income matters and avoiding an absolute conclusion',[
q('Where was the first job?', 'At a small shop near home','At a large airport','At a hospital','At a radio station','The narrator began work at age twenty.'),q('What mistake happened first?', 'The wrong change was given','A shelf fell','A report was late','A phone was stolen','The manager responded to a common new-worker error.'),q('How did the manager respond?', 'Calmly and with teaching','By shouting publicly','By ending the job','By ignoring the customer','The response allowed learning.'),q('How does the narrator train people now?', 'With patience remembered from the first job','By leaving them alone','With no feedback','By expecting perfection','Earlier treatment shapes current leadership.'),q('What is the balanced final lesson?', 'Work can provide income and teach character','Money never matters','Every hard job is good','Mistakes have no effect','The revision respects both livelihood and growth.')
],{replaceText:[["A first job is never really about the money. It's about learning who you become when things get difficult.",'Income matters, and a first job can also teach how we respond when work becomes difficult.']]}),
R('02','keep; career-change podcast includes gradual study, portfolio work, family financial concern, and practical testing before leaving',[
q('How old was Maya when changing career?', 'Thirty','Twenty','Forty','Eighteen','The title and introduction give her age.'),q('What sign showed she needed change?', 'She dreaded returning to the desk','Her parents chose design','The office closed','Her husband lost work','A Monday realization made dissatisfaction clear.'),q('How did she begin learning?', 'With courses beside her current job','By resigning immediately','By buying a company','Without practice','The change began gradually.'),q('Why were her parents worried?', 'Money and risk','The design colors','Her husband’s opinion','The podcast length','Their concern focused on stability.'),q('What does Maya recommend first?', 'Test the new path before a full move','Quit tomorrow','Ignore finances','Expect instant success','Small trials provide evidence and reduce risk.')
]),
R('03','keep; practical coworker dialogue supports early workload communication, priority-setting, meals, and teamwork',[
q('How late did Dewi work?', 'Until nine','Until noon','Until seven in the morning','She left early','Long hours still did not finish the report.'),q('Why was Dewi silent?', 'She feared looking unable to cope','The manager was away','No deadlines existed','Fajar asked her not to speak','Image concerns delayed useful communication.'),q('What did Fajar ask the manager?', 'Which task mattered most','For a new job','To cancel every project','For a longer lunch only','Priority was clearer than vague complaint.'),q('What basic need had Dewi missed?', 'A proper lunch','A full week of sleep','A train home','A medical visit','Four days without proper lunch added to fatigue.'),q('What is their next sequence?', 'Eat, prepare, then speak to the manager','Work alone all night','Complain publicly','Ignore all deadlines','Support leads to a concrete conversation.')
]),
R('04','keep; strong feedback story distinguishes specific respectful correction from silence or personal attack',[
q('How did Pak Hendra usually speak?', 'Quietly','By shouting','Only by email','Through other workers','His calm style made words memorable.'),q('What happened after the big project?', 'He gave honest detailed feedback','He offered only praise','He canceled the project','He said nothing','Specific review supported growth.'),q('Why did he give correction?', 'He believed the narrator could improve','He disliked the narrator','He wanted public attention','He had no other tasks','Expectation was framed as respect.'),q('What happened without honest feedback?', 'A coworker repeated problems','Every task improved','The manager became clearer','The team needed no review','Silence can block learning.'),q('How does the narrator now give feedback?', 'Clearly, kindly, and specifically','With personal insults','Only after failure','Without examples','The learned method combines truth and dignity.')
]),
R('05','keep; realistic recruiter call supports questions, notice obligations, written terms, and time before a decision',[
q('Who calls Rafi?', 'Recruiter Nina','His manager','A customer','A radio host','She represents the company interviewed with.'),q('What start date is discussed?', 'A date after his notice period','The same afternoon','One year later','Before the interview','Rafi must finish current responsibilities.'),q('Why is three weeks conditional?', 'He needs to confirm his notice requirement','He needs a passport','The team has no manager','The salary is unknown forever','Existing employment terms matter.'),q('What team information does he ask?', 'Manager and coworkers','Restaurant menu','Train schedule','Family address','He wants to understand reporting structure.'),q('What must arrive before acceptance?', 'A written offer with details','A public announcement','A new laptop','A verbal promise only','Written terms allow a careful decision.')
]),
R('06','keep with softer timing; personal recovery method separates one error from overall ability and chooses a controllable next step',[
q('What happened during the presentation?', 'The narrator’s mind went blank','The manager left','The laptop was stolen','The meeting was canceled','A public mistake triggered embarrassment.'),q('What did the friend separate?', 'One bad hour from the whole day','Work from income','Lunch from dinner','Email from reports','The event did not need to define everything.'),q('What question follows the emotion?', 'What small thing can I control now?','Who should I blame?','How can I hide it?','Why work again?','The method turns toward action.'),q('Which small action is mentioned?', 'Send one clear email or walk briefly','Quit immediately','Repeat the presentation all night','Ignore the mistake','A manageable response restores direction.'),q('What does one error not erase?', 'Months of good work','The need to correct it','The whole presentation','A manager’s feedback','Ability is not reduced to one moment.')
],{replaceText:[['I give myself exactly ten minutes to feel upset.','I often give myself about ten quiet minutes to feel upset, though another person may need a different healthy pause.']]}),
R('07','revise; prevent self-diagnosis and clarify that leave is a pause, with manager support and professional health advice if symptoms continue',[
q('How long had overtime continued?', 'Almost six months','Two days','One week','Several years','The long pattern came before the crisis.'),q('What did the caller feel at the desk?', 'Empty and unable to focus','Excited and energetic','Hungry only','Ready for more overtime','The symptoms went beyond ordinary tiredness.'),q('Who did the caller speak with?', 'The manager','Only the radio audience','A customer','Nobody','Workplace communication led to time off.'),q('Did two days solve everything?', 'No, they were only a pause','Yes, completely','No, they made it worse','Yes, the job ended','The caller says longer changes were needed.'),q('What should happen if symptoms continue?', 'Seek qualified health support','Diagnose from a radio story','Work more hours','Hide all signs','The revision adds an important safety boundary.')
],{replaceText:[['Did you recognize that feeling as burnout right away?','Did you know what the continuing tiredness and poor focus meant?'],['Not at first. I thought I just needed one good night of sleep, but the feeling didn\'t go away.','No. I avoided diagnosing myself and later arranged appropriate health support when the symptoms continued.'],['Just a pause, really. But it gave me enough energy to start setting real limits on my working hours now.','Just a pause. I also discussed workload changes and knew I should seek qualified health care if the symptoms continued or became severe.']]}),
R('08','keep; excellent handover story covers owner, status, deadline, next step, contacts, data boundaries, peer review, and genuine leave',[
q('Why was conversation alone insufficient?', 'Details could be forgotten while the narrator was away','The team never spoke','The manager disliked notes','All tasks were finished','A shared room did not guarantee shared knowledge.'),q('What did every task entry identify?', 'Status, deadline, next action, and contact','Private passwords','Only the title','Personal health data','The note focused on needed operational facts.'),q('Why exclude sensitive information?', 'The handover should not expose private data','The team needed no access','The note was public advertising','Deadlines were secret','Useful sharing still follows data boundaries.'),q('What mistake did Laila catch?', 'Monday was written as Tuesday','A supplier name was missing','Leave lasted four days','The customer had no order','Peer review protected the deadline.'),q('How did the note protect rest?', 'Coworkers could act without contacting the person on leave','It canceled every task','It removed the manager','It extended leave forever','Good preparation reduces interruption.')
]),
R('09','keep; realistic estimation lesson replaces confidence theater with task breakdown, review time, uncertainty, and early communication',[
q('What image did the narrator want to show?', 'Fast and confident','Careful and uncertain','Tired and confused','Quiet and unavailable','The quick promise was meant to impress.'),q('What hidden work was missed?', 'Checking data and reviewing writing','Buying equipment','Calling customers','Traveling to a supplier','The first estimate ignored task parts.'),q('When should a likely delay be communicated?', 'As early as possible','After the deadline passes','Only when a manager asks','After hiding the problem','Early notice protects planning and trust.'),q('How was the new estimate built?', 'One day for data and half a day for writing and review','A random guess','The fastest possible answer','Another worker’s promise','Breaking down work improved realism.'),q('Why check before making a promise?', 'The deadline can match the real work','It guarantees no mistake','It removes all uncertainty','It makes every task faster','A reliable answer comes from understanding the task.')
]),
R('10','keep; inclusive scheduling dialogue considers care duties, time zones, async updates, agenda length, private feedback, trial, and review',[
q('What personal duty affects Sari?', 'Taking a parent to an appointment','A weekly flight','Teaching a night class','Cooking team lunch','Wednesday timing clashes with care.'),q('Who else struggles with the time?', 'A colleague in another time zone','Only the manager','Every customer','Nobody','The issue affects more than one person.'),q('What may replace some live topics?', 'Written updates','Longer meetings','Private photos','Extra calls','Not every item needs real-time discussion.'),q('Why allow private comments?', 'Some constraints may be personal','To hide the meeting time','To exclude colleagues','To avoid all feedback','People may not want to explain needs publicly.'),q('What follows four trial meetings?', 'Review attendance and adjust','Make the time permanent','Cancel the team','Add more topics','The schedule remains testable and responsive.')
])];
