import { q } from '../helpers.mjs';

export const reviews = [
  {
    id: 'a2-akhlak-01', level: 'A2', scriptDecision: 'revise; replace an unsafe private meeting with official lost-property handling and identity verification',
    replaceText: [
      ['I got off at the next station and called the number on one of his cards; when he answered, his voice sounded tired, almost hopeless.', 'I took the wallet to the station service desk and asked them to record it as lost property. Staff used the ID to contact its owner.'],
      ['When I explained that I had found his wallet, he went completely silent for a moment, then almost started crying with relief.', 'While I waited, staff checked the wallet contents with me as a witness so there would be a clear record.'],
      ['He told me that money was meant for his mother\'s medicine, and losing it that morning had frightened him more than anything else that week.', 'When the owner arrived, he confirmed his identity and described the wallet before staff returned it. He said the cash was for an urgent family expense.'],
      ['We met near a small coffee shop close to the station, and when I handed him the wallet, he tried to give me some money as thanks.', 'He thanked me at the public service desk and offered a small reward.'],
      ['Tomorrow I will apologize to my manager for being late', 'Tomorrow I will explain the documented delay to my manager'],
    ],
    tags: { 0: 'thoughtful', 2: 'tempted', 3: 'honestly', 4: 'determined', 5: 'carefully', 7: 'relieved', 8: 'gratefully', 10: 'concerned', 12: 'peacefully' },
    baseQuiz: [
      q('Where was the wallet found?', 'On an empty train seat', 'Inside a coffee shop', 'At the service desk', 'Under the narrator’s office chair', 'It remained beside the narrator until the next stop.'),
      q('What temptation did the narrator experience?', 'Keeping the cash and leaving the wallet', 'Using the bank cards', 'Calling the family photo shop', 'Giving the wallet to another passenger', 'The narrator honestly describes a brief dishonest thought.'),
      q('Where did the narrator take the wallet?', 'The station service desk', 'A private restaurant', 'The owner’s home', 'The narrator’s workplace', 'Official lost-property handling reduced risk for both sides.'),
      q('How was the owner verified?', 'He showed identity and described the wallet', 'He only stated the cash amount online', 'The narrator recognized his voice', 'He brought a family member', 'Staff checked that the claimant was the rightful owner.'),
      q('What cost did the narrator’s decision have?', 'An important meeting was missed', 'The wallet cash was lost', 'The train service stopped', 'The manager ended the job', 'Returning the property responsibly took extra time.'),
    ],
    additions: [
      q('Why did staff record the contents?', 'To create a clear account of what was handed in', 'To decide who could keep the cash', 'To publish the owner’s information', 'To charge a lost-property fee', 'A documented handover protects the finder, staff, and owner.'),
      q('What made the family photo morally important to the narrator?', 'It helped her imagine the owner as a worried person', 'It proved the cash amount', 'It contained the station address', 'It gave permission to open the wallet', 'Empathy interrupted the temptation to keep the money.'),
      q('Why was the official desk safer than a private meeting?', 'Identity and transfer could be verified publicly', 'The owner could not thank the narrator', 'The train would wait longer', 'Cash is never allowed in a station', 'The revision avoids arranging a meeting with an unknown person.'),
      q('Does refusing the reward mean every reward is forbidden?', 'No, it describes the narrator’s personal choice', 'Yes, the script gives a legal rule', 'No, because the owner withdrew it', 'Yes, station staff demanded refusal', 'The narrator explains motivation, not a universal ruling.'),
      q('What does the narrator still owe the manager?', 'An honest explanation of the documented delay', 'A false excuse about the train', 'The owner’s private information', 'Part of the recovered cash', 'Good character toward one person does not remove responsibility to another.'),
    ],
  },
  {
    id: 'a2-akhlak-02', level: 'A2', scriptDecision: 'revise; add medical assessment and caregiver support so patience does not replace appropriate care',
    replaceText: [['Once I stopped expecting him to be who he used to be, caring for him became less exhausting and much more peaceful.', 'After a medical assessment, our family learned practical ways to support him. I also take breaks and ask my sister for help before I become overwhelmed.'], ['I would say patience isn\'t a feeling that simply appears. It\'s a choice you make again, quietly, every time you feel your temper rising.', 'I would say patience includes a calm response, suitable medical guidance, and asking for caregiver support before anger grows.']],
    tags: { 0: 'warmly', 3: 'thoughtful', 5: 'honestly', 7: 'regretfully', 9: 'reflective', 11: 'calmly', 13: 'carefully', 15: 'encouraging', 17: 'warmly' },
    additions: [
      q('Why did Aldi’s early expectation create frustration?', 'He expected his father’s memory to work as before', 'His father refused every meal', 'His sister denied the changes', 'The doctor gave no information', 'The expectation did not match his father’s changing ability.'),
      q('What does the sister’s reminder change?', 'It separates a symptom from intentional behavior', 'It proves repeated questions are easy', 'It makes medical assessment unnecessary', 'It gives Aldi control over memory loss', 'Recognizing that forgetting is not a choice reduces blame.'),
      q('What new support appears in the revised script?', 'Medical guidance and shared caregiver breaks', 'A promise never to feel tired', 'A strict rule to answer alone', 'A public discussion of private details', 'Patience is supported by care systems, not only willpower.'),
      q('Why should Aldi ask for help before becoming overwhelmed?', 'Rest can reduce the risk of an angry response', 'His father needs fewer family members', 'Caregivers should never answer questions', 'His sister caused the memory problem', 'Caregiver limits matter for the safety and dignity of everyone.'),
      q('What is the interview careful not to claim?', 'That calmness alone treats memory changes', 'That repeated questions occur', 'That families may struggle', 'That Aldi once raised his voice', 'The revision places emotional patience beside professional assessment.'),
    ],
  },
  {
    id: 'a2-akhlak-03', level: 'A2', scriptDecision: 'revise; keep compassion for family illness while adding written business repair, realistic dates, and accountability',
    replaceText: [['Family comes before business, Bagas. If your father was sick, that money was exactly where it needed to be.', 'I understand why you used your own savings for your father. But our business still needs a clear revised plan because I made commitments based on your promise.'], ['I\'ll send what I can by next week, and the rest once my father recovers and I\'m working again properly.', 'I can confirm a safe amount by Friday. Then we should write a revised schedule based on my actual finances, not on when my father recovers.'], ['Take the time you need. Just promise you\'ll talk to me next time', 'Let us review the supplier debt and put the new agreement in writing. And please talk to me early next time']],
    tags: { 0: 'tense', 1: 'nervous', 3: 'ashamed', 5: 'honestly', 6: 'softening', 8: 'hurt', 10: 'compassionately', 12: 'firmly', 13: 'carefully', 15: 'sincerely', 16: 'hopeful' },
    additions: [
      q('What practical harm did the silence cause Farah?', 'She borrowed money to pay the supplier', 'She closed the shop immediately', 'She paid the hospital bill', 'She lost contact with her brother', 'Farah made an expensive adjustment without information.'),
      q('Why is Farah’s revised response both kind and responsible?', 'She respects the family need but still requires a business plan', 'She cancels the entire debt', 'She ignores the supplier commitment', 'She demands money during the call', 'Compassion does not erase commitments made to the shop.'),
      q('Why should repayment not depend on the father’s recovery?', 'Recovery time is uncertain and should not become a financial promise', 'The father caused the partnership problem', 'Hospital care always ends by Friday', 'Farah controls the recovery date', 'A responsible schedule uses finances that can actually be checked.'),
      q('What does putting the agreement in writing achieve?', 'It creates shared expectations that both partners can review', 'It publicly exposes the father’s illness', 'It guarantees the shop will succeed', 'It removes the need for future communication', 'A written repair makes dates and responsibilities clear.'),
      q('What must accompany Farah’s forgiveness?', 'Earlier honesty and reliable follow-through', 'No further discussion of money', 'A promise that hardship will not return', 'Ending the partnership immediately', 'Trust can continue, but it needs changed behavior and accountability.'),
    ],
  },
  {
    id: 'a2-akhlak-04', level: 'A2', scriptDecision: 'keep; thoughtful humility story gives appropriate credit without denying real personal effort',
    tags: { 0: 'reflective', 1: 'uneasy', 3: 'quietly', 4: 'defensive', 6: 'thoughtful', 8: 'humbly', 9: 'determined', 10: 'warmly', 12: 'cautiously', 14: 'peacefully', 15: 'smiling' },
    additions: [
      q('What showed that pride was becoming unhealthy?', 'The narrator mentioned the award without being asked', 'The award remained on the desk', 'The team attended the ceremony', 'Dedi congratulated the narrator', 'Repeated self-promotion made the change visible.'),
      q('Why was Dedi’s comment difficult to accept?', 'It challenged the narrator’s preferred self-image', 'It denied that the award existed', 'It came from a stranger', 'It accused the whole team', 'Embarrassment and defensiveness came before reflection.'),
      q('Which factors existed beside the narrator’s hard work?', 'Team support, opportunity, timing, and circumstance', 'Only luck with no effort', 'A mistake by another branch', 'A promise from the manager', 'The story presents achievement as real but not isolated.'),
      q('Why had coworkers been waiting for thanks?', 'Public praise had not yet included their contribution', 'They wanted the physical award', 'They had not heard about the ceremony', 'Dedi asked them to complain', 'Recognition felt incomplete until the team was acknowledged.'),
      q('How did the meaning of the award change?', 'It became a reminder of shared effort', 'It became proof that pride is necessary', 'It lost all value', 'It was hidden from the office', 'Humility changes interpretation without pretending the success did not matter.'),
    ],
  },
  {
    id: 'a2-akhlak-05', level: 'A2', scriptDecision: 'keep; emotionally realistic workplace story delays anger, gathers evidence, corrects the record, and protects dignity',
    tags: { 0: 'concerned', 1: 'tense', 3: 'frustrated', 5: 'angry', 7: 'remembering', 9: 'calmly', 11: 'firmly', 13: 'relieved', 15: 'reflective', 17: 'grateful' },
    additions: [
      q('What physical sign showed Yoga’s anger?', 'His face felt hot and his hands shook', 'He lost his voice completely', 'He left the room', 'He tore the written notes', 'The script shows self-control despite a strong body response.'),
      q('Why did writing help during the meeting?', 'It stored his points without releasing them as anger', 'It proved the director was correct', 'It informed the entire company', 'It replaced the supporting emails', 'Notes created time between emotion and response.'),
      q('What made Yoga’s private explanation persuasive?', 'A calm timeline supported by emails', 'A louder version of the complaint', 'Agreement from every coworker', 'The director’s earlier apology', 'Evidence shifted the discussion from blame to facts.'),
      q('Why will the director clarify the issue publicly?', 'The original blame created a public false impression', 'Yoga requested public praise', 'The supplier joined the meeting', 'Private correction is always insufficient', 'The record needs repair in front of the group that heard the error.'),
      q('What does the story suggest about silence?', 'Temporary silence can prepare a better response, not surrender the truth', 'Silence always means agreement', 'Unfair criticism should never be corrected', 'Evidence matters only in private', 'Yoga delays the response but still addresses the injustice.'),
    ],
  },
  {
    id: 'a2-akhlak-06', level: 'A2', title: 'A Family Dinner Story About a Promise Repaired', scriptDecision: 'replace; remove an unsafe four-hour drive and an impossible “no matter what” promise while teaching reliable repair',
    replaceScript: [
      'Nabila: [concerned] Ayah, thank you for helping with my school book last night. I know you were already away for work.',
      'Ayah: You called because the book was at Aunt Hana’s house and you needed two pages for today’s class.',
      'Nabila: I thought you would drive back for it because you once promised to bring anything I needed for school.',
      'Ayah: [carefully] That promise was too wide. Driving four extra hours while tired would not have been a safe or wise solution.',
      'Nabila: Were you worried I would think you had broken your word?',
      'Ayah: Yes. But keeping trust does not mean choosing a dangerous action just to follow my exact old sentence.',
      'Nabila: [curious] So what did you do instead?',
      'Ayah: I called Aunt Hana. With your teacher’s permission, she photographed the two pages and sent them privately to us.',
      'Nabila: Then you called me and explained that the book could be collected safely after your trip.',
      'Ayah: [warmly] Exactly. I still helped with the real need, but I changed the unsafe method.',
      'Nabila: Why did you apologize? The pages arrived in time.',
      'Ayah: Because I had made a promise that sounded unlimited. A trustworthy person should not promise what health, safety, or circumstances may prevent.',
      'Nabila: [thoughtful] What would have happened if Aunt Hana could not send the pages?',
      'Ayah: We would have told the teacher honestly and asked for another reasonable solution. We would not invent an excuse.',
      'Nabila: So a repaired promise can still protect trust?',
      'Ayah: [gently] Yes, when we communicate early, explain the limit, and do what is safely possible.',
      'Nabila: I also need to take responsibility. I left the book there and only noticed at night.',
      'Ayah: That is true. Tonight, let us make a short school-bag checklist together.',
      'Nabila: [determined] I will check it before bed instead of depending on an emergency rescue.',
      'Ayah: Good. Trust grows when both people speak honestly, plan carefully, and repair mistakes without creating a new danger.'
    ],
    tags: { 0: 'concerned', 3: 'carefully', 6: 'curious', 9: 'warmly', 12: 'thoughtful', 15: 'gently', 18: 'determined' },
    baseQuiz: [
      q('Where was Nabila’s school book?', 'At Aunt Hana’s house', 'In Ayah’s car', 'At the school office', 'Inside the work hotel', 'She needed only two pages from the forgotten book.'),
      q('Why did Ayah refuse to drive back?', 'Four extra tired hours would be unsafe', 'He did not care about school', 'The road was permanently closed', 'Nabila had found the book', 'Safety placed a reasonable limit on the old promise.'),
      q('How did they receive the needed pages?', 'Aunt Hana sent private photos with teacher permission', 'Ayah posted the whole book publicly', 'Nabila bought another book', 'The teacher canceled class', 'They found a lawful, private, and practical alternative.'),
      q('Why did Ayah still apologize?', 'His original promise was unrealistically unlimited', 'The photos arrived too early', 'Aunt Hana refused to help', 'Nabila had made no mistake', 'He takes responsibility for careless wording.'),
      q('What will Nabila use in the future?', 'A school-bag checklist before bed', 'A promise of another long drive', 'A public photo folder', 'Her teacher’s private number', 'Planning reduces avoidable emergencies.'),
    ],
    additions: [
      q('What is the difference between the need and the method?', 'Nabila needed pages, but Ayah did not need to drive dangerously', 'The book and pages had no connection', 'The teacher required the original book', 'The method mattered more than school', 'A promise can honor its purpose through a safer solution.'),
      q('What would they do if the photos were impossible?', 'Tell the teacher honestly and request another solution', 'Invent a transport problem', 'Drive despite exhaustion', 'Hide the missing work', 'Trustworthy repair includes honest limits.'),
      q('Why was the page sharing kept private?', 'School material and messages should go only to the people who need them', 'The pages were embarrassing', 'Aunt Hana wanted payment', 'The teacher banned all photos', 'The script models limited, permission-based sharing.'),
      q('How does Nabila share responsibility?', 'She admits forgetting and begins a preparation habit', 'She blames Ayah’s work trip', 'She demands a stronger promise', 'She asks the teacher to pack for her', 'Repair is stronger when both sides address their part.'),
      q('What is the mature lesson about promises?', 'Reliability includes safety, early communication, and realistic repair', 'Exact words must be followed at any cost', 'A changed plan always breaks trust', 'Parents must solve every forgotten item', 'Good character avoids creating a second harm while addressing the first problem.'),
    ],
  },
  {
    id: 'a2-akhlak-07', level: 'A2', scriptDecision: 'keep; strong gossip scenario replaces uncertain claims with a direct, fair question about a real decision',
    tags: { 0: 'thoughtful', 1: 'uneasy', 3: 'tempted', 4: 'reflective', 5: 'firmly', 6: 'determined', 7: 'relieved', 9: 'honestly', 11: 'gently', 13: 'peacefully' },
    additions: [
      q('Why was the promotion claim unreliable?', 'The coworkers spoke with certainty but had no evidence', 'Rina denied being manager', 'The director announced another reason', 'The narrator knew it was true', 'Confidence in a statement does not replace evidence.'),
      q('How did the narrator respond without defending Rina blindly?', 'She admitted she lacked enough information to judge fairly', 'She claimed every decision was correct', 'She reported both coworkers immediately', 'She left without saying anything', 'The response rejects gossip without pretending to know the truth.'),
      q('Why was one direct question more useful than lunch gossip?', 'Rina could explain the decision and its context', 'It proved the promotion process', 'It made every coworker agree', 'It kept Rina unaware of confusion', 'The real source could address the actual work issue.'),
      q('What does “words travel faster than truth” mean?', 'Rumors spread before accurate information is checked', 'Truth is always difficult to say', 'Messages move slowly at work', 'Every repeated story becomes correct', 'Repetition can change and strengthen an unverified claim.'),
      q('What quiet success does the narrator value?', 'Choosing fairness although nobody will praise it', 'Learning the director’s private life', 'Winning the lunch discussion', 'Proving Rina deserved promotion', 'Character is shown through a choice that may remain unnoticed.'),
    ],
  },
  {
    id: 'a2-akhlak-08', level: 'A2', scriptDecision: 'keep; excellent credit-sharing case distinguishes technically true words from a misleading public impression',
    tags: { 0: 'warmly', 1: 'uneasy', 3: 'honestly', 4: 'reflective', 5: 'gently', 7: 'relieved', 8: 'hurt', 9: 'thoughtful', 11: 'firmly', 13: 'prepared', 14: 'encouraging' },
    additions: [
      q('Why did the praise become uncomfortable?', 'It made the narrator’s contribution sound complete when it was not', 'The guide contained no useful work', 'Bayu had rejected the diagram', 'The manager criticized the examples', 'Silence allowed an inaccurate impression.'),
      q('Why would private thanks fail to repair the issue?', 'The team had received the misleading impression publicly', 'Bayu worked from home', 'The manager disliked private messages', 'The document was unfinished', 'Correction needs to reach the same audience as the misunderstanding.'),
      q('How did the narrator avoid false self-denial?', 'The message named Bayu’s work without denying her own leadership', 'She transferred the whole project to Bayu', 'She rejected all manager feedback', 'She claimed to have done nothing', 'Accurate credit can include several real contributions.'),
      q('What later behavior shows trust increased?', 'Bayu shared ideas more freely in the next project', 'Bayu stopped working remotely', 'The manager gave another award', 'The team removed the narrator’s name', 'Fair recognition changed future collaboration.'),
      q('What preventive habit does the narrator adopt?', 'Preparing a sentence that names key contributions', 'Waiting for absent people to complain', 'Avoiding group presentations', 'Thanking everyone with no details', 'Planned credit reduces accidental omission.'),
    ],
  },
  {
    id: 'a2-akhlak-09', level: 'A2', scriptDecision: 'keep; nuanced pharmacy story uses overheard context to correct impatience without demanding private medical details',
    tags: { 0: 'tired', 2: 'impatient', 4: 'surprised', 5: 'seriously', 6: 'concerned', 8: 'reflective', 10: 'calmly', 11: 'resigned', 13: 'gently', 14: 'encouraging' },
    additions: [
      q('What assumption did the complaining woman make?', 'The man was unprepared and wasting time', 'The pharmacist had closed the counter', 'The narrator needed different medicine', 'The bus had already left', 'She judged the delay before knowing its purpose.'),
      q('Why was the slow service medically important?', 'It prevented two medicines from being used together', 'It reduced the medicine price', 'It allowed the man to make a call', 'It changed the father’s hospital', 'Careful checking protected the patient from a serious error.'),
      q('What contradiction does the narrator identify?', 'He wanted careful service for family but speed for strangers', 'He disliked queues but arrived early', 'He needed a bus but chose to walk', 'He trusted the pharmacist but not medicine', 'Personal needs exposed an unfair double standard.'),
      q('Did patience remove the practical cost?', 'No, the narrator still missed the bus', 'Yes, the line moved immediately', 'No, the medicine was unavailable', 'Yes, another pharmacist arrived', 'Patience changed behavior, not the waiting time.'),
      q('What information does the narrator avoid demanding?', 'The full private details behind another customer’s delay', 'The location of the bus stop', 'The dose for his mother', 'The order of the queue', 'The lesson allows uncertainty without invading privacy.'),
    ],
  },
  {
    id: 'a2-akhlak-10', level: 'A2', scriptDecision: 'keep; strong promise-repair dialogue rejects unhealthy overwork and builds a specific, reviewable alternative',
    tags: { 0: 'worried', 2: 'panicked', 4: 'reflective', 6: 'desperate', 7: 'firmly', 9: 'thoughtful', 11: 'practically', 13: 'gently', 15: 'carefully', 17: 'honestly', 19: 'encouraging' },
    additions: [
      q('What social pressure affected Fikri’s estimate?', 'Everyone expected an immediate helpful answer', 'The organizer threatened him', 'Hasan promised the work first', 'The meeting had no schedule', 'Fikri agreed before checking actual capacity.'),
      q('Why are two sleepless nights a poor repair?', 'They risk health, paid work, and poster quality', 'They provide too much calendar time', 'The organizer asked for templates', 'The fonts are already complete', 'Fixing one promise should not create several new problems.'),
      q('What makes Hasan’s proposal more than an excuse?', 'It includes finished work, reusable templates, and dated follow-up', 'It asks the organizer to wait without details', 'It transfers all work secretly', 'It promises twelve posters again', 'The alternative gives immediate value and a realistic path.'),
      q('Why must the organizer agree before another volunteer adapts files?', 'The changed responsibility and method need consent', 'Volunteers cannot use templates', 'Fikri owns the community center', 'Hasan needs public credit', 'A repair plan cannot be imposed on the person depending on the promise.'),
      q('What restores trust after the poor estimate?', 'Early honesty plus a schedule that matches real capacity', 'A vague message after Friday', 'Staying silent until all work is done', 'Making a larger promise', 'Reliable repair begins before the delay becomes a surprise.'),
    ],
  },
];
