import { q } from '../helpers.mjs';

export const reviews = [
  {
    id: 'a2-daily-01', level: 'A2', speakers: [{ name: 'Nisa', gender: 'female' }, { name: 'Rina', gender: 'female' }], scriptDecision: 'revise; make the travel companions unambiguously same-gender while retaining realistic planning, backups, cost sharing, and rest',
    replaceText: [['Yusuf:', 'Nisa:']],
    tags: { 0: 'excited', 2: 'practical', 3: 'sleepily', 5: 'thoughtful', 8: 'carefully', 10: 'curious', 12: 'pleased', 15: 'organized', 17: 'tired', 19: 'laughing' },
    additions: [
      q('Why do Nisa and Rina need to wake at 5:30?', 'They need time to reach the 7:00 train', 'They plan to visit the market first', 'The hotel opens before sunrise', 'They want to cook breakfast on the train', 'The early wake-up supports travel to the station before departure.'),
      q('What does the printed confirmation protect against?', 'A dead phone causing check-in difficulty', 'The hotel changing its location', 'The train food being expensive', 'Rain at the market', 'A paper backup keeps key booking information accessible.'),
      q('How does their Sunday plan differ from Saturday?', 'It is quieter and leaves time to reach the station', 'It includes more crowded attractions', 'It begins with another early train', 'It has every hour scheduled', 'They expect fatigue and deliberately reduce activity.'),
      q('Why will Nisa wait for the final receipt?', 'To send Rina an exact share of the hotel cost', 'To change the train tickets', 'To reserve the old market', 'To calculate the snack price', 'The receipt makes shared expenses transparent.'),
      q('What tension appears in their planning style?', 'They want structure but also enough space to relax', 'They disagree about whether to travel', 'They want to pack heavy luggage', 'They refuse to plan any activity', 'The ending recognizes that overplanning can reduce the rest they need.'),
    ],
  },
  {
    id: 'a2-daily-02', level: 'A2', scriptDecision: 'revise lightly; preserve the beginner cooking arc while restoring recipe and food-safety importance',
    replaceText: [['seasoning matters more than expensive ingredients, and that patience usually matters more than following a recipe exactly', 'basic seasoning and patient practice matter more than expensive ingredients, while food-safety steps and important recipe measurements still need care'], ['start with something small and forgivable', 'start with a simple recipe, read the safety steps first, and allow yourself to learn']],
    tags: { 0: 'honestly', 2: 'amused', 3: 'determined', 4: 'proud', 6: 'laughing', 7: 'pleased', 8: 'practical', 10: 'warmly', 12: 'reflective', 14: 'encouraging' },
    additions: [
      q('What financial pattern motivated the narrator?', 'Takeout consumed too much of the salary', 'Kitchen equipment was too expensive', 'Friends expected free meals', 'Recipes required paid videos', 'Cooking began as a response to repeated food spending.'),
      q('Why was the second soup important?', 'It proved improvement was possible after a failed attempt', 'It was served to many guests', 'It exactly copied a restaurant meal', 'It used expensive ingredients', 'A small success made continued practice feel worthwhile.'),
      q('What does the weekend rule provide?', 'Regular practice with permission to make mistakes', 'A requirement to cook every meal', 'A reason to ignore safety steps', 'A promise that every dish succeeds', 'One new dish a week creates manageable repetition.'),
      q('Which part of a recipe should not be treated casually?', 'Food-safety instructions and important measurements', 'The price of ingredients', 'The narrator’s grandmother’s handwriting', 'The number of friends invited', 'Creative learning still needs safe handling and reliable proportions.'),
      q('Why does cooking now help after work?', 'Slow physical tasks give the mind a calmer focus', 'Every meal saves the same amount', 'The kitchen removes all stress', 'Friends always visit afterward', 'Chopping and preparing replace passive phone scrolling with focused activity.'),
    ],
  },
  {
    id: 'a2-daily-03', level: 'A2', scriptDecision: 'revise; strengthen a repeated-heater response with urgent safety assessment and unconditional tenant rights',
    replaceText: [['Just use extra blankets tonight, and I promise this gets fixed quickly tomorrow.', 'Do not touch the unit or wiring. I will call the emergency maintenance line now. If the apartment cannot stay safely warm, we will arrange a safe temporary place tonight.'], ['If it breaks a third time, I\'ll agree to buy a completely new heater for the apartment.', 'Because it failed again, I will ask a qualified technician to assess whether replacement is safer than another repair.'], ['Because it failed again, I will ask a qualified technician to assess whether replacement is safer than another repair.', 'Because it failed again, a technician will assess whether replacement is safer than repair.'], ["You're not bothering me, you're paying rent and deserve a working apartment. I should have replaced it after the first repair, honestly.",'You are not bothering me. Every tenant deserves a safe, working home, and I need to respond properly to a repeated failure.'], ['because tenants like you always pay on time and never cause unnecessary problems for me', 'because safe maintenance is my responsibility, not a reward for being an easy tenant']],
    tags: { 0: 'firmly', 1: 'concerned', 3: 'alert', 5: 'apologetic', 6: 'carefully', 7: 'seriously', 8: 'thoughtful', 9: 'responsibly', 11: 'firmly', 13: 'sincerely', 15: 'confirming', 17: 'warmly' },
    baseQuiz: [
      q('Why does Dewi call Pak Agus?', 'The apartment heater has failed again', 'The apartment is too expensive', 'The technician arrived early', 'The wiring has been replaced', 'The failure returned after three weeks.'),
      q('When did the unit stop?', 'Around eight while Dewi was cooking', 'At noon during work', 'Before the previous repair', 'After the technician called', 'Dewi gives a specific time and context.'),
      q('What must Dewi avoid?', 'Touching the heater or wiring', 'Using extra clothing', 'Calling the landlord', 'Leaving the kitchen', 'A qualified person should assess the faulty equipment.'),
      q('What will happen because this is a repeat failure?', 'A technician will assess repair versus replacement', 'They will wait for a third failure', 'Dewi must buy a heater', 'The old repair is assumed safe', 'Repeated failure triggers a stronger response.'),
      q('Why does Pak Agus say he must act?', 'Safe maintenance is a landlord responsibility', 'Dewi has never complained', 'The rent will increase', 'The technician knows Dewi', 'Tenant safety is not conditional on being easy or quiet.'),
    ],
    additions: [
      q('Why is “extra blankets” alone an incomplete plan?', 'The home may become unsafely cold before morning', 'Blankets always damage heaters', 'Dewi has no blankets', 'The technician needs them', 'The revised response considers whether staying in the apartment is safe.'),
      q('What is the purpose of the emergency maintenance call?', 'To obtain qualified advice about the immediate risk', 'To teach Dewi how to repair wiring', 'To delay the morning visit', 'To document rent payment', 'A strange noise and shutdown may need more than routine scheduling.'),
      q('What temporary option is discussed?', 'A safe place to stay if the apartment cannot remain warm', 'Buying an unapproved heater', 'Sleeping in the kitchen', 'Repairing the unit alone', 'Alternative accommodation protects the tenant while the fault is assessed.'),
      q('How does Dewi communicate effectively?', 'She gives the history, timing, symptom, and a reasonable replacement question', 'She promises to fix the unit', 'She hides that it failed before', 'She demands an exact diagnosis', 'Specific facts help the landlord choose an appropriate response.'),
      q('What principle replaces praise for a “good tenant”?', 'Housing safety applies regardless of a tenant’s convenience to the landlord', 'Only punctual tenants receive repairs', 'Repeated failures are minor inconveniences', 'A landlord may wait until equipment fails three times', 'Basic maintenance is a responsibility, not a personal favor.'),
    ],
  },
  {
    id: 'a2-daily-04', level: 'A2', title: 'Why I Started Setting Boundaries at Work', scriptDecision: 'revise; remove a birthday setting and keep the boundary lesson within an ordinary family dinner',
    replaceText: [["during my sister's birthday dinner, when I answered three messages before the cake was even served", 'during a family dinner with my sister, when I answered three messages before our meal was even served'], ['one quiet hour that belongs completely to you', 'one protected hour, while making sure genuine emergencies have a clear contact route']],
    tags: { 0: 'tired', 2: 'honestly', 3: 'regretfully', 5: 'determined', 6: 'uneasy', 7: 'surprised', 9: 'reflective', 11: 'calmly', 12: 'grateful', 14: 'encouraging' },
    additions: [
      q('What fear maintained the narrator’s availability?', 'Others might see him as lazy or uncommitted', 'The manager required vacation replies', 'His sister needed work updates', 'Every message was an emergency', 'The habit grew from an assumption about how commitment looked.'),
      q('What made the family dinner a turning point?', 'His sister’s disappointment showed the cost outside work', 'The meal was served late', 'His manager sent a complaint', 'The phone stopped receiving messages', 'The nonverbal reaction exposed a damaged relationship.'),
      q('Why did the first quiet evenings feel wrong?', 'Constant availability had become a learned expectation', 'Coworkers were angry', 'The emergency route had failed', 'The narrator disliked family time', 'Discomfort continued even without an external demand.'),
      q('How did boundaries improve work rather than reduce care?', 'Rest allowed clearer and more focused participation', 'The narrator worked fewer required hours', 'All difficult messages disappeared', 'Coworkers took over every task', 'Energy and attention replaced exhaustion and resentment.'),
      q('What makes the closing advice responsible?', 'It protects time while preserving a route for real emergencies', 'It tells everyone to ignore all work', 'It assumes every job has the same hours', 'It requires a full weekend offline', 'A boundary should fit actual responsibilities and urgent needs.'),
    ],
  },
  {
    id: 'a2-daily-05', level: 'A2', scriptDecision: 'keep; practical grocery podcast distinguishes planning, inventory, bulk cooking, tracking, and hunger-driven choices',
    tags: { 0: 'welcoming', 3: 'honestly', 5: 'practical', 7: 'thoughtful', 9: 'amused', 11: 'reflective', 13: 'warmly', 15: 'practical', 17: 'surprised', 19: 'encouraging' },
    additions: [
      q('Why did food waste occur before budgeting?', 'Shopping was disconnected from planned meals', 'The weekly limit was too low', 'Frozen meals spoiled immediately', 'Receipts were stored in a folder', 'Random purchases were not matched to actual cooking.'),
      q('What did checking the cupboard add beyond making a list?', 'It prevented buying items already owned', 'It increased restaurant spending', 'It removed all snack purchases', 'It set the weekly budget', 'An inventory made the list accurate.'),
      q('How does freezing portions solve a specific problem?', 'It provides food when tiredness would otherwise lead to eating out', 'It makes every ingredient cheaper', 'It removes the need to plan meals', 'It guarantees no food expires', 'Ready meals preserve convenience within the budget.'),
      q('Why are receipts useful over time?', 'They reveal repeated spending patterns', 'They replace the shopping list', 'They keep food fresh', 'They decide what Farid may eat', 'Small purchases become visible when reviewed together.'),
      q('Which advice targets impulse buying directly?', 'Do not shop while hungry', 'Cook only one portion', 'Avoid all snacks', 'Never eat outside the home', 'Hunger can make unplanned food look more necessary.'),
    ],
  },
  {
    id: 'a2-daily-06', level: 'A2', scriptDecision: 'revise; keep gradual sleep-hygiene changes while removing caffeine ambiguity and adding a professional-care boundary',
    replaceText: [['making tea around nine', 'making a caffeine-free warm drink around nine'], ['If your evenings feel out of control too, maybe start with just moving your phone, mine made a bigger difference than I imagined.', 'Moving a phone may be one useful experiment. If serious sleepiness or sleep problems continue, seek appropriate health advice instead of relying on one habit.']],
    tags: { 0: 'tired but proud', 2: 'reflective', 3: 'embarrassed', 5: 'determined', 6: 'restless', 7: 'calmly', 8: 'surprised', 10: 'reflective', 12: 'honestly', 14: 'carefully' },
    additions: [
      q('What evidence weakened the work-stress explanation?', 'The late habit continued during calm work weeks', 'The manager denied any stress', 'The phone was used only at work', 'Weekends had earlier bedtimes', 'The pattern remained when the claimed cause was absent.'),
      q('Why was falling asleep in the meeting significant?', 'The schedule was affecting daytime function and work', 'The meeting occurred at midnight', 'The narrator had finished every task', 'The manager recommended tea', 'The consequence showed the issue was more than inconvenience.'),
      q('What role does the warm drink play?', 'It is a repeated signal that the day is ending', 'It medically treats every sleep problem', 'It replaces the need for a bedtime', 'It keeps the narrator awake', 'A caffeine-free routine supports transition rather than acting as a cure.'),
      q('How does the narrator respond to occasional slips?', 'She returns to the routine instead of treating one night as failure', 'She gives up the changes', 'She removes all weekend activities', 'She stays awake the next night', 'The story presents improvement as imperfect but continuing.'),
      q('When is professional advice appropriate?', 'When serious sleepiness or sleep difficulty continues', 'After any single late night', 'Only if moving the phone works', 'Never, because the habit solved it', 'Persistent symptoms may need assessment beyond self-help.'),
    ],
  },
  {
    id: 'a2-daily-07', level: 'A2', title: 'Two Shelter Volunteers Plan the Dog-Walking Rota', speakers: [{ name: 'Tara', gender: 'female' }, { name: 'Nisa', gender: 'female' }], scriptDecision: 'replace; avoid an unsuitable mixed-household and pet premise while retaining shared responsibility and animal welfare',
    replaceScript: [
      'Tara: [concerned] Nisa, the shelter coordinator said Bimo’s evening walk was recorded late twice this week.',
      'Nisa: I saw that. Several volunteers helped with food, but everyone assumed another person had taken him outside.',
      'Tara: The unclear rota is unfair to the dog. Exercise, water, and observation cannot depend on someone noticing by chance.',
      'Nisa: [thoughtful] Let us make fixed morning roles and confirmed evening roles. Which time can you truly protect?',
      'Tara: I can do Monday, Wednesday, and Friday mornings before work. I should not promise every morning because Tuesday begins early.',
      'Nisa: Good. I can cover Tuesday and Thursday, and the weekend team already has two trained walkers.',
      'Tara: [practical] Evenings change more often. What if the assigned person confirms in the group by four o’clock?',
      'Nisa: If there is no confirmation, the backup volunteer receives an alert. We should never wait until the dog is already distressed.',
      'Tara: The walker also needs to refill water and record appetite, energy, and anything unusual.',
      'Nisa: [carefully] Yes, but volunteers should not diagnose illness. A concern goes to shelter staff or the veterinarian.',
      'Tara: What about new volunteers who want to help?',
      'Nisa: They first learn leash safety and walk with a trained person. Bimo is strong when he becomes excited.',
      'Tara: [relieved] This is better than our old color-coded calendar because it includes confirmation and backup.',
      'Nisa: The calendar was attractive, but nobody owned the final check.',
      'Tara: I will put the rota near the staff desk and in the private volunteer group.',
      'Nisa: [firmly] Keep visitor names and medical notes out of the group. It needs only animal-care tasks and volunteer shifts.',
      'Tara: Agreed. We can review the plan after two weeks and ask staff whether Bimo’s routine became more consistent.',
      'Nisa: If a shift repeatedly fails, we change the rota rather than blaming the dog or hiding the missed care.',
      'Tara: [warmly] Clear responsibility is part of kindness. Good intentions are not enough if the animal’s needs are missed.',
      'Nisa: Exactly. I will confirm tonight’s walk now, and you can check the water record afterward.'
    ],
    tags: { 0: 'concerned', 3: 'thoughtful', 6: 'practical', 9: 'carefully', 12: 'relieved', 15: 'firmly', 18: 'warmly' },
    baseQuiz: [
      q('What problem did the shelter coordinator report?', 'Bimo’s evening walk was recorded late twice', 'Bimo refused every meal', 'The weekend team had resigned', 'The dog had no trained walkers', 'Unclear responsibility caused delayed care.'),
      q('Why does Tara reject promising every morning?', 'Her Tuesday schedule would make the promise unrealistic', 'She dislikes morning walks', 'Nisa requested all mornings', 'The shelter is closed on Tuesday', 'She matches commitment to actual availability.'),
      q('How will evening shifts be protected?', 'An assigned person confirms, with a backup if needed', 'Any visitor may notice the leash', 'The dog chooses a volunteer', 'Only the calendar is checked at night', 'Confirmation and backup prevent assumption gaps.'),
      q('What must a walker record?', 'Water, appetite, energy, and unusual observations', 'A medical diagnosis', 'Visitor names', 'Every private staff note', 'The record supports continuity without exceeding the volunteer role.'),
      q('How are new volunteers introduced?', 'They learn safety and walk with a trained person', 'They immediately walk alone', 'They only read the old calendar', 'They receive the veterinarian’s password', 'Training protects both people and the animal.'),
    ],
    additions: [
      q('Why did the old calendar fail?', 'It displayed shifts but did not ensure anyone confirmed completion', 'Its colors frightened Bimo', 'It included too many veterinarians', 'The staff desk had no space', 'A schedule needs ownership and follow-through.'),
      q('What happens when a volunteer notices a health concern?', 'Shelter staff or a veterinarian assesses it', 'The volunteer diagnoses and treats it', 'The concern is posted publicly', 'The walk continues without a note', 'Observation and professional judgment have different roles.'),
      q('Why is the volunteer group private and limited?', 'Care coordination should not expose unrelated personal data', 'The public is not allowed to know the shelter exists', 'Volunteers cannot discuss shifts', 'Bimo’s name is confidential', 'The group contains only information needed for the task.'),
      q('What will the two-week review measure?', 'Whether the care routine became more consistent', 'Whether every volunteer likes the colors', 'Whether Bimo can skip walks', 'Whether the dog should live with Tara', 'Review tests the system against the animal’s actual needs.'),
      q('What is the dialogue’s central ethical point?', 'Kind intentions need clear responsibility to become reliable care', 'Volunteers should accept every shift', 'Animals can wait until someone remembers', 'A written rota removes all need for communication', 'Good character is shown through dependable action.'),
    ],
  },
  {
    id: 'a2-daily-08', level: 'A2', scriptDecision: 'keep; strong personal-finance story targets automatic spending without shaming social meals or generosity',
    tags: { 0: 'warmly', 1: 'curious', 3: 'surprised', 5: 'honestly', 6: 'reflective', 7: 'prepared', 9: 'thoughtful', 11: 'generously', 13: 'calmly', 14: 'encouraging' },
    additions: [
      q('Why did the narrator initially underestimate spending?', 'Individual purchases were small and easy to forget', 'The bank account was incorrect', 'Household costs were hidden', 'Friends paid for every meal', 'Low prices did not prevent a large combined effect.'),
      q('What caused avoidable motorcycle rides?', 'Leaving home too late to walk', 'Unsafe walking routes every day', 'A dislike of public transport', 'Heavy household shopping', 'Earlier preparation changed the transport choice.'),
      q('Why is lunch with a friend not treated as the main problem?', 'It was a visible, valued choice rather than automatic repetition', 'It cost less than water', 'The friend returned the money', 'Social meals never affect budgets', 'The narrator distinguishes priorities from unnoticed habits.'),
      q('What prevents the budget from becoming hard-hearted?', 'Money remains for generosity and unexpected needs', 'Every comfort is removed', 'Only household expenses are tracked', 'Friends choose the categories', 'The plan leaves room for care and uncertainty.'),
      q('Why track closely only one week each month?', 'It provides evidence without making daily life constantly anxious', 'The other weeks have no spending', 'The phone note expires weekly', 'The categories change every Sunday', 'The method balances useful information with sustainability.'),
    ],
  },
  {
    id: 'a2-daily-09', level: 'A2', scriptDecision: 'keep; excellent paper-management system combines retrieval, minimal retention, encryption, emergency access, and secure destruction',
    tags: { 0: 'frustrated', 1: 'surprised', 2: 'determined', 4: 'carefully', 6: 'securely', 7: 'thoughtful', 8: 'firmly', 9: 'relieved', 11: 'reflective', 13: 'practically', 14: 'encouraging' },
    additions: [
      q('Why is the drawer placed away from water and heat?', 'To reduce physical damage to important papers', 'To hide it from the building manager', 'To make cooking easier', 'To improve the folder labels', 'Storage location protects the documents as well as organizing them.'),
      q('Why are identification numbers excluded from the contents list?', 'The list can guide retrieval without exposing sensitive data', 'The numbers are never useful', 'The folders contain no identity copies', 'Encryption automatically removes them', 'A simple index should reveal as little private information as possible.'),
      q('What risk does the trusted-family arrangement address?', 'Emergency access should not depend on one unavailable person', 'Family members need all account passwords', 'The drawer cannot be locked', 'The narrator may forget how to read labels', 'Limited continuity planning supports real emergencies.'),
      q('Why are some papers shredded instead of recycled normally?', 'Addresses or account details could be exposed', 'Shredded paper lasts longer', 'Recycling does not accept mail', 'Old letters are always illegal to keep', 'Secure destruction matches the sensitivity of the content.'),
      q('What makes the system more than visual tidiness?', 'It protects privacy while making records quickly usable', 'It uses expensive matching folders', 'It keeps every document forever', 'It removes the need for annual review', 'Function and information security are the real goals.'),
    ],
  },
  {
    id: 'a2-daily-10', level: 'A2', scriptDecision: 'keep; coherent cupboard-first planning combines inventory, dates, meal sequence, waste reduction, and shared updates',
    tags: { 0: 'warmly', 2: 'surprised', 4: 'reflective', 6: 'practical', 8: 'thoughtful', 10: 'carefully', 12: 'measured', 14: 'pleased', 16: 'warmly', 18: 'prepared', 19: 'honestly' },
    additions: [
      q('What caused the crowded cupboard?', 'Rizal repeatedly bought from memory', 'Iman planned too many meals', 'Fresh food was stored there', 'The whiteboard listed no items', 'Assumption replaced checking.'),
      q('How do package dates affect the meal plan?', 'Items that should be used sooner are scheduled first', 'Expired food is automatically cooked', 'Dates decide who shops', 'Only fresh food receives a date', 'Meal order helps reduce avoidable waste.'),
      q('Why will they buy only one loaf?', 'Existing flour can become later flatbread', 'Bread cannot be stored', 'They plan no lunches', 'The shop limits purchases', 'Current supplies cover part of the need.'),
      q('What weakness could the whiteboard still have?', 'Someone may list an item another person already bought', 'It cannot show words', 'It always increases food waste', 'Only Rizal may read it', 'The board improves communication but does not replace a final check.'),
      q('Why does Iman photograph both cupboard and list?', 'To carry current evidence while shopping', 'To post the food publicly', 'To replace checking dates', 'To calculate restaurant prices', 'The photos reduce dependence on memory at the shop.'),
    ],
  },
];
