import { q } from '../helpers.mjs';
const R=(id,decision,additions,extra={})=>({id:`a2-education-${id}`,level:'A2',scriptDecision:decision,tags:{0:'thoughtful',2:'reflective',4:'honestly',6:'encouraged',8:'determined',10:'warmly',12:'hopeful',14:'gently',17:'warmly'},additions,...extra});
export const reviews=[
R('01','revise lightly; retain adult career learning while acknowledging prior support and avoiding a universal claim about confusion',[
q('What belief initially limited the narrator?', 'Technical learning seemed reserved for people with a different background','Cashiers were not allowed to study online','The course required a university degree','The coworker doubted the narrator','The barrier was partly an assumption about who could belong.'),q('Why did the calculator change motivation?', 'It turned confusing lessons into a working result','It immediately produced a software job','It took only thirty minutes','The cousin began using it for orders','A small completed project made progress visible.'),q('How did the bakery website extend learning?', 'It solved a real need for another person','It replaced every course exercise','It was built without any prior guidance','It guaranteed the job application','A practical user made the skill feel useful.'),q('What does the narrator now compare fairly?', 'Current progress with an individual learning path','Salary with university tuition','Speed with the cousin’s business','The calculator with every website','Slower progress no longer becomes shame.'),q('What is the balanced lesson about confusion?', 'It can be a normal stage that needs support and practice','It always proves understanding will follow','It should be hidden from colleagues','It means the course is wrong','Confusion is survivable but not automatically productive.')
],{replaceText:[['because I had built it completely from nothing','because I had combined lessons, examples, feedback, and my own effort into something useful'],['confusion is simply the beginning of understanding','confusion can be a normal stage, and I can ask for help or break the idea into smaller steps']]}),
R('02','revise; make the partners same-gender and replace late caffeine and excessive rehearsal with a focused finish and sleep',[
q('Why do Sari and Laila divide the remaining work?', 'Each person takes the section matching her strength','The professor assigned separate grades','They cannot edit the same file','The presentation topic changed','A specific division reduces panic.'),q('What is their plan for an unknown question?', 'Admit the limit and check it afterward','Invent a confident answer','Ask the audience to ignore it','Change the conclusion','Honest uncertainty protects accuracy.'),q('Why does a short break help?', 'Tired thinking may improve after a pause','It removes the wrong statistics','It replaces all rehearsal','The deadline moves later','The break is used as a reset, not avoidance.'),q('How will they avoid sacrificing the whole night?', 'Do one timed run, record issues, and stop at a set time','Practice twice after midnight','Drink more coffee','Rewrite every slide','A boundary protects sleep before presenting.'),q('What makes their proposed conclusion effective?', 'It follows the evidence and leaves a clear final idea','It promises renewable energy solves everything','It avoids mentioning the data','It adds more statistics without checking','The ending is hopeful but tied to actual results.')
],{speakers:[{name:'Sari',gender:'female'},{name:'Laila',gender:'female'}],replaceText:[['Fajar:','Laila:'],['I\'ll make us some coffee before we continue.','I’ll bring water and a light snack before we continue.'],['we should practice the whole presentation twice before we sleep tonight','we should do one timed practice, note the weak parts, and stop at our agreed time so we can sleep'],['Thank you for staying calm tonight, Fajar.','Thank you for staying calm tonight, Laila.']]}),
R('03','keep; authentic hobby-learning interview combines apps, group practice, embarrassment, intrinsic motivation, and real use',[
q('Why did music matter more than a formal goal?', 'It created curiosity strong enough to begin','It taught Rian full sentences','It prepared him for an exam','It gave him a conversation group','Interest, not obligation, started the learning.'),q('What did the Saturday group add beyond the app?', 'Real speaking practice with other learners','A required school grade','Free travel abroad','Perfect pronunciation','Interaction exposed mistakes and built comfort.'),q('How did Rian reinterpret embarrassing errors?', 'They were normal evidence of being a beginner','They showed adults cannot learn','They had to be hidden from the group','They meant the app had failed','Remembering others’ beginnings reduced shame.'),q('What kept progress moving without an exam?', 'Personal curiosity and regular practice','Fear of the host','A university deadline','The waiter’s expectations','The motivation was internally maintained.'),q('Why was the restaurant moment important?', 'A real person understood language developed slowly over time','It proved Rian spoke without mistakes','It ended the need to study','The waiter joined the group','Use in context made the long practice tangible.')
]),
R('04','revise lightly; keep productive exam recovery while avoiding the claim that failure is always a better teacher than success',[
q('Why did blaming the exam feel easier?', 'It protected the narrator from examining weak preparation','The exam was officially canceled','Colleagues agreed it was unfair','The results contained no details','External blame delayed personal change.'),q('What did the result review reveal?', 'Basic misunderstandings, not only difficult questions','A marking error','Perfect definitions','A lack of exam time only','The diagnosis changed the next study method.'),q('Why did problem-solving outperform memorization here?', 'It required applying concepts rather than recognizing words','It made the exam shorter','It removed the need for definitions','It guaranteed every answer','The certification tested usable understanding.'),q('How did the group expose shallow knowledge?', 'Explaining ideas made gaps visible','Other students gave the answers','The group changed the exam','The narrator stopped practicing alone','Teaching requires more than familiarity.'),q('What is the revised final lesson?', 'Careful review of failure can improve learning','Failure always teaches more than success','Every failed exam should be repeated','Passing first time prevents real knowledge','The value comes from analysis and changed action.')
],{replaceText:[['Failure taught me more about real learning than success ever could have','Reviewing that failure honestly taught me something this particular success alone would not have shown']]}),
R('05','keep; sibling dialogue broadens major options and encourages research without pretending the first choice must be perfect',[
q('What outside pressure narrows Dewi’s view?', 'Family conversations repeatedly center medicine and engineering','Rio requires biology','The deadline bans other subjects','Environmental programs are unavailable','Familiar prestigious fields crowd out quieter options.'),q('Why does Rio mention changing his own major?', 'To show that uncertainty and revision can be normal','To tell Dewi to copy his path','To prove majors do not matter','To delay Friday’s deadline','Personal experience reduces the demand for perfection.'),q('What should Dewi research besides course titles?', 'Programs and the experiences of current students','Only future salary','Family opinions alone','Rio’s old subjects','Multiple sources help her understand the actual path.'),q('Does Rio claim changing direction is always easy?', 'No, he says it is possible but was confusing and frightening','Yes, universities allow it without cost','No, because it is forbidden','Yes, he felt confident throughout','His reassurance remains realistic.'),q('What improved before Dewi made a final choice?', 'Her set of options and the questions she could investigate','The application deadline','The cost of medicine','Her biology grades','A useful conversation creates a better decision process, not the decision itself.')
]),
R('06','keep; thoughtful teacher narrative connects mobility-related gaps with private scaffolding and evidence-based expectations',[
q('Why were Budi’s grades a poor measure of ability?', 'Repeated school changes created gaps and instability','He never knew any answers','His father opposed school','The teacher made tests too easy','Context explained uneven performance.'),q('Why begin with private questions?', 'They allowed evidence of knowledge without public pressure','They lowered the curriculum permanently','They hid Budi from classmates','They guaranteed correct answers','The teacher adjusted participation while still checking learning.'),q('What belief did Budi carry from earlier experience?', 'Difficulty meant he was permanently bad at learning','Moving schools made him more intelligent','Teachers always understood him','Math was the only useful subject','Repeated struggle had become an identity judgment.'),q('What later action shows growing confidence?', 'Helping a classmate with mathematics','Receiving a private question','Writing a farewell letter','Moving to another school','He used knowledge publicly to support someone else.'),q('How did Budi change the teacher’s future practice?', 'New quiet students receive questions before assumptions','Every student receives the same private task','Grades are no longer used','Moving families are asked to stay','The experience became a general habit of inquiry, not a label.')
]),
R('07','revise; retain adult-scholarship story while adding official verification and avoiding a universal application promise',[
q('What responsibility interrupted the caller’s first degree?', 'Supporting younger siblings after her father died','Failing every class','Moving for a job','Losing interest in study','Family finances required her to leave at twenty-one.'),q('Why did age feel like a barrier?', 'She feared the committee would see her as too far behind','The program published an age limit','Her sister opposed applying','Online study required youth','The fear existed before the committee’s actual response.'),q('How did she verify the advertisement?', 'She checked the institution’s official site and contacted its office','She trusted the social post alone','She sent money through a message link','Her sister guaranteed it','Verification protects applicants from scholarship scams.'),q('What preparation supports her return?', 'Slow textbook reading and an adult-student group','Pretending the long gap does not matter','Leaving her job immediately','Buying every course book','Academic review and peer support address the transition.'),q('What is the careful final advice?', 'Verify suitable programs and submit a truthful application','Every adult will receive funding','Apply through any advertisement tonight','Age never affects practical planning','Encouragement includes legitimacy and individual eligibility.')
],{replaceText:[['My sister saw an advertisement online and sent it to me','My sister saw an advertisement online; I verified it on the institution’s official site and called its scholarship office'],['Absolutely, especially if money or time once stopped them, because programs like this exist specifically for people like us.','I would encourage them to verify legitimate programs, check eligibility, and apply honestly if the opportunity fits their situation.'],['finally submits their own application tonight','takes one safe next step toward a suitable, verified program']]}),
R('08','keep; excellent metacognitive script separates vocabulary, listening, grammar, attention, knowledge, and strategy errors',[
q('Why was checking only the score insufficient?', 'It measured performance without guiding the next study action','The score was always wrong','Teachers did not use scores','The test contained no patterns','Mistakes carried diagnostic information the number alone lacked.'),q('What pattern linked vocabulary errors?', 'Familiar-looking words were chosen without sentence context','Every unknown word was skipped','Numbers were confused','Grammar rules were missing','Recognition overrode careful reading.'),q('Why did listening require a different solution?', 'Topic understanding was present, but precise details were missed','The audio used no vocabulary','Every speaker corrected themselves','The narrator could not hear anything','The error type called for detail notation and correction awareness.'),q('Why take one grammar item to the teacher?', 'It reflected missing understanding rather than simple carelessness','The answer key was lost','The log had no grammar column','The test score was too high','Correct classification determined the response.'),q('What made later errors more useful even before perfect scores?', 'Their causes were easier to explain and address','They were all the same type','The narrator stopped reviewing','Comfortable exercises disappeared','Clear diagnosis improved control of future practice.')
]),
R('09','keep; strong reading-strategy story uses purpose, librarian mediation, background building, selective reading, and honest limits',[
q('Why did popularity become unhelpful pressure?', 'The narrator treated others’ praise as a command to finish','The book was not historically accurate','The librarian disliked popular books','Online readers knew his goals','Public value did not guarantee personal readiness or fit.'),q('Why did the librarian ask about interest first?', 'A useful entry point depends on the reader’s purpose','She wanted to avoid offering books','The original book had no index','Only family history was available','Purpose guided the alternatives.'),q('How did the overview and letters serve different roles?', 'One built structure; the other made daily experience concrete','Both repeated the original chapter','One was easier only because it was illustrated','The letters supplied exam answers','The resources complemented each other.'),q('What changed when the narrator returned to the original?', 'Background knowledge made references more understandable','Every page became easy','The librarian explained each sentence','The language had been rewritten','Preparation changed the reader, not the book.'),q('Why can selective reading be serious learning?', 'Relevant sections can answer a clear question honestly','Indexes remove the need for context','Finishing books has no value','Difficult chapters should always be skipped','Method should serve a defined learning purpose.')
]),
R('10','keep; excellent teaching-demo coaching aligns one goal, learner thinking, evidence of learning, time, and backup materials',[
q('Why are twelve slides a problem beyond speed?', 'They leave little space for learner thinking and practice','The interview allows only four colors','Reliable sources need no examples','The screen cannot show twelve files','Teaching quality is not the amount of content displayed.'),q('What makes the first comparison active?', 'Learners observe two sites before receiving the explanation','Nisa reads all three signs','The interviewer chooses the answer','The slide contains a definition','Observation gives learners a task.'),q('Why announce a ten-second pause?', 'Learners understand that silence is intentional thinking time','It fills the five minutes','Nisa can read her notes','The screen needs to load','Clear timing prevents silence from feeling accidental.'),q('What does the final question assess?', 'Whether learners can apply checks to a source','Whether they memorized Nisa’s wording','Whether they prefer one picture','Whether they can read twelve slides','A reasoned choice reveals usable understanding.'),q('How should Nisa handle no audience answer?', 'Model a possible observation and continue calmly','Skip the learning goal','Rush through all slides','Wait for the whole five minutes','The demo remains interactive in design without depending on a real class response.')
])];
